### ISSUE TITLE
[suggestion] a biome whitelist option

### ISSUE THREAD

**Issue by KihakuGato** [TelepathicGrunt/RepurposedStructures#101]
This would be especially helpful in the cases of where a world generator type is buffet based- ex- the default Cave worldtype in vanilla minecraft is the plains biome. Another example would be mc worlds/modpacks where there may be limited dimensions from the norm (say the lack of a Nether dimension for example, yet wanting to be able to access Nether shipwrecks) and being able to whitelist another dimension's biomes as an alternative.

Being able to whitelist the specific biomes for preferred dungeons and mineshafts would be pretty helpful.

**Comment by TelepathicGrunt** [comment]
Yeah I have this in my todo for 1.17 as I'll need to redo the config system. 
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/107

it'll be a lot of work and with so many structures, I need to think of a better way to condense it while giving more freedom without making a million new config options lol.

**Comment by TelepathicGrunt** [comment]
Changed plans. 1.16.5-3.0.0 repurposed structures now has a config file dedicated to biome whitelisting/blacklisting now! it is in the repurposed_structures-forge folder in the config folder. You can do `"all": "*"` in disallowedBiomes  to blacklist all dimensions and then pick and choose which dimension you want to spawn structures in with the allowedBiomes config entry. allowedBiomes overrides disallowedBiomes
