### ISSUE TITLE
Compatibility Issue with Lycanites 1.16.5

### ISSUE THREAD

**Issue by P4YN-Ki** [TelepathicGrunt/RepurposedStructures#102]
Lycanites has a Mob called Aegis that recognises Vanilla Villages as a Spawn point for the Mob. With this mod installed also, the mob just stops spawning entirely. Not sure what's causing it, but if you could take a look, it'd be much appreciated.

**Comment by TelepathicGrunt** [comment]
My villages are their own structures so lycanite will need to add mod compat code on their end to detect my villages as well. I'll try and poke them about it

**Comment by TelepathicGrunt** [comment]
I made a report to them here. Keep watch on this link to see if any progress can be made with this mob https://gitlab.com/Lycanite/LycanitesMobs/-/issues/831

**Comment by P4YN-Ki** [comment]
Thanks for the update. I'll also poke in the Discord, since the mods go really well together, compat should be something they are interested in.

**Comment by TelepathicGrunt** [comment]
While you wait for dedicated mod compat on Lycanite's end, there's a workaround you can do right now. As of 1.16.5-3.0.0 repurposed structures which I just released, there's now a new config file in config/repurposed_structures-forge folder that lets you change what mob spawns in my structures over time. This means, by editing that config file to add entries for villages, you could make aegis spawn over time rarely in RS villages. 

If you want villages to only have 1 or 2 Aegis ever, you can make a datapack that replaces RS's town center nbt files for villages with modified version that has the Aegis in them. The nbt files and their paths can be found here.
https://github.com/TelepathicGrunt/RepurposedStructures/tree/latest-released/src/main/resources/data/repurposed_structures/structures/village

I hope this helps!

**Comment by TelepathicGrunt** [comment]
gonna close this as it seems lycanite has a system to let players add extra spawner json files.
https://gitlab.com/Lycanite/LycanitesMobs/-/blob/master/src/main/resources/data/lycanitesmobs/spawners/village.json

 I am not sure how it works but there may be a way to datapack in more json files with each one's "structureId" pointing to an RS village: 

repurposed_structures:village_oak
repurposed_structures:village_badlands
repurposed_structures:village_birch
repurposed_structures:village_dark_oak
repurposed_structures:village_jungle
repurposed_structures:village_swamp
repurposed_structures:village_mountains
repurposed_structures:village_giant_taiga
repurposed_structures:village_crimson
repurposed_structures:village_warped

Seems like there's a ton of options. Just requires some effort to make the compat work
