### ISSUE TITLE
Quick question: is it okay to embed the datapacks straight into a public modpack?

### ISSUE THREAD

**Issue by pm065** [TelepathicGrunt/RepurposedStructures#106]
KubeJS has a data folder where you can put data to load automatically. Since the datapacks aren't on Curse, I want to ask permission to put them there (:

**Comment by TelepathicGrunt** [comment]
~~Yeah it is ok but you will need a mod to be able to distribute and apply the datapack automatically to worlds. For example, here's two you can look into:~~

~~https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack~~

~~https://www.curseforge.com/minecraft/mc-mods/open-loader~~

Hopefully this helps!

Edit: Oh i misread, you are using KubeJS to distribute them. yeah you can distibute the datapacks. The one I listed on my mod page or you make are fine to share. A lot of people list datapacks in the customization section of curseforge like here.https://www.curseforge.com/minecraft/customization/farlanders-spawn-in-warped-villages

I just keep my own RS datapacks on github pages so they are all in one place for users to find
