### ISSUE TITLE
[1.16.5] Crash when generating new chunks. Near village (?).

### ISSUE THREAD

**Issue by Gbergz** [TelepathicGrunt/RepurposedStructures#112]
Was flying in creative whilst in a test world when the integrated Singlepllayer server just crashed me to the Main Menu.

### Versions:
**Minecraft**: 1.16.5
**Forge**: 36.1.31
**Repurposed Structures**: [2.7.5-forge](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures/files/3346614)

### **Crash-Report**: https://gist.github.com/Gbergz/c793a760eb1677705adf5846dbfe5c98

Hopefully can get fixed, thanks in advanced.
**-** Gbergz

**Comment by TelepathicGrunt** [comment]
This is probably cause by another mod classloading TagCollectionManager too early and probably broke The Undergarden's worldgen features that relied on the tag. And the error cascades and broke my mod's structure pool files as a result which causes the crash you see.

There's a bit more info here: https://github.com/TelepathicGrunt/RepurposedStructures/issues/111

Are you using Terraforged? If so, update it to v0.2.12. If you have VanillaFoodPantry mod on, try removing that as well. If you don't have either of those mods on, can you put on the mod called [Blame](https://www.curseforge.com/minecraft/mc-mods/blame), get the crash to happen again, and then show me the latest.log file?

**Comment by Gbergz** [comment]
TerraForged is in the pack but its not used (as in the chosen preset). I don't have VanillaFoodPantry.

I don't have the Undergarden mod either.

Edit. I haven't updated Terraforged to 0.2.12 yet though. Still on 0.2.11, will update and test more.

**Comment by TelepathicGrunt** [comment]
Well, update Terrfaorged anyway and see if that resolves the issue as it doesn't matter if it is being used or not for worldgen as the tagfix thing they were doing is always ran. If the issue still perists, yeah try Blame and I can check out the latest.log and help you further with that

**Comment by Gbergz** [comment]
Updated a couple of mods (including terraforged) and the crash doesn't happen anymore, tried lots of stuff to reproduce it. 
I'll re-comment if it does happen again though.

**Comment by TelepathicGrunt** [comment]
Ah alright nice. Guess updating worked! I'll close this issue for now but yeah, will reopen if the issue comes back
