### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Tyrius1** [TelepathicGrunt/RepurposedStructures#114]
https://pastebin.com/nUabfSge
was flying around in creative
forge 36.2.0
mc 1.16.5
RS 2.7.12

**Comment by TelepathicGrunt** [comment]
So this is a modcompat issue but I'll need more info to be able to tell you which mod. You should put on the mod called [Blame](https://www.curseforge.com/minecraft/mc-mods/blame/files), enter a world, and then give me the latest.log file. That will greatly help narrow down the issue!

**Comment by TelepathicGrunt** [comment]
are you able to get more info? Or did you figure out the issue by now?

**Comment by Tyrius1** [comment]
Issue seems to be resolved. If it happens again I'll be sure to provide a full log with blame included

**Comment by TelepathicGrunt** [comment]
Ah thank you! Just reply with the logs here if it occurs and I'll reopen this report. Have fun!
