### ISSUE TITLE
[Mod Compat] Replace End structures' Phantom spawners with Spectre spawners if Deadly End Phantoms is installed

### ISSUE THREAD

**Issue by DarthCaesium** [TelepathicGrunt/RepurposedStructures#115]
You should make it so that if Deadly End Phantoms is installed, then End structures should use a different spawner table that contains Spectres in place of Phantoms.

**Comment by TelepathicGrunt** [comment]
for End Dungeon spawners, you can use a datapack to override what mobs their spawner block can have. This includes changing the chance for vanilla phantoms into deadly end phantoms like you want! Here's the datapack you can edit to do the changes and then put on. 
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/releases/tag/0.0.5

For End Outposts, as of 1.16.5-3.0.0 repurposed structures which I just released, there's now a new config file in config/repurposed_structures-forge folder that lets you change what mob spawns in my structures over time. This means, by editing that config file, you should be able to make Deadly End Phantoms spawn in End Outposts over time! 

Lastly, there's a few vanilla phantoms that is in the End Outpost's nbt file too that spawns when the structure generates. if you want to swap those, you can use a datapack to override the End Outposts's nbt files with modified ones that doesn't have the vanilla phantoms or swapped with Deadly End Phantoms. Here's what the nbt files are:
https://github.com/TelepathicGrunt/RepurposedStructures/tree/latest-released/src/main/resources/data/repurposed_structures/structures/outposts/end

Those are the only two End feature/structures that has phantoms. Hopefully this helps!

Let me know if the config for changing mob spawns over time isnt working
