### ISSUE TITLE
crash upon creating new world

### ISSUE THREAD

**Issue by KrystalTheFox** [TelepathicGrunt/RepurposedStructures#117]
recently, when I try to create a new world with repurposed structures mod, it immediately crashed after I click create world.
https://pastebin.pl/view/030c5981

Forge version: 36.0.45
Minecraft version: 1.16.5
RS: 2.7.12

**Comment by TelepathicGrunt** [comment]
You have a structure spacing/separation with invalid values. However, finding which structure it is is difficult unless you put on this mod called Blame https://www.curseforge.com/minecraft/mc-mods/blame

Put on Blame and reproduce the crash. The please share the latest.log file here so we can see which structure's spacing/separation needs to be fixed (usually in configs)

**Comment by KrystalTheFox** [comment]
Okay. I found out it was one of the structures that had min and max distance were backwards in the config file. I fixed it and it works fine now

**Comment by TelepathicGrunt** [comment]
Ah nice. Glad you found the issue! Im guess it was dungeons arise as I'm sorta recalling someone had that issue with their config before. I'll close this report now
