### ISSUE TITLE
Project: Vibrant Journeys broken json breaks RS entirely

### ISSUE THREAD

**Issue by SHXRKIEgg** [TelepathicGrunt/RepurposedStructures#118]
Gets stuck on the loading screen before it shows the world loading screen and just freezes.

Crash - https://pastebin.com/F4fz7NKU

**Comment by SHXRKIEgg** [comment]
Actually at this point its just random, sometimes works something it just freezes.

Update it seems to be the latest version of https://www.curseforge.com/minecraft/mc-mods/project-vibrant-journeys causing it

**Comment by TelepathicGrunt** [comment]
I'm not getting the tick loop issue but when using that mod and RS alone with Blame, Blame found they have broken configuredfeature which is cascading the error and preventing minecraft from loading my configuredfeatures it seems. Thus causing my mod to just die with the `empty or non-existent pool` spam that lasts forever and my structures not generating fully.
https://paste.ee/p/BHoxa

The configuredfeatures that is broken in their mod right now are:
projectvibrantjourneys:mega_redwood_tree
projectvibrantjourneys:redwood_tree
projectvibrantjourneys:redwood_forest_vegetation

also, they need to register projectvibrantjourneys:fallen_tree_feature configuredfeature as well. 

Hopefully they can address this soon. 

I bet if I put on one of my datapacks with pool_additions which activates that com.telepathicgrunt.repurposedstructures.utils.SafeDecodingRegistryOps code, then I would get the crash you have.

**Comment by SHXRKIEgg** [comment]
yeah I pretty much have all your datapacks too

**Comment by TelepathicGrunt** [comment]
Good news! PVJ released a new beta update to resolve this issue. I’ll close this report now but let me know if the issue still persists and I’ll reopen it
