### ISSUE TITLE
water_physics_overhaul crashing RS structures

### ISSUE THREAD

**Issue by ruiluth** [TelepathicGrunt/RepurposedStructures#119]
[crash-2021-07-27_22.30.01-client.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/6890100/crash-2021-07-27_22.30.01-client.txt)

Crashed while generating a new chunk in the Overworld.

Looked on Terraforged's github, but there is a similar issue closed there which stated that it's a third party issue. The next mod on the stack and the one I most recently installed was this one, so this seems like the most likely culprit.

**Comment by TelepathicGrunt** [comment]
Actually, this looks more like another mod broke the parsing of pool files for repurposed structures. Looking at your mod list, I see water_physics_overhaul-0.1.1 which is known for dangerously injecting new properties into vanilla blocks. This causes any mod or datapack that specifies blockstates in their worldgen json file to blow up and in the case of RS, it breaks my structures so badly that they cannot generate anymore and crashes. Here's the original report on that
https://github.com/TelepathicGrunt/RepurposedStructures/issues/97

Here's my comment about the issue on water physics overhaul's github
https://github.com/Sasai-Kudasai-BM/Water-Physics-Overhaul/issues/6#issuecomment-845598148

Does removing water_physics_overhaul fix the crash for you? if so, I'll close this report

**Comment by ruiluth** [comment]
I think you're right. I was testing both at the same time, but it does look like that's the problem. Thanks!

**Comment by TelepathicGrunt** [comment]
Ah glad we figured out the issue! I'll close this now
