### ISSUE TITLE
pyramid_ocean causing crashes with TerraForged generation

### ISSUE THREAD

**Issue by NielsPilgaard** [TelepathicGrunt/RepurposedStructures#123]
Going near an Ocean Pyramid causes a crash in worlds generated with TerraForged

Crash: https://paste.ee/p/FOJJ9

### Versions
- [Repurposed Structures v3.0.1 (1.16.5 MC)](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures/files/3402745) 
- [TerraForged v0.2.13](https://www.curseforge.com/minecraft/mc-mods/terraforged/files/3400572)
- Forge-1.16.5.36.2.1

**Comment by TelepathicGrunt** [comment]
The crash seems to be occurring when I schedule a tick to a bubble column block so it can automatically create the column of bubble upward when the chunk starts ticking after worldgen is done.
https://github.com/TelepathicGrunt/RepurposedStructures/blob/06670e05c8e960674aaecd7def7f0cd94212cb2a/src/main/java/com/telepathicgrunt/repurposedstructures/world/processors/BubbleColumnProcessor.java#L27

As for why it is crashing, I do not know. the specific vanilla code seems to do `p_205362_1_.getY() >> 4` so for that to be -1, something might be trying to force the ocean pyramid under y = 0 which shouldn't occur in normal terrain and is why I cannot reproduce the crash myself. Some other mod might be messing with structure gen somehow that cause the processor to run below y = 0.
![image](https://user-images.githubusercontent.com/40846040/128416203-f3a2128d-8fa6-439a-8b60-18137d7e7133.png)

I'm gonna try seeing if I can restrict it between 0 and 255 but I would need you to test it

**Comment by TelepathicGrunt** [comment]
@NillerMedDild when you are able to, could you please try this jar and see if the height restriction for the processor prevents the crash? It won't solve the issue of someone forcing the pyramid in a weird spot but this should hopefully workaround the issue. 
[repurposed_structures_forge-3.0.4b+1.16.5.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/6941492/repurposed_structures_forge-3.0.4b%2B1.16.5.zip)

Hmm this might crash if the pyramid spawns in a floating island world and it ends up in the void. I will test that

**Comment by NielsPilgaard** [comment]
Will do 👍

**Comment by NielsPilgaard** [comment]
I can't reproduce the issue ^^'
Edit: With the old jar, that is

**Comment by TelepathicGrunt** [comment]
Just tested spawning the ocean pyramid in the end with a slight bump in height so that its bubble columns is right on the edge. Turns out, yeah it crashes as mc will attempt to spawn the entire structure piece and the part of the structure below the world bottom will also run the processor. And negative y values will be fed into the bubble column processor which then crashes the scheduling of fluid ticks. Tested it with the fix and it no more crashing. 

v3.0.4 is now released on curseforge for download. Thank you for reporting this!

**Comment by NielsPilgaard** [comment]
Damn that was fast, thanks!
