### ISSUE TITLE
Missing loot table for desert pyramid

### ISSUE THREAD

**Issue by cheshyrp** [TelepathicGrunt/RepurposedStructures#125]
It's unclear from this report if the issue lies with Repurposed Structures or End Remastered. Apologies if this is the wrong place to report it.

****************** Blame Report 1.16.5-3.2.3-forge ******************

 Found a Loot Table path that does not exist:  endrem:minecraft_chest/desert_pyramid
 The path represented by this Loot Table is:  data/endrem/loot_tables/minecraft_chest/desert_pyramid.json
 Loot Table method called at:  net.minecraft.loot.LootContext.func_227502_a_
                               com.telepathicgrunt.repurposedstructures.misc.EndRemasteredDedicatedLoot.handleDedicatedModCompat
 Most common cause is that the Loot Table file is not actually at that location.
 Please let the mod author know about this so they can check to see if their Loot Table is correct.

**Comment by TelepathicGrunt** [comment]
Did you update endrem to their latest? They are on 1.16.3+ B4.0.3.

I updated Repurposed Structures to grab the new loot tables in Endrem as they changed their paths and loot tables in a recent update.

**Comment by cheshyrp** [comment]
Yes I did. I have the latest version of both mods.

**Comment by TelepathicGrunt** [comment]
Looking closer, this is the loot table in end rem:
https://gitlab.com/endrem/end-remastered/-/blob/master/src/main/resources/data/endrem/loot_tables/minecraft_chest/desert_pyramid.json

This is the entries I have that looks for it:
https://github.com/TelepathicGrunt/RepurposedStructures/blob/6d6f351a452eab3c5f98df014b50481a44e378ba/src/main/java/com/telepathicgrunt/repurposedstructures/misc/EndRemasteredDedicatedLoot.java#L30

They match up and should work. Which makes me wonder if their loot table was failed to be parsed for some reason. Can you share your entire latest.log file?

**Comment by cheshyrp** [comment]
Pastebin consistently timed out, so I zipped the log and posted it to Dropbox. Here's the link: https://www.dropbox.com/s/v5rw4qczzv0yea4/latest.zip?dl=0

**Comment by TelepathicGrunt** [comment]
Oh i figured it out. I was looking at Master branch on their repo but their latest update is the update-4 branch. I need to change minecraft_chest to minecraft/chest in my mod. 
![image](https://user-images.githubusercontent.com/40846040/128639003-35c3d8b9-e027-45f1-84ac-80d2d3905db2.png)


Sorry about that. next update of RS will have this fixed!
Just to be clear, desert temples still have loot. It's just RS structure's chests cannot import end rem's items from their loot tables as I got the wrong path

**Comment by TelepathicGrunt** [comment]
Fixed in latest release now!
