### ISSUE TITLE
Server Crashes when attempting to generate End Mineshafts and End Strongholds

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [TelepathicGrunt/RepurposedStructures#130]
Forge Version: 36.2.2
Repurposed Structures Version: 3.1.0
Minecraft Version: 1.16.5
Crash Report: https://gist.github.com/NJL5390/193ea4dc0910634167eae920c9e35013

Hi,

I was just testing my modded server and when I traveled to the end I got this crash. It seems to point to the end mineshafts present in your mod. Would you be able to help with this?

This crash doesn't happen in singleplayer and only happens on the server.

Thanks in advance!

**Comment by The-Bernician-Lamb** [comment]
I was able to reproduce the issue twice in the same session with blame installed. The first time the server didn't crash, it just disconnected me after trying to /locate an End Mineshaft. The second time the server actually crashed after I attempted to teleport to the Outer End Islands. So here's the latest log with Blame: https://gist.github.com/NJL5390/6ddf9ea6f9a13a7f277d191a3944803b
(I will warn you, It's incredibly long).

I hope this helps!

**Comment by TelepathicGrunt** [comment]
shit. I called a method that only exists on the client. I’ll release fix soon hopefully

**Comment by The-Bernician-Lamb** [comment]
Thought I'd mention that I sometimes seem to get this issue in relation to End Strongholds too.

**Comment by TelepathicGrunt** [comment]
Yeah I know what the issue is. The method step() only exists on the client and not the server so the server dies if it tries to call the method. End stronghold has the same code too. https://github.com/TelepathicGrunt/RepurposedStructures/blob/7d9fce892cadccc2aa487514e8c371f2992daa17/src/main/java/com/telepathicgrunt/repurposedstructures/world/structures/MineshaftEndStructure.java#L65

**Comment by TelepathicGrunt** [comment]
Well dang it. I tried to push a quick fix for it but then my laptop died and I cannot get to my charger till tomorrow. For now, stay away from those two structures until tomorrow when I release the fix. Sorry about that

**Comment by The-Bernician-Lamb** [comment]
Don't worry about it man, these things happen.

**Comment by TelepathicGrunt** [comment]
Dont worry?! The sky is falling! Cities on fire! And shark tornados are everywhere! 

jk lol. The patch is now out and approved on curseforge. Thank you for reporting this!

**Comment by TelepathicGrunt** [comment]
Oh uh, i missed another clientside code being called. v3.1.3 is out and should fix all serverside crashes for good

**Comment by The-Bernician-Lamb** [comment]
Well, Thanks for catching that because I haven't had a chance to test it yet!
