### ISSUE TITLE
Game fails to start with Repurposed Structures 3.1.1

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [TelepathicGrunt/RepurposedStructures#131]
Repurposed Structures Version: 3.1.1
Forge Version: 36.2.2
Minecraft Version: 1.16.5
Latest Log: https://gist.github.com/NJL5390/459e532b98f71beed88785beb5ace0cd

Hi,

It's me again. When I use the latest version of Repurposed Structures my game just freezes on startup and the logs seem to indicate an error with mixins. Only started happening after using the latest update to Repurposed Structures.

EDIT: Definitely an issue with Repurposed Structures, I was able to reproduce it with only Repurposed Structures.

**Comment by TelepathicGrunt** [comment]
yeah i screwd up the dolphin mixin. there's talk in my discord about it and currently fixing it lol

**Comment by TelepathicGrunt** [comment]
fix is released in v3.1.2. I had someone test it in prod so it shouldnt crash now
