### ISSUE TITLE
Mixin (?) crash while generating a structure in the end. 

### ISSUE THREAD

**Issue by AmphyEX** [TelepathicGrunt/RepurposedStructures#132]
Crashlog: https://pastebin.com/d0X7NaU8
Modlist: https://pastebin.com/jrM3c3r3

Crash while generating structure in the end. Not sure what's exactly causing it. Maybe a mixin bug? 
Structure was generated on Repurposed Structures v3.0.1 (1.16.5 MC), tried updating to Repurposed Structures v3.1.2 (1.16.5 MC) with no fix.

**Comment by Veynam** [comment]
Hello, I'm facing the exact same issue.

Crashlog: https://pastebin.com/FmVibA5F
My modlist should be in the crashlog.

**Comment by TelepathicGrunt** [comment]
After I fixed the last serverside crash, What i didnt know was the next code after it was also calling clientsided code.... aaaaa


v3.1.3 is now out and I ran it on a server to double make sure the end structures wont crash server. Sorry about that. I'm losing my mind lol
