### ISSUE TITLE
Memory leak in biome cache

### ISSUE THREAD

**Issue by BlueAmulet** [TelepathicGrunt/RepurposedStructures#138]
https://github.com/TelepathicGrunt/RepurposedStructures/blob/617334c8753085f6c2e23f725f568ddc96e99304/src/main/java/com/telepathicgrunt/repurposedstructures/world/processors/BiomeSurfaceProcessor.java#L25

This cache holds WorldGenRegion -> map(positions -> biomes), however it keeps the region objects alive in memory and over time this region -> map fills up with tons of entries and memory usage grows. I changed this to a WeakHashMap and the number of entries stayed pretty low and memory usage didn't go up after each new world.

**Comment by TelepathicGrunt** [comment]
Thank you! I'll put this in next update. How did you find the leak and narrow it down to that code?

**Comment by TelepathicGrunt** [comment]
Now I'm super curious. How many worlds saves are you even creating in single player? I had to make 20 worlds back-to-back to even notice any memory increase lol
![image](https://user-images.githubusercontent.com/40846040/132094522-a221a81a-4d3f-4f14-9a20-90bdf2a7443e.png)

**Comment by BlueAmulet** [comment]
I've actually been testing out a modpack and have been noticing over time memory fills up to the point it's doing full GC every second. In the resulting heap dumps the MINI_BIOMEPOS_CACHE object usually stood out with high amounts of memory consumption.

But yeah I also had to create several worlds back to back. I also put some debugging messages in the computeIfAbsent function that shows how many entries were in the cache every time it added a new one, since sometimes making a new world doesn't immediately trigger adding stuff to the cache.

**Comment by TelepathicGrunt** [comment]
The processor only runs and adds the world to the cache if the grassy igloo generates. New version of RS is now released so updating should fix it

**Comment by TelepathicGrunt** [comment]
To be clear after some digging, the processor was storing the worldgenregion which while it is a world, it's not the single world itself. It's a temporary restricted world used for worldgen which meant as you explored and generated more grassy igloos, that cache kept growing. The WeakHashmap was indeed the solution so it throws out the WorldGenRegion when it is finished with worldgen
![image](https://user-images.githubusercontent.com/40846040/132103579-5239808d-fe61-4842-a720-3d9cf31fb9fd.png)
