### ISSUE TITLE
Disable Villages Spawning

### ISSUE THREAD

**Issue by MrEcko19** [TelepathicGrunt/RepurposedStructures#139]
Hi,

Maybe I'm wrong but I thought that you cant disable villages from spawning with this mod.
Changing all values to 1001 in villages config should be no generation isn't it? If I'm correct then something is wrong because I can still find vanilla villages while no other mod is generating them

**Comment by TelepathicGrunt** [comment]
Vanilla villages? This mod does not touch vanilla villages at all. The config is only for disabling repurposed structures villages. To disable vanilla villages, there may be another mod that does that or you can try using a datapack like this one. This replaces the vanilla villages with a mineshaft that has the probability of spawning set to 0. Just make sure you do not use /locate command or anything that searches specifically for villages as it might hang forever with that datapack.
[no_vanilla_village_datapack.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/7110262/no_vanilla_village_datapack.zip)
