### ISSUE TITLE
Bountiful does not add to RS villages. 

### ISSUE THREAD

**Issue by TelepathicGrunt** [TelepathicGrunt/RepurposedStructures#142]
~~blays waystones now adds to RS villages again~~

**Comment by TelepathicGrunt** [comment]
![image](https://user-images.githubusercontent.com/40846040/134169729-d5ade5b9-4deb-488f-b385-aee81b26427b.png)

**Comment by snaiperskaya** [comment]
Hi, I have the latest versions of Waystones, Bountiful, and Repurposed Structures and neither waystones nor bountiful boards are generating in villages. On my server, it's throwing this error for the waystone:

![image](https://user-images.githubusercontent.com/4693814/144730939-abeb4c46-c00b-4e35-8fe5-ad726761c411.png)

**Comment by TelepathicGrunt** [comment]
@snaiperskaya Well, bountiful does not have support for 1.16 rs so it won’t appear at all. Which is the reason for this bug report.

 As for waystones, the mod compat is on their side actually so you’ll have to poke them about why the waystones aren’t spawning. Might be that the path they used for their Waystone is in a different nbt path or you have waystones in villages turned off in your config

**Comment by snaiperskaya** [comment]
Thank you! I added a note to an open issue they have that matches what I'm seeing. I have the option for village generating on and even have the additional option to force generation on, so realistically I should be seeing them in nearly every village and yet I haven't found any.

Here is the thread I added the details to for reference: https://github.com/ModdingForBlockheads/Waystones/issues/472

**Comment by TelepathicGrunt** [comment]
I made a RS-Bountiful compat datapack for fabric bountiful in 1.18. Once the Forge version updates to 1.18, I'll make a forge version of the datapack (Well, actually the fabric datapack most likely will work for the 1.18 forge version anyway)
https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-bountiful-datapack-compat
