### ISSUE TITLE
Canal v2.2 and older crashes Repurposed Structures. (Update to 2.3 or higher)

### ISSUE THREAD

**Issue by brisingraerowing** [TelepathicGrunt/RepurposedStructures#150]
```text
Repurposed Structures: Crash is about to occur because an entry in a datapack does not exist in a registry or failed to resolve an entry.
 Entry failed to be resolved: ResourceKey[minecraft:root / minecraft:worldgen/processor_list]
 Registry being used: "repurposed_structures:village/oak/path_randomizer"
```

Not sure what this means.

**Comment by TelepathicGrunt** [comment]
What version of RS are you using? Can you post the full latest.log file after you get the crash with Blame mod also on? That will greatly help me narrow down the cause of the issue

Blame mod: https://www.curseforge.com/minecraft/mc-mods/blame

**Comment by brisingraerowing** [comment]
I'll get the blame log in a moment, though there's a ton of errors like the following in the log:

```text
Error loading registry data: Not a json array: {"processors":[{"rules":[{"output_state":{"Name":"minecraft:birch_planks"},"input_predicate":{"block":"minecraft:grass_path","predicate_type":"minecraft:block_match"},"location_predicate":{"block":"minecraft:water","predicate_type":"minecraft:block_match"}},{"output_state":{"Properties":{"snowy":"false"},"Name":"minecraft:grass_block"},"input_predicate":{"block":"minecraft:grass_path","probability":0.1,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"level":"0"},"Name":"minecraft:water"},"input_predicate":{"block":"minecraft:grass_block","predicate_type":"minecraft:block_match"},"location_predicate":{"block":"minecraft:water","predicate_type":"minecraft:block_match"}},{"output_state":{"Properties":{"level":"0"},"Name":"minecraft:water"},"input_predicate":{"block":"minecraft:dirt","predicate_type":"minecraft:block_match"},"location_predicate":{"block":"minecraft:water","predicate_type":"minecraft:block_match"}},{"output_state":{"Properties":{"snowy":"false"},"Name":"minecraft:grass_block"},"input_predicate":{"block":"minecraft:dirt","predicate_type":"minecraft:block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}}],"processor_type":"minecraft:rule"}],"forge:registry_name":"repurposed_structures:village/birch/path_randomizer"}
```

**Comment by TelepathicGrunt** [comment]
Yeah what I believe is happening is a mod might be unsafely injecting a new property into Oak Planks, Water, or Grass Block which causes the processor json file to blow up. Minecraft’s worldgen system is a bit fragile where it requires every single property of a block to be specified in that processor json file. So when a mod adds properties the wrong way, it blows up my mod and other worldgen datapacks as well. It has happened a few times before. 

I guess the best way forward for me is to get a copy or link to your modpack so I can download all your mods and start manually testing to find which mod is adding the property that is blowing up my mod. It’ll take me a bit of time to do that though as it’s trial and error.

**Comment by brisingraerowing** [comment]
[Log with blame](https://gist.github.com/BrisingrAerowing/8548ef540b633ccdf7144911fd1692fe)

**Comment by brisingraerowing** [comment]
This pack is similar to another one I've built , so I'm going through mods in this one that aren't in that still working pack.

**Comment by brisingraerowing** [comment]
I think I know which mod is broken: Canals, as it just released an update to fix generation of flowing water crashing.

**Comment by TelepathicGrunt** [comment]
yeah. This is their changelog:
`Fix a bug when generating a world, if you have some mod/datapack installed that tries to generate flowing water blocks. Add Statement dependency.`

That's exactly the issue you are facing. Them switching to using the Statement Library would fix it and prevent minecraft from blowing up when it reads the water block in processor files. Update Canals and let me know if that fixes the crash!

**Comment by brisingraerowing** [comment]
It does!
