### ISSUE TITLE
RS + Subterrean Wilderness compat

### ISSUE THREAD

**Issue by Krampus69** [TelepathicGrunt/RepurposedStructures#159]
Hello :wave:
Subterrean Wilderness floods some RS structures like mineshafts in particular

![2021-12-01_17 40 59](https://user-images.githubusercontent.com/81943963/144275917-8af325c6-9213-46a7-9d0f-3c3987296213.png)

![2021-12-01_17 45 44](https://user-images.githubusercontent.com/81943963/144276516-5f66f234-3bf5-4072-b982-20fd4b9a78d5.png)

Makes it pretty hard to navigate in. I don't know if this is more on Subwild side, or even if this is fixable but I wanted to show you since you seem to be a pretty resourceful modder
Cheers

EDIT : I'm using repurposed_structures_forge-3.2.5+1.16.5 / subwild-1.3.1
On Minecraft 1.16.5
Forge 36.2.9
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/7635678/latest.log)

**Comment by TelepathicGrunt** [comment]
Yeah this isn’t something I can fix on my end. My structures generated first and then subterranean’s features detected the structure’s open space and filled it with a ton of stuff. You can ask them to see if they can add a setting to not place features within the bounds of structures somehow. They could try and move the features to a generation stage before underground structures as a workaround.
