### ISSUE TITLE
ERROR and WARN spam in server console

### ISSUE THREAD

**Issue by Mangraz** [TelepathicGrunt/RepurposedStructures#161]
On 1.18, the server is getting spammed with errors like "[14:38:06] [Server thread/ERROR]: Unknown structure start: repurposed_structures:mansion_birch" and warns like "[14:44:53] [Server thread/WARN]: Found reference to unknown structure 'repurposed_structures:mineshaft_nether' in chunk [33, -6], discarding".  Log attached for reference
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/7693141/latest.log)
.

**Comment by TelepathicGrunt** [comment]
Did you remove repurposed structures off of the server? Looks like it isn’t running if the game cannot resolve the structure starts

**Comment by Mangraz** [comment]
Something like that was indeed the issue. The server did not load fabric or any mods whatsoever and I didn't even notice until much later. Sorry for that.
