### ISSUE TITLE
Crash on Tick: NoSuchElementException: minecraft:this_entity

### ISSUE THREAD

**Issue by Sarund9** [TelepathicGrunt/RepurposedStructures#170]
Game Crashed while running around a new world, generating terrain

[Crash Report](https://pastebin.com/NRmYWtDB)

It seems this is trying to get an element with the ID "minecraft:this_entity"
When generating a LootTable

**Comment by TelepathicGrunt** [comment]
Yeah I was gonna say it was a duplicate of https://github.com/TelepathicGrunt/RepurposedStructures/issues/169 lol

Try moving that issue report but yeah, have you contacted curios yet? Seems to be caused by them
