### ISSUE TITLE
[Bug] Wandering Trader generated maps don't have coded names

### ISSUE THREAD

**Issue by RyanCR03** [TelepathicGrunt/RepurposedStructures#173]
maps generated from wandering traders with repurposed structures don't have names
![image](https://user-images.githubusercontent.com/32957560/148464533-b835f41f-5a16-4232-9696-9d1bc204c1cf.png)

**Comment by TelepathicGrunt** [comment]
I dont add mushroom village maps to wandering trader maps. Only underground bastion maps to wandering trader.
https://github.com/TelepathicGrunt/RepurposedStructures/blob/latest-released/src/main/java/com/telepathicgrunt/repurposedstructures/misc/MobMapTrades.java

You got another mod or modpack that is adding the maps to wandering traders but is not making a new entry for them in the lang files like this:
https://github.com/TelepathicGrunt/RepurposedStructures/blob/05ab08617878cca2b1a9de42f0decdf8f76088f2/src/main/resources/assets/repurposed_structures/lang/en_us.json#L39

Whoever is adding the map should consider trying to add lang entries for structures that typically do not have structure maps. Or you can make a small resourcepack to put on that adds the translation yourself. I don't think I want to work to maintain lang entries for all my structures that dont have a map by default

**Comment by RyanCR03** [comment]
idk what mod would be doing this and also it only seems to happen with mushroom villages

**Comment by TelepathicGrunt** [comment]
I know i seen some sort of mod that added any structure map to wandering trader's trades. If you're playing on a pre-made modpack, the modpack makers may had added to the trades themselves by using kubejs or crafttweaker 

I may end up just end up adding translations for all my structures in cse another mod or datapack makes a map to them. It'll be low priority so idk when next RS update will be with it in

**Comment by TelepathicGrunt** [comment]
are you by chance using the fabric version of repurposed structures but made the report this forge version? Cause if so, I found out that the fabric version was adding mushroom village maps to wandering traders but I forgot to do that on the forge version oops.

**Comment by TelepathicGrunt** [comment]
fixed in newest update for RS just released. All structures have translations in case anyone makes a custom explorer map to any of them
