### ISSUE TITLE
Cant run minecraft after update mod

### ISSUE THREAD

**Issue by InfernumYT** [TelepathicGrunt/RepurposedStructures#177]
Cant run minecraft when i update that mod from 4.1.0 to 4.2.0 (i using forge 1.18.1-39.0.14, and some other mods)

**Comment by TelepathicGrunt** [comment]
Do you have a latest.log file for me to see? Without log, I can’t do much

**Comment by Inonedn** [comment]
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/7885729/latest.log)

**Comment by InfernumYT** [comment]
[CrystalLauncherGameLog.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/7885726/CrystalLauncherGameLog.txt)

**Comment by InfernumYT** [comment]
[CrystalLauncherGameLog.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/7885745/CrystalLauncherGameLog.txt)

**Comment by TelepathicGrunt** [comment]
This mixin is dying but I got no clue why right now as I literally did not touch it at all in this update
https://github.com/TelepathicGrunt/RepurposedStructures/blob/e4935fe0e42d00d400d0b712b13f7673c9b639d3/src/main/java/com/telepathicgrunt/repurposedstructures/mixin/structures/StructureFeatureAccessor.java#L15

fun time

**Comment by InfernumYT** [comment]
[CrystalLauncherGameLog_WithoutOtherMods.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/7885829/CrystalLauncherGameLog_WithoutOtherMods.txt)
maybe it will help, thats log from new modpack(only forge and that mod)

**Comment by TelepathicGrunt** [comment]
The issue is my mod wasn't building the refmap for the mixins as I did the wrong change to my build.gradle file. 4.2.1 is out and should fix it. I'll keep this issue report up for an hour or two so people know to update

**Comment by TelepathicGrunt** [comment]
actually update to 4.2.2 as i forgot to remove debug code that wouldve crashed if better strongholds is on. I pray that's the last crash in my mod..........
