### ISSUE TITLE
1.16.1 - endless stronghold generated in mining dimension

### ISSUE THREAD

**Issue by bessiq** [TelepathicGrunt/RepurposedStructures#18]
Forge: 32.0.106
repurposed_structures-1.16.1-2.0.1.jar

Hi there! Thanks for bringing this mod to Forge 1.16. It's one of my favorites!

So, I don't think Repurposed Structures is technically doing anything wrong, so maybe this will be more of a feature request? Anyway, I have Advanced Mining Dimension installed, and if I enable the Stonebrick strongholds for modded biomes, it generates a seemingly endless stronghold in that dimension from bedrock to about y-45. The dimension is one single biome named "mining_dimension:mining_biome", tagged as PLAINS. The dimension name is "mining_dimension:mining_dimension".

Would it be possible to have a dimension or biome blacklist? I love seeing the structures in modded biomes, but for now I've disabled this stronghold from spawning in them. (Apparently this dimension is valid for grassy igloos, too. Maybe I should check the bedrock roof lol.)

Anyway, it's not a huge deal, but thought I'd ask. Thanks!

**Comment by bessiq** [comment]
RE: the igloos

![2020-08-04](https://user-images.githubusercontent.com/7315505/89364561-b6e82500-d6a0-11ea-82d0-031fc3d11195.png)
![2020-08-04 (1)](https://user-images.githubusercontent.com/7315505/89364562-b780bb80-d6a0-11ea-89b4-ae1f1aec44cc.png)

It's kind of beautiful in a way. lol

**Comment by TelepathicGrunt** [comment]
Hmm I didnt do the settings stuff correctly per dimension. Due to how dimensions work, I may or may not be able to make blacklists. The code for vanilla 1.16.1 structure spacing settings in dimensions is cursed lmao

**Comment by TelepathicGrunt** [comment]
Holy smokes. Took me a bit but I found the issue. Mining Dimension opted to make their dimension by code instead of json. In doing so, they passed an empty map of structure spacing configs instead of using the already made list of structure spacing configs in the class. And so, all structures that is added to their dimension's biome will spawn every single chunk because that's the default behavior minecraft goes for if it cant find a config for the the structure........

I'll open an issue report with them. Other devs that reads this, please make your dimension by json. I'm pretty sure Minecraft will handle these kinds of stuff for you! 
![image](https://user-images.githubusercontent.com/40846040/89470301-7abccf00-d749-11ea-9397-7bce80bf47c3.png)

**Comment by TelepathicGrunt** [comment]
Issue report now made. Hopefully they can fix this swiftly on their end!

<https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension/issues/16>

As for config to blacklist dimensions... uhhhhhhhhhhhhhhhhhhhhhhhhhhh
Yeah dimension stuff is super cursed lmao. I'll poke for a bit and see what I can do.

**Comment by bessiq** [comment]
Wow, thanks for digging into it. I guess this would also explain why the dimension was completely flooded above a certain Y level and filled with infinite meteors when I tested AE2 earlier.

Dungeon Crawl and Quark's big dungeons generate in this dimension also, but not endlessly. Still somewhat common though - especially Dungeon Crawl - it also generates its tower spire up to the roof, similar to the igloo ladders.

Don't sweat the blacklist if it's annoying. Would blacklisting by biome be any easier? The dimension does have its own unique biome name, fwiw. I wish I could figure out a way to remove the PLAINS tag from it.

Anyway, I tend to find bugs like this amusing, so no worries. Thanks again.

**Comment by TelepathicGrunt** [comment]
Biome blacklist added in v2.0.2! Should help against these kinds of incompatibilities but it won't help against modded dimensions that aren't setup right and uses vanilla biomes. 
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures/files/3024658
