### ISSUE TITLE
[1.16] Giant boulders config

### ISSUE THREAD

**Issue by HenryMaxler** [TelepathicGrunt/RepurposedStructures#186]
Hello, I was thinking of updating the mod to the newest version, but I was unable to find a config for

```
["Mod-wide Impacting Options"."Feature Options"]
		["Mod-wide Impacting Options"."Feature Options".Misc]
# Adds giant boulders to modded Giant Tree Taiga (or Redwood) biomes.
			addGiantBouldersModdedBiomes = true
```

Were the boulders removed?  I liked them, so I was wondering if they were removed, is there any issue with using the old version instead of updating?  The version I was using before was 1.16.5-2.5.0.

**Comment by TelepathicGrunt** [comment]
I am no longer supporting 1.16 anymore so that version will not be receiving anymore updates sorry. I removed the boulders because they aren’t really structures and doesn’t fit within repurposed structures’s scope. Another mod that revamps biomes would be a much better fit for those boulders.
