### ISSUE TITLE
"Errors in currently selected datapack" when attempting to load a world in Forge 1.18.2

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [TelepathicGrunt/RepurposedStructures#187]
Repurposed Structures Version: 5.0.0
Feature NBT Deadlock Begone version: 2.0.0
Forge Version: 40.0.3
Latest Log: https://gist.github.com/NJL5390/053299f79079f06c0ec523f6c4b8c95b

Hi,
When attempting to test the 1.18.2 version of this mod on forge I found that I can start up the game just fine but when I try and load into a world I get this screen:
![2022-03-04](https://user-images.githubusercontent.com/64381954/156783566-9efa5cba-0e30-4564-8d3e-74d635745d70.png)

If I remove the mod then everything works fine again. I have also tested with multiple other mods and this was the only one that produced this issue.

**Comment by TelepathicGrunt** [comment]
The mixin to increase the maximum size of weights in structure pool files is not applying. I’ll test later but I was certain it was working. Are you running with any other mods on or just RS?

**Comment by The-Bernician-Lamb** [comment]
I was using other mods when I first discovered this issue but I was able to narrow it down to Repurposed Structures and I have since been able to reproduce it with only Repurposed Structures.

**Comment by JasonKillsUs** [comment]
same here 1.18.2_40.0.2/3 only on new World creation

**Comment by TelepathicGrunt** [comment]
fixed in v5.0.1 now
