### ISSUE TITLE
[2.0.1 | 1.16.1] Jungle Fortress not generating at all.

### ISSUE THREAD

**Issue by robertfwallis** [TelepathicGrunt/RepurposedStructures#19]
![image](https://user-images.githubusercontent.com/11021224/89395135-d44eda80-d704-11ea-8ae3-461a1252246c.png)

**Comment by TelepathicGrunt** [comment]
It is generating it seems but uh, broken lmao
Gotta figure out why now 

![image](https://user-images.githubusercontent.com/40846040/89406523-4dd9cf00-d6eb-11ea-9a5d-a5f09d7519bd.png)

**Comment by TelepathicGrunt** [comment]
Biome blacklist added in v2.0.2! Should help against these kinds of incompatibilities but it won't help against modded dimensions that aren't setup right and uses vanilla biomes. 
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures/files/3024658
