### ISSUE TITLE
Bad gen on nether mineshafts

### ISSUE THREAD

**Issue by zachsai** [TelepathicGrunt/RepurposedStructures#192]
![2022-03-15_15 20 17](https://user-images.githubusercontent.com/63996164/158454941-03285ba7-38aa-4f21-b138-d5bae7e9fe4f.png)
Bad gen on nether mineshafts

**Comment by TelepathicGrunt** [comment]
Not really, looks fine to me as a neat way to find them. You can lower them in the config in 1.18.1 and below. Or lower them with a datapack in 1.18.2. If anything, I may just barely lower them so the top is still visible in lava but not open as often.
