### ISSUE TITLE
Crash on load with Forge 40.0.18

### ISSUE THREAD

**Issue by iosgoodch** [TelepathicGrunt/RepurposedStructures#193]
# Issue
With repurposed_structures_forge-5.0.3+1.18.2 installed, the game crashes on launch with Forge 40.0.18.

<img width="994" alt="Screen Shot 2022-03-16 at 10 36 03 PM" src="https://user-images.githubusercontent.com/9204465/158743966-cc286733-e3e7-4183-86c6-9875eee0ea84.png">

### How reproducible
Happens every time.

## Additional Information / Resources
Crash log:

[crash-2022-03-16_22.32.41-fml.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/8281665/crash-2022-03-16_22.32.41-fml.txt)

**Comment by TelepathicGrunt** [comment]
Fixed in v5.0.4. Forge did a breaking change and so, I had to update a part of my mod to make it work again.
