### ISSUE TITLE
Question: what's meaning of "RS" in the advancements?

### ISSUE THREAD

**Issue by 1mtwtfss1** [TelepathicGrunt/RepurposedStructures#195]
As the title says, I wnt to know the meaning of "RS".Is it a abbreviation?

**Comment by TelepathicGrunt** [comment]
RS stands for Repurposed Structures. The first letters of the words in my mod's name

**Comment by 1mtwtfss1** [comment]
OK. Thank you.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月27日(星期天) 上午8:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TelepathicGrunt/RepurposedStructures] Question: what&#39;s meaning of &quot;RS&quot; in the advancements? (Issue #195)





 
RS stands for Repurposed Structures. The first letters of the words in my mod's name
