### ISSUE TITLE
Structures spawning in end in BYG biomes

### ISSUE THREAD

**Issue by zachsai** [TelepathicGrunt/RepurposedStructures#198]
1.18,2
![image](https://user-images.githubusercontent.com/63996164/163698590-999bdcbc-4217-4fbd-9cfa-88bcc4c02b99.png)
![image](https://user-images.githubusercontent.com/63996164/163698592-c35ccfa8-67fc-473d-95fc-194ea2d669a9.png)
![image](https://user-images.githubusercontent.com/63996164/163698596-578dab79-f630-4e76-a1fa-2ff000255831.png)

**Comment by TelepathicGrunt** [comment]
Those nether structures from RS can only spawn in nether tagged biomes. To be specific, following the Nether City, It uses this tag `#repurposed_structures:has_structure/cities/nether` for biomes to spawn in:
https://github.com/TelepathicGrunt/RepurposedStructures/blob/4bb6777776487330dcbd054447915afeb1a89a68/src/main/resources/data/repurposed_structures/worldgen/configured_structure_feature/city_nether.json#L18

And that tag is pulling values from `#repurposed_structures:collections/nether`:
https://github.com/TelepathicGrunt/RepurposedStructures/blob/4bb6777776487330dcbd054447915afeb1a89a68/src/main/resources/data/repurposed_structures/tags/worldgen/biome/has_structure/cities/nether.json#L4

And that tag looks like this. See how it is pulling biomes from nether tags?
https://github.com/TelepathicGrunt/RepurposedStructures/blob/latest-released/src/main/resources/data/repurposed_structures/tags/worldgen/biome/collections/nether.json

This does not look like an RS issue. Rather, a datapack or another mod is inappropriately tagging their end biomes in the nether biome tags. Or the nether biomes are actually spawning in the end (use F3 to see exactly what biome those structures are spawning in to know what biomes are for some reason nether tagged). Once you check what that biome is, you can let me know so i can tell the owner to recheck their biome tags and tag their biomes properly.

**Comment by TelepathicGrunt** [comment]
Problematic tag found. This is in byg and is putting the wrong biomes into c:in_nether tag
https://github.com/AOCAWOL/BYG/blob/1.18.X/Common/src/main/resources/data/c/tags/worldgen/biome/in_nether.json

You can make a small datapack to fix this as a workaround until they update.

**Comment by TelepathicGrunt** [comment]
Latest byg is said to have fixed this issue. Please give it a try and let me know if the issue persists.

**Comment by GoatRammaHamma70** [comment]
it is fixed
