### ISSUE TITLE
Advancement titles and descriptions not displaying properly

### ISSUE THREAD

**Issue by NJL5390** [TelepathicGrunt/RepurposedStructures#20]
Minecraft Version: 1.16.1
Forge version: 32.0.106
Repurposed Structures version: 2.0.3

Since Updating to version 2.0.2 earlier today the advancement descriptions and titles of the mod have been broken and not displaying properly. This only started occurring in version 2.0.2 and was not occurring prior to this.

Some screenshots to show what I mean:
![2020-08-06_20 45 53](https://user-images.githubusercontent.com/64381954/89577104-19b7f880-d828-11ea-98d0-0cec5cd7b01f.png)
![2020-08-06_17 07 44](https://user-images.githubusercontent.com/64381954/89577228-44a24c80-d828-11ea-998f-1f5846da75fe.png)

**Comment by TelepathicGrunt** [comment]
Ah yes. gitignore ignoring my asset folder again lmao. 
Give me a moment and I'll fix this!

**Comment by TelepathicGrunt** [comment]
Fixed in 2.0.4!
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures/files/3025634

**Comment by NJL5390** [comment]
Thanks for the quick fix! Awesome mod btw, I and many others appreciate the work that you put into your mods!
