### ISSUE TITLE
[1.16.5 Forge] Failed to create valid structure

### ISSUE THREAD

**Issue by ghost** [TelepathicGrunt/RepurposedStructures#200]
latest.log 
https://pastebin.ubuntu.com/p/rhzj5td39M/

**Comment by TelepathicGrunt** [comment]
I stopped supporting 1.16.5 a long time ago. The only two things I can suggest is maybe try deleting the repurposed structures mineshaft config folder. That way it gets remade with the values that fits the mineshaft. The only other thing is check the `Blame Report Worldgen Import` entries in the log and see if removing the offending mods fixes the mineshafts
