### ISSUE TITLE
Game crashes when creating new world.

### ISSUE THREAD

**Issue by xaviergking** [TelepathicGrunt/RepurposedStructures#213]
My game will work all the way until I click "create new world" then it crashes. I've tried it without this mod and it works every time. I've included my crash report and latest log. It might be conflicting with another mod but I have no idea which, any ideas? Either that or it created a separate issue, I don't know.

[crash-2022-06-16_13.02.01-client.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/8920976/crash-2022-06-16_13.02.01-client.txt)

[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/8920979/latest.log)

**Comment by TelepathicGrunt** [comment]
Remove RS until I fix this. Issue with the rs datapack json reading system which rs datapacks and waystone mods uses for compat with rs

**Comment by TelepathicGrunt** [comment]
should be fixed now in v6.0.2. Give it a try. I just released it.
