### ISSUE TITLE
End pyramids blow up automatically [Lootr - edit their config to fix]

### ISSUE THREAD

**Issue by Claes-Arno** [TelepathicGrunt/RepurposedStructures#215]
Whenever an end pyramid loads in, the tnt in the chest room goes off automatically.

**Comment by Claes-Arno** [comment]
This happens in v6.0.9

**Comment by TelepathicGrunt** [comment]
Just tested. It is not blowing up for me at creation. 
![image](https://user-images.githubusercontent.com/40846040/176790833-f16d1d6f-424d-495a-aeab-4ccee9e17820.png)

In order for the trap to be set off, the chest has to be empty of all items to make the comparator turn on the redstone torch. What other mods do you have on? Any that modifies the chest loot table or replaces the chests or changes the redstone mechanics?

**Comment by TelepathicGrunt** [comment]
Looks like having lootr on will cause the comparator to fail and set off the trap. I'll ask lootr to see if they have a way to turn off their lootr chests for a specific loot table or change how they feed power to comparators

**Comment by Claes-Arno** [comment]
I am indeed using lootr. I am going to try adding this structure to the lootr config so that the chest won't be converted into lootr chests.

**Comment by Claes-Arno** [comment]
Changing the config doesn't work it seems. I'd have to disable lootr in the whole end dimension, which i don't really want to do. I don't see another way around though...

**Comment by TelepathicGrunt** [comment]
What config did you edit and what did you put into the config?

**Comment by Claes-Arno** [comment]
I tried the dimension-blacklist config in the lootr-common.toml file. I put "minecraft:the_end" in the blacklist, but I only want to blacklist the end pyramid structure from your mod. I also tried to change the loot table with KubeJS, but that doesn't seem to work because lootr generates instanced loot only when you interact with the chest (I think), therefore the comparator reads it as 'empty' and generates a redstone signal before you even get close to it.

**Comment by TelepathicGrunt** [comment]
Lootr specifically made their chests have no comparator output at all because the chest loot is per player and the comparator is not a player and thus, has no way of knowing what loot to check.

Is there any other config in lootr beside the dimension one?

**Comment by Claes-Arno** [comment]
Oh ok I didn't know it worked like that. Here's a screen of the whole config file:
<img width="1106" alt="Screenshot 2022-07-01 152116" src="https://user-images.githubusercontent.com/91273692/176903034-72763cd4-05be-466f-b9c4-a17be28507c1.png">

**Comment by TelepathicGrunt** [comment]
loot_table_blacklist is what you want. 
`loot_table_blacklist = ["repurposed_structures:chests/pyramids/end"]`
Will work and not convert the comparator chests in end pyramids. 

![image](https://user-images.githubusercontent.com/40846040/176947979-188bde79-f5da-41b6-ac62-05070e72bf3f.png)

**Comment by Claes-Arno** [comment]
I tried that before but forgot the chests part. It works now! Thanks a lot!

**Comment by TelepathicGrunt** [comment]
Lootr just recently updated so their chests always puts out a comparator value of 1. So Lootr chests should not make RS end pyramids explode anymore.
