### ISSUE TITLE
Crash on newer Forge versions [FIXED: update to v6.1.3 RS or newer]

### ISSUE THREAD

**Issue by Lokos2** [TelepathicGrunt/RepurposedStructures#217]
I'm not the most experienced, so I can't tell what the specific details are, but seems that the mod is not compatible with the latest up-to-date version of Forge, it was working fine yesterday before the update.

**Error message:**
https://mclo.gs/xnAWLbk

Mods used:
Aquaculture-1.19-2.4.0
architectury-5.7.27-forge
balm-4.2.0
betteranimalsplus-1.19-11.0.6-forge
BiomesOPlenty-1.19-17.0.0.136
corpse-1.19-1.0.4
Enhanced-Farming-1.19-1.4.3
ExtraArmor+1.19-1.15.1
goblintraders-1.7.2-1.19
morevillagers-forge-1.19-4.0.2
repurposed_structures_forge-6.1.1+1.19
journeymap-1.19-5.8.5rc2-forge
TerraBlender-forge-1.19-2.0.0.112
waystones-forge-1.19-11.0.0

**Comment by TelepathicGrunt** [comment]
it's Forge 41.0.79 that broke it
![image](https://user-images.githubusercontent.com/40846040/178121863-30ac6de7-121f-4807-bbd1-6671f2d404fa.png)

**Comment by TelepathicGrunt** [comment]
fixed in v6.1.2 RS. It requires v41.0.85 Forge or newer to work now. Thank you for reporting this!
