### ISSUE TITLE
repurposed structures failed to load correctly

### ISSUE THREAD

**Issue by krjencik** [TelepathicGrunt/RepurposedStructures#218]
forge 41.0.98
version of mod: 6.1.2

**Comment by TelepathicGrunt** [comment]
Do you have any logs or screen of the issue?

**Comment by TelepathicGrunt** [comment]
Forge renamed a field. Fixing

**Comment by TelepathicGrunt** [comment]
linking this to keep info together of these forge breaking changes
https://github.com/TelepathicGrunt/RepurposedStructures/issues/217

**Comment by TelepathicGrunt** [comment]
Fixed in v6.1.3
