### ISSUE TITLE
crash at chunk loading

### ISSUE THREAD

**Issue by jackg2527** [TelepathicGrunt/RepurposedStructures#22]
Hi, thanks for the awesome mod! I think I was about to see one of the structures but game crashed. logs attached. Thanks in advance for your help.

[crash-2020-09-05_00.38.19-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/5177724/crash-2020-09-05_00.38.19-server.txt)

[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/5177725/latest.log)

**Comment by TelepathicGrunt** [comment]
Ok the good news is I know exactly what the issue is. Another mod called the DynamicRegistries class in code way too early which killed the registries. That's why you see a million errors in that log from all kinds of mods.

What mods do you have on? (If you have The Bumblezone, please update it to v2.0.3 as it was causing this issue before in older versions)

**Comment by jackg2527** [comment]
Thanks for the quick reply. 

Mod list is below. Did lots of swapping mods and I _think_ the source was a pre-alpha version of Ars Magica 3 aka I had added a few hours earlier. I got the same crash after removing it, but when I used a backup of the same world (never saw AM3) I was able to generate mountain village. Maybe the backup worked b/c the chunk got corrupted during the crash?

Anyway sorry to waste your time. I probably shouldn't post issues in the middle of the night! also attached pics of the RS village. Cheers!

		forge-1.16.2-33.0.37-client.jar Minecraft {minecraft@1.16.2 DONE}
		mcw-bridges-1.0.4-mc1.16.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		useful_backpacks-1.16.2-1.11.4.80.jar Useful Backpacks {usefulbackpacks@1.11.4.80 DONE}
		repurposed_structures-1.16.2-2.1.2.jar Repurposed Structures {repurposed_structures@1.16.2-2.1.2 DONE}
		AmbientSounds_v3.0.21_mc1.16.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		NetherPortalFix_1.16.2-7.1.0.jar NetherPortalFix {netherportalfix@7.1.0 DONE}
		manaandartifice-1.0.6-pre9.jar Mana and Artifice {mana-and-artifice@1.0.6-pre9 DONE}
		CreativeCore_v2.0.7_mc1.16.2.jar CreativeCore {creativecore@2.0.0 DONE}
		RingOfGrowth-1.16.2-1.2.1.jar Ring of Growth {ring_of_growth@1.2.1 DONE}
		mcw-trapdors-1.0.0fix-mc1.16.2.jar Macaw's Trapdoors {mcwtrpdoors@1.0.0 DONE}
		jei-1.16.2-7.3.2.25.jar Just Enough Items {jei@7.3.2.25 DONE}
		movingelevators-1.2.20-mc1.16.2.jar Moving Elevators {movingelevators@1.2.20 DONE}
		gates-1.6.2.jar Gates {gates@1.6.2 DONE}
		mcw-windows-1.0.2-mc1.16.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		Patchouli-1.16-42.jar Patchouli {patchouli@1.16-42 DONE}
		BetterCaves-1.16.2-1.0.1.jar YUNG's Better Caves {bettercaves@1.16.2-1.0.1 DONE}
		RingOfRepair-1.16.2-1.2.2.jar Ring of Repair {ring_of_repair@1.2.2 DONE}
		RingOfMiner-1.16.2-1.2.1.jar Ring of Miner {ring_of_miner@1.2.1 DONE}
		Placebo-1.16.2-4.2.0.jar Placebo {placebo@4.2.0 DONE}
		fakeblocks-1.16.2-1.0.2.jar Fake Blocks {fakeblocks@1.16.2-1.0.2 DONE}
		enderchests-1.16-1.7.1.jar EnderChests {enderchests@1.7.1 DONE}
		WitherSkeletonTweaks-1.16.2-5.1.0.jar Wither Skeleton Tweaks {wstweaks@5.1.0 DONE}
		worldedit-forge-mc1.16.2-7.2.0-beta-04.jar WorldEdit {worldedit@7.2.0-beta-04+98f71a3 DONE}
		u_team_core-1.16.2-3.1.8.179.jar U Team Core {uteamcore@3.1.8.179 DONE}
		increasemobcap-forge-1.16.2-1.0.1.jar Increase Mob Cap {increasemobcap@1.0.1 DONE}
		FastFurnace-1.16.2-4.2.0.jar FastFurnace {fastfurnace@4.2.0 DONE}
		mcws-roofs-1.16.2-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
		Apotheosis-1.16.2-4.2.0.jar Apotheosis {apotheosis@4.2.0 DONE}
		mcw-doors-1.0.0-mc1.16.2.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		grapple_hooks-1.2.0-29.jar Grapple Hooks {grapple_hooks@1.2.0-29 DONE}
		AI-Improvements-1.16.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		Hwyla-forge-1.10.11-B78_1.16.2.jar Waila {waila@1.10.11-B78_1.16.2 DONE}
		ItemPhysic_v1.4.6_mc1.16.2.jar ItemPhysic {itemphysic@1.6.0 DONE}
		forgemod_VoxelMap-1.10.10_for_1.16.2.jar VoxelMap {voxelmap@1.10.10 DONE}
		forge-1.16.2-33.0.37-universal.jar Forge {forge@33.0.37 DONE}
		goprone-1.16.2-1.3.4.jar GoProne {goprone@1.16.2-1.3.4 DONE}
		shetiphiancore-1.16-3.8.1.jar ShetiPhian-Core {shetiphiancore@3.8.1 DONE}
		CleanView-1.16.2-v1.jar CleanView {cleanview@1.16.2-v1 DONE}
		SoundFilters-0.14_for_1.16.2.jar Sound Filters {soundfilters@0.14_for_1.16.2 DONE}
		infernalmobs-1.16.2.1.jar Infernal Mobs {infernalmobs@1.16.2.1 DONE}
		corpse-1.16.2-1.0.8.jar Corpse {corpse@1.16.2-1.0.8 DONE}
![2020-09-05_12 35 23](https://user-images.githubusercontent.com/23530614/92312893-2db35f00-ef7a-11ea-812b-34b4181c8de8.png)
![2020-09-05_12 36 36](https://user-images.githubusercontent.com/23530614/92312896-37d55d80-ef7a-11ea-8698-45c896d0c5df.png)

**Comment by TelepathicGrunt** [comment]
At least if it is working now, awesome! Be sure to let them know about my comment about DynamicRegistries and that they can contact me if they are stumped about fixing that.

Have fun and enjoy! :)
