### ISSUE TITLE
Crash with Create / IDAS / RS

### ISSUE THREAD

**Issue by brisingraerowing** [TelepathicGrunt/RepurposedStructures#225]
[Crash Log](https://gist.github.com/brisingraerowing/698324c36c6c3425985a77e25eed49cd)

It looks like RS generated a structure through an IDAS structure that has a Create kinetic source, breaking part of said source and bricking the world. I've also reported this to Create at Creators-of-Create/Create#3704.

**Comment by TelepathicGrunt** [comment]
Yeah that’s not an RS bug. That crash will occur with any mod or datapack spawning an structure nbt piece that replace’s create’s block. Create will need to fix their block entity so it does not try to access a null field. I’m assuming that field is the level field which is null for block entities very early in worldgen

**Comment by TelepathicGrunt** [comment]
closing as this is so old. Will reopen if someone can reproduce the error in newer mc versions
