### ISSUE TITLE
issue with datapacks on 1.16.5

### ISSUE THREAD

**Issue by ghost** [TelepathicGrunt/RepurposedStructures#227]
we are on ATM6 which has repurposed_structures_forge-3.4.7+1.16.5 
We added to the servers datapack:
Repurposed_Structures-Better_Dungeons_v2
Repurposed_Structures-Immersive_Engineering_v4
Repurposed_Structures-Ice_and_Fire_v2

The nether was a laggy and it kicked us. 

in the logs it shows a lot of: 

`[00:04:22] [Worker-Main-152/ERROR] [co.te.re.RepurposedStructures/]:
***************************************
Failed to get mob. Please check that repurposed_structures:dungeons/nether.json is correct or that no other mod is interfering with how vanilla reads data folders. Let TelepathicGrunt know about this too!`

removing the datapacks and the nether is suddenly fine.

Better dungeons : BetterDungeons-1.16.4-1.2.1
Immersive Engineering : ImmersiveEngineering-1.16.5-5.1.0-148
Ice and Fire : iceandfire-2.1.9-1.16.5

**Comment by TelepathicGrunt** [comment]
You would need to share the logs from server please. If the server stalled and timed out, then I would need a thread dump as well. Spark can give thread dumps iirc. Do the dump right when the server stalls which is when chunks stops loading and mobs are frozen, etc. This will show exactly what stalled the server and it may not even be the datapacks you listed (coincidences happens)

without the log or thread dump, there’s nothing that can be done for troubleshooting. Also, fyi, I am not supporting 1.16.5 anymore so there will be no more rs updates for that.

**Comment by ghost** [comment]
The client gets kicked but the server carries on running. Reconnecting will let you run fine for a bit.

The log file is too big to pastebin (or to post here) so I uploaded it to my google drive:
https://drive.google.com/file/d/10VpRnUOoKqzvHWyI10PIJmzxLoYB9TnE/view?usp=sharing

Np on the not supporting, I think its some interaction between the mod and the datapacks, just figured its something that should be reported.

**Comment by TelepathicGrunt** [comment]
![image](https://user-images.githubusercontent.com/40846040/187003078-fcdebe3c-124e-48ca-8db9-25abd0218a1d.png)
Seems to work fine. Check the client log to see if it has a reason for the disconnect.  Also, depending on how server is setup, a deadlock wont crash the server but clients will still disconnect if the server doesn't respond in time. (which a thread dump would be helpful for)

**Comment by TelepathicGrunt** [comment]
The `Failed to get mob.` logspam you have means RS was unable to read its json files for dungeon spawner mobs. None of the datapacks you listed touches the rs_spawner files and doesn't seem to have any worldgen datapack parse issue errors in your log file. Meaning something else is breaking RS there for the mob spawner.

**Comment by TelepathicGrunt** [comment]
It's been 10 days without a response and I am unable to reproduce issue. I'll close this now unless more info comes up and then I'll reopen

**Comment by ghost** [comment]
My apologies, I did not see your reply.
We removed the datapacks and the issue went away and the server has been fully stable. 
Reluctant to add them again and have the issue come back. 
If its not effecting anyone else then tbh its a mute issue. If i had more free time on my hands I would see if I could get more details but works pretty busy these days and my free time to game is cherished lol. 

Again sorry for not replying sooner.

EDIT, looking at the image you shared that does not seem to be the atm6 pack, so I am wondering if the issue was some mod in atm6 interacting with the datapacks badly and RS caught in the crossfire (only thing I can think of)
