### ISSUE TITLE
Extreme TPS lag on Server

### ISSUE THREAD

**Issue by AllThatJazz139** [TelepathicGrunt/RepurposedStructures#228]
2 weeks ago I created a 1.18 Forge server for me and my friends to play on. After Rigorous single player testing we started it up, However, occasionally when generating new terrain TPS drops to about 2-5 and an error in the Console appears. This lag lasts from anywhere from 5-30+ minutes. 

Based on the Console message I thought best to make an issue report here, even though I am not 100% certain this mod is the cause, It's the best lead I have at the moment. Linked below is a spark Profiler Report of the direct lag source (StructureCheck.tryLoadFromStorage) as well as the latest.log with the error first happening at 03:37:00.369. I apologize if this was not the correct place or way to post this. Thank you.

Spark: https://spark.lucko.me/bI5tDOx7r4
Latest.log: https://pastebin.com/7Qw4yvup
modlist: https://pastebin.com/TU2wiXKw

**Comment by TelepathicGrunt** [comment]
This is not an RS issue. The lag comes from a mixin into player tick to try and locate a structure nearby.

![6FFE7D2F-1FAD-4D9C-91F7-DB50FA4927F0](https://user-images.githubusercontent.com/40846040/188267353-a482e253-cb5a-425e-812f-a4004dfb9c3c.jpeg)

This mixin was determined before to be Better Desert Temple’s mixin. Go into Better Desert Temple’s config and turn off their Mining Fatigue effect to disable that specific mixin and stop the lag. 

The logspam about the empty processor list is not from RS either. That’s from Domestic Innovation not grabbing the empty processor list from the dynamic registry like they need to do instead.

**Comment by TelepathicGrunt** [comment]
Or you can try and update Better Desert Temple and see if that solves the issue as they may had fixed the problem with the mixin. https://github.com/YUNG-GANG/YUNGs-Better-Desert-Temples/issues/8

**Comment by AllThatJazz139** [comment]
Thank you so much for this! I am going to test this immediately. I apologize once again for taking up your time with an issue that wasn't your mod.

**Comment by TelepathicGrunt** [comment]
It’s fine as this isn’t easy to narrow down. I only know about it because some other users were complaining about the same problem and I helped find out that it was better pyramid’s mixin

**Comment by TelepathicGrunt** [comment]
I'm guessing that config/updating better pyramid solved the issue. I'll close this report now.
