### ISSUE TITLE
[1.19.2 Quilt] Power rail rotation fix mixin crashing 

### ISSUE THREAD

**Issue by Sunconure11** [TelepathicGrunt/RepurposedStructures#234]
https://gist.github.com/Sunconure11/4a122cd2006d43202af7a790d299490c

**Comment by Sunconure11** [comment]
This pretty much soft-locks the game.

**Comment by Sunconure11** [comment]
https://pastebin.com/ggWStu7e

**Comment by Sunconure11** [comment]
@TelepathicGrunt Might want to look at this

**Comment by TelepathicGrunt** [comment]
I get notifications for all issue reports on my repo. No need to ping me as it won't make me be able to get off of work faster lol.

**Comment by TelepathicGrunt** [comment]
Should be fixed in v6.3.1 Quilt RS that is released now. Thank you for reporting this!
