### ISSUE TITLE
Crash with Valhelsia Structures

### ISSUE THREAD

**Issue by johanplima** [TelepathicGrunt/RepurposedStructures#238]
When I turn Valhelsia Structures Off it runs perfect

**Comment by TelepathicGrunt** [comment]
Can you please provide me a latest.log file after you get the crash? The file is in the logs folder above he mods folder

**Comment by TelepathicGrunt** [comment]
Oh Valhelsia Structures is only on 1.18.2. I'm not really supporting MC versions older than 1.19.2 but even then, I gave it a test and my mod is running just fine with v0.1.0 Valhelsia Structures in 1.18.2 with latest Forge version and v5.1.14 RS.
![image](https://user-images.githubusercontent.com/40846040/198156915-bd8c8487-e728-486e-890d-2aa47d6e58f3.png)

**Comment by TelepathicGrunt** [comment]
Closing as no more info was provided over 2 weeks and I cannot reproduce the issue
