### ISSUE TITLE
Crash when entering the Nether

### ISSUE THREAD

**Issue by vitorvicente** [TelepathicGrunt/RepurposedStructures#239]
Every time I try to open the nether in Singleplayer it crashes... it doesn't even finish loading (ie I never actually see the nether). The crash log mentions an issue with Repurposed Structures when generating something in the Nether.

I have a feeling this might be my fault due to some conflict/configuration, but, since you're more familiar with the mod, I thought you might have a clearer idea. I've looked through the config and I don't think there's anything majorly wrong? But two eyes are better than one!

Minecraft Version: 1.16.5
Mod Version: 3.4.7+1.16.5.jar
Forge Version: 36.2.39

Modpack: https://www.curseforge.com/minecraft/modpacks/xcraft-ultra-modded-v2

Crash Log: https://pastebin.com/R3Ksf6HA

Current Configs are attached.
[repurposed_structures-forge.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/9883273/repurposed_structures-forge.zip)

**Comment by TelepathicGrunt** [comment]
Ugh 1.16.5. The old Mc version where other mod’s either broken worldgen json or block property manipulation can cascade and kill my mod’s start pool json which then causes the game to crash due to empty template pool.

If you share the latest.log file (not the crashlog file) after you get the crash, it’ll have more info as to what mod could be involved or at least, what json file is getting broken in your modpack

**Comment by TelepathicGrunt** [comment]
One known mod to conflict in 1.16.5 is Water Physics Overhaul
https://github.com/TelepathicGrunt/RepurposedStructures/issues/97

**Comment by vitorvicente** [comment]
https://pastebin.com/aJYcJZDQ - Latest.log file

And sorry for bugging you about an older version xD

**Comment by TelepathicGrunt** [comment]
Ok so the latest.log file just before the crash states this:

[08:27:41] [Worker-Main-12/ERROR]: MinY should always be less than MaxY or else a crash will occur or no pieces will spawn. Problematic structure is:repurposed_structures:mineshaft_crimson

i don’t see any worldge json parsing issue so next step is, can you double check the config you have for crimson mineshaft and make sure min y is less than max y?

**Comment by vitorvicente** [comment]
https://pastebin.com/R16rdf9e - Am an idiot, would be hard for the mineshaft to generate above Y 15 and below Y 14 xD I had a feeling I had miss configured something somewhere...

Thanks for the help! The nether now generates smoothly :)
