### ISSUE TITLE
Can i turn off the sideeffects of red sandtemple?

### ISSUE THREAD

**Issue by zaze06** [TelepathicGrunt/RepurposedStructures#240]
So i wonder is it possible to turn off the side effects of the red sand temple

**Comment by TelepathicGrunt** [comment]
??? I am not sure what you mean by side effect. I’m guessing you’re talking about the Badlands Pyramid but side effect? Can you please be more description of what you’re looking for?

**Comment by zaze06** [comment]
when i walk into a badlands pyramid I get mining fatigue 3, and I whunder if I can turn it off

**Comment by TelepathicGrunt** [comment]
Are you using the Repurposed Structures - Yung’s Better Pyramid compat datapack? If so, edit the datapack, go into data/betterpyramids/tags/structures/mining_fatigue.json and then delete the badlands pyramid entry from it

**Comment by zaze06** [comment]
Yung's better desert temple is the only mod I can find, no datapacks

**Comment by TelepathicGrunt** [comment]
Without the compat datapack on, then my pyramid cannot have mining fatigue. 

If the badlands pyramid looks like this, then you dont have the compat datapack and it is not my mod giving mining fatigue then: 
![image](https://user-images.githubusercontent.com/40846040/198898423-bad2a6e9-f5b5-4268-aa65-4c5e9a4905eb.png)

If the badlands pyramid looks like this, then you do have the Repurposed Structures - Yung's Better Pyramid Compat Datapack on and that is what is tagging the Badlands Pyramid to have mining fatigue until you kill yung's pharaoh Husk mob inside. You would need to find where the compat datapack is in your modpack and edit the tag to not have the badlands pyramid to remove the effect.
![image](https://user-images.githubusercontent.com/40846040/198898382-feb3ad58-c7b1-437a-a258-72558b814033.png)

![image](https://user-images.githubusercontent.com/40846040/198898454-ae9bdab5-a65e-4a99-a11b-2adfac042879.png)

**Comment by TelepathicGrunt** [comment]
I just fixed the images in my last comment. GitHub going borked

**Comment by zaze06** [comment]
I have the small pyramid. and i did find a `"betterdeserttemples:desert_temple"` in the data folder for yungs in a `applies_mining_fatigue.json` file. so removing the mod should fix it?

**Comment by TelepathicGrunt** [comment]
No. If you see a small Badlands Pyramid, then you do not have Repurposed Structures - Yung's Better Pyramid Compat Datapack. Which means my Badlands Pyramid is not tagged to have mining fatigue. Thus the mining fatigue is not from my mod.

 Have you verified that you are not near a different structure instead? If you're near yung's own desert pyramid structure, then removing his structure from the tag will remove mining fatigue from his. But if not, then a different mod is doing mining fatigue

**Comment by zaze06** [comment]
I have verified that the mining fatigue is triggered when going inside the area of the temple. and from what I know there is no other instruction near it

**Comment by TelepathicGrunt** [comment]
Please give me your entire modpack instance including the mods folder, config folder, resourcepack folder, etc. What you are describing is not possible unless there is a datapack specifically tagging my badlands pyramid to be using yung's mining fatigue stuff. 

Pic of me with both RS and Yung's better temple on but no compat datapack. Thus no mining fatigue in pyramid
![image](https://user-images.githubusercontent.com/40846040/198899503-7a7cd87b-030b-4f7f-a292-211ba2330117.png)

**Comment by zaze06** [comment]
better minecraft v9 whit additon of simple vc(but i bet its not relevant), defualt config, resorcpacks(see immage)
![image](https://user-images.githubusercontent.com/54169874/198899579-de6e65b8-a925-47e6-9bbc-e77343da5dca.png)

**Comment by zaze06** [comment]
if its relevant its the fabric version of the modpack(it probably is)

**Comment by TelepathicGrunt** [comment]
That modpack does have the compat datapack. It's in the paxi folder in the config folder
![image](https://user-images.githubusercontent.com/40846040/198899861-3f68eba3-d009-4447-9ed0-56801d8dc4a3.png)

**Comment by zaze06** [comment]
ok so, just removing that datapack fixes it? or should I just remove a thing in the datapack?

**Comment by TelepathicGrunt** [comment]
If you want RS pyramids to continue to be in the style of Yung's Better Temples, then edit that Repurposed_Structures-Better_Desert_Temples_v2 datapack by unzipping it, go to `\data\betterdeserttemples\tags\worldgen\structure\applies_mining_fatigue.json` file, and remove RS pyramids from that tag file. Save. Delete the zip version and keep the unzipped form (minecraft can read both zipped and unzipped folders)

If you do **not** want RS pyramids to be in the style of Yung's Better Temples, then just delete the datapack outright

**Comment by zaze06** [comment]
ok thanks

**Comment by zaze06** [comment]
all the tags are `repurposed_structures:pyramid_X` shuld i remove all of thos then?

**Comment by TelepathicGrunt** [comment]
make the file be

```json
{
  "replace": false,
  "value": []
}
```

to make all RS pyramids not have mining fatigue

**Comment by zaze06** [comment]
thanks

**Comment by TelepathicGrunt** [comment]
Closing as it seems we resolved the issue lol

**Comment by zaze06** [comment]
yea, and thanks for all the help even tho this wasn't your mods doing
