### ISSUE TITLE
Mod Causes lag (Possible compability issue) and also .... ads server components to single play.....

### ISSUE THREAD

**Issue by Zelioth** [TelepathicGrunt/RepurposedStructures#241]
I'll start with the information 

Minecraft 1.19.2
Forge 43.1.47
RS : 6.3.5+

Okay so I'm in the process of improving and testing my pack "Friends United" which is published on curse forge. This pack has had a mjor memory issue that I have been working on that I have narrowed down to Biome Modifiers. I'm not fully blaming Repurposed Structures for the lag issues and this is very difficult to explain but it does increase memory usage in the main menu for some odd reason and in game when generating a new world it somehow makes the client thing you're joining a server and the game begins to provide a ping based on the clients status.... I know how weird this sounds but after MAJOR TESTING meaning every mod in my pack has been removed and re-added, done in groups, one by one, etc to find the cause of lag and though I found MOST Of it RS seems to for some reason create a server environment for single player 

I want to state that YES I know single player sort of runs as a server environment already but when running a profiler with RS added to single player it shows the extra info and ping info which is not correct either 

This is without RS 
https://spark.lucko.me/nOUQOZ0ugq

This is WITH RS
https://spark.lucko.me/XPZ4LsZVW4

I get this isn't a game breaking issue and you may not even care but it is worth reporting considering it's the only mod out of 400+ that I've come across to do this. 

Profiler ran by Spark, Each profile was done after allowing the world to load to a stable point then heapdumps were ran to determine aspects of data for benefits of finding issues within the modpack.

**Comment by TelepathicGrunt** [comment]
“ server environment for single player” 

I believe you’re talking about the integrated server that vanilla spins up. Single player is not just a client. It’s a client with a built in server to run serversided stuff locally. 

I can’t read the spark link you gave on mobile as it tells me nothing so you’ll have to please show a bit more about what you’re talking about. Also, how much Ram usage are we talking about here too? Under the hood, RS will increase memory usage anyway due to the nbt files that Mc has to load anyway in order to spawn structures. All structure mod’s nbt file will contribute to memory usage.

It’ll take time before I am able to look more at you file but from the current sound of this, It doesn’t sound like there’s actually an issue.

**Comment by TelepathicGrunt** [comment]
I am at computer and now can look at the spark profiles. The memory usage is well, just about nearly the same. Maybe 0.3 GB difference with 
`net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate$StructureBlockInfo`
showing up quite a bit in the second link which is from processors ran for structures which is a vanilla thing that my mod has. Those StructureTemplate$StructureBlockInfo are super shortlived and will be garbage collected right away. I see no mentions of Biome Modifiers anywhere so not where where that even came up.

Yeah I'm not seeing any actual memory issue here at all even overall for your modpack. To be honest, I don't think this spark heap dump is actually even usable. A proper heap dump would be to use VisualVM to make one and then open the dump file in Eclipse to view where the actually instances of these stuff are living at. Like for `9,653,088 220.9 MB java.util.ArrayList`, a proper heap dump viewer should tell you what classes the list instances here are living in and which class has the largest list.

I think your pack as is looks fine tbh. What specifically is the memory issue you're having? 6GB for a large forge pack seems about normal from what I seen

Edit:
![image](https://user-images.githubusercontent.com/40846040/201562881-9822a432-3256-4ac9-a777-948d66f04867.png)
420 mods??? On Forge? It is honestly a miracle you're only hitting 6GB lmao

**Comment by TelepathicGrunt** [comment]
Closing as it has been over a week with no response
