### ISSUE TITLE
Ancient City End Version overwrites main end island

### ISSUE THREAD

**Issue by djnifos** [TelepathicGrunt/RepurposedStructures#243]
Seed : 1972983197258518424
Tested V.6.3.5 and V.6.3.5
1.19.2
forge - 43.1.52

Prevents dragon spawn, removes dragon respawn structure, becomes impossible to return to overworld without external methods or death.

**Comment by TelepathicGrunt** [comment]
Make a new world for now. Not every world will have ancient city at world origin. I just need to take this line
https://github.com/TelepathicGrunt/RepurposedStructures/blob/f00bf64621ddb3ab36de3930d4fd3234d098d813/src/main/resources/data/repurposed_structures/worldgen/structure_set/pyramids_end.json#L13

And copy it into the end ancient city structure set json so they only spawn farther than 1000 blocks from world origin
https://github.com/TelepathicGrunt/RepurposedStructures/blob/latest-released-Forge/src/main/resources/data/repurposed_structures/worldgen/structure_set/ancient_cities_end.json

**Comment by TelepathicGrunt** [comment]
just released fixed update now
