### ISSUE TITLE
Crashing when trying to create a world

### ISSUE THREAD

**Issue by TheButterbrotMan** [TelepathicGrunt/RepurposedStructures#248]
Hello, when i try to create a world my game crashes.
https://bytebin.lucko.me/CjHKwaagN4

**Comment by TelepathicGrunt** [comment]
are you using an RS compat datapack in 1.19.3?

**Comment by TelepathicGrunt** [comment]
Please share with me the entire latest.log file. Not the crashlog as crashlog files are truncated and never states all the info I need.

**Comment by TheButterbrotMan** [comment]
> 

Not that i know of

**Comment by TheButterbrotMan** [comment]
> are you using an RS compat datapack in 1.19.3?

No, not that i know of.

**Comment by TheButterbrotMan** [comment]
This is the full log: https://bytebin.lucko.me/IGgD3JI4s8

**Comment by TelepathicGrunt** [comment]
fixed now. Update RS to 6.3.1 and it should not crash with fabric Waystones anymore
