### ISSUE TITLE
I did not find any structures

### ISSUE THREAD

**Issue by Medmusss** [TelepathicGrunt/RepurposedStructures#250]
I always make new worlds with this mod but never find any structures from that mod even if the game tells me the mod is on but still nithing

**Comment by TelepathicGrunt** [comment]
@Medmusss when you do `/locate structure repur` does Repurposed Structures’s structures show up in the autocomplete?

 If not, then the mod is not actually running and you need to figure out why. Make sure you got the right mod jar for your modloader and Mc version and the mod jar is in the mods folder.

If it does show up, select one of RS’s structure and teleport to it. Does it show up then?

**Comment by Medmusss** [comment]
Yeah I did what you said and it worked I found the actual structures but without using the command I did not find any while I played minecraft using this mod 1 year ago and I was constantly finding new structures but now not as much. I don't know if I am the problem and I am just saying shi or the mod actually changed

**Comment by TelepathicGrunt** [comment]
Then it sounds like the structures are spawning but you were just unlucky and haven’t found them while exploring. Some structures are a bit more rare like Overworld Cities which Wandering Traders sell maps to. You can increase the structure spawnrates by config if 1.16.5 Mc or by datapack in 1.18.2+ mc. Here’s a link to the datapacks you can use to make structures more common in 1.18.2+ https://github.com/TelepathicGrunt/RepurposedStructures/releases/tag/4.0.0

**Comment by Medmusss** [comment]
alright thank you for explaining and responding so fast by the way is the mod compatible with valhesia structures ?

**Comment by TelepathicGrunt** [comment]
Yep. Repurposed Structures is compatible with just about any mod that I know of. Only possible issue would be if mods changes the overworld to use modded biomes that are not properly “tagged”.  However all the large biome mods I know of are using tags and I verified my structures in them. As long as you can find structures with locate command, they are spawned and you’re good to go!
