### ISSUE TITLE
Wonky generatation when villages overlap with overworld fortresses

### ISSUE THREAD

**Issue by rodnelkes** [TelepathicGrunt/RepurposedStructures#252]
Version: 1.19.3
Seed: -7881515120190134907
<details>
<summary>Relevant mods:</summary>
Terralith_v2.3.5.jar<br>
repurposed_structures_quilt-6.3.12+1.19.3.jar<br>
</details>

<details>
<summary>If needed, all mods:</summary><br>
3dskinlayers-fabric-1.5.2-mc1.19.3.jar<br>
Amplified_Nether_v1.2.jar<br>
BetterF3-5.1.0-Fabric-1.19.3.jar<br>
Capes-1.5.1+1.19.3.jar<br>
Chunky-1.3.53.jar<br>
Continents_1.19_v1.1.1.jar<br>
NoChatReports-FABRIC-1.19.3-v1.19.0.jar<br>
Structory-1.19-v1.3.jar<br>
Terralith_v2.3.5.jar<br>
YetAnotherConfigLib-2.2.0.jar<br>
bettermounthud-1.2.1.jar<br>
c2me-fabric-mc1.19.3-0.2.0+alpha.9.12.jar<br>
carpet-extra-1.19.3-1.4.91.jar<br>
carpet-fixes-1.19.3-1.13.0.jar<br>
carpet-tis-addition-mc1.19.3-v1.44.0.jar<br>
clickthrough-1.19.3-fabric0.68.1-0.4.jar<br>
cloth-config-9.0.94-fabric.jar<br>
dynamic-fps-2.2.0.jar<br>
entity_texture_features_fabric_1.19.3-4.2.0.1.jar<br>
entityculling-fabric-1.5.2-mc1.19.3.jar<br>
fabric-carpet-1.19.3-1.4.91+v221207.jar<br>
ferritecore-5.1.0-fabric.jar<br>
forgetmechunk-1.0.4-1.18.X-1.19.X.jar<br>
inspecio-1.7.0+1.19.3.jar<br>
itemscroller-fabric-1.19.3-0.18.0.jar<br>
itemswapper-fabric-0.3.2-mc1.19.3.jar<br>
krypton-0.2.1.jar<br>
lazydfu-0.1.3.jar<br>
litematica-fabric-1.19.3-0.13.1.jar<br>
lithium-fabric-mc1.19.3-0.10.4.jar<br>
malilib-fabric-1.19.3-0.14.0.jar<br>
memoryleakfix-1.19.3-0.7.0.jar<br>
midnightlib-quilt-1.1.0.jar<br>
minihud-fabric-1.19.3-0.25.0.jar<br>
modmenu-5.0.2.jar<br>
moreculling-1.19.3-0.12.3.jar<br>
ok_zoomer-5.0.0-beta.10+1.19.3.jar<br>
qfapi-5.0.0-alpha.7_qsl-4.0.0-beta.3_fapi-0.70.0_mc-1.19.3.jar<br>
quilt-kotlin-libraries-1.0.0+kt.1.7.20+flk.1.8.5.jar<br>
reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar<br>
repurposed_structures_quilt-6.3.12+1.19.3.jar<br>
smoothboot-fabric-1.19-1.7.1.jar<br>
sodium-fabric-mc1.19.3-0.4.7+build.21.jar<br>
starlight-1.1.1+fabric.ae22326.jar<br>
tweakermore-mc1.19.3-v3.9.2.jar<br>
tweakeroo-fabric-1.19.3-0.15.0.jar<br>
</details>

1.  Villager houses generate in locations where the villagers can never really leave the house. 116 71 100
![2022-12-30_22 38 38](https://user-images.githubusercontent.com/44254053/210124408-bbff1f95-5ee3-43f5-a1ef-917deaeda227.png)
Because of the fences, the villagers that spawn in the house can never leave, boxing them in.

2. Some houses spawn with the fortress blocks in them, not allowing it to be used until the player breaks the blocks inside. 109 68 109
![2022-12-30_22 38 46](https://user-images.githubusercontent.com/44254053/210124490-965690b8-1e15-4765-8044-289672ebe68e.png)
Since in my head, the villagers arrive long after the fortress has been made, the 

3. Not sure if intended, but sometimes blocks that make up the fortress is used in the houses. 75 64 192
![2022-12-30_22 34 21](https://user-images.githubusercontent.com/44254053/210124503-ba297de8-f007-4e82-8cb3-30f0667a471d.png)
I don't really mind this one. 

4. Plots also work weirdly when intersecting the fortress. 127 65 144
![2022-12-30_22 39 02](https://user-images.githubusercontent.com/44254053/210124546-62563fc6-31ac-4950-a34b-d0595af35376.png)

**Comment by TelepathicGrunt** [comment]
Not really an issue. Structure fusions is a normal limitation of minecraft and is ok. Even vanilla has structure fusions at times like this picture where several village houses spawn inside the mansion itself: 
![](https://progameguides.com/wp-content/uploads/2022/06/minecraft-seed-mansion-june-2022-java.jpg)

I could abuse the exclusion zone option to try and keep jungle villages from jungle fortresses but I frankly like seeing some structure fusions here and there. It makes for more interesting combinations and stuff at times as long as it isn’t super frequent. 

Best advice I have for you, just mine the fortress blocks and make the area easier for villagers to walk through. Renovate the area to your likening and add some creativity for how the village and fortress fusion meshes together!

**Comment by rodnelkes** [comment]
I see. I actually like the village on top of the fortress. My only grip is that the natural generation produces weird results. I'll work around them.
