### ISSUE TITLE
Repurposed Structures v1.7.2 (1.16.4 MC) is marked for Forge

### ISSUE THREAD

**Issue by pavog** [TelepathicGrunt/RepurposedStructures#254]
Hi, I saw that the version [Repurposed Structures v1.7.2 (1.16.4 MC)](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric/files/3123150) is marked for Forge.
Is this a typo?

**Comment by TelepathicGrunt** [comment]
Fixed. But don’t play 1.16.4. Use the 1.16.5 files at the very least

**Comment by pavog** [comment]
Wow that was fast.
Thanks a lot!
