### ISSUE TITLE
Repurposed Structures is Possibly Missing "Some" Tags

### ISSUE THREAD

**Issue by Coraline774477** [TelepathicGrunt/RepurposedStructures#257]
Minecraft: 1.19.2
Forge: 1.19.2-43.2.3
Repurposed Structures: 1.19.2-6.3.7

While I was reporting a crash that was caused by different mods I was looking through the latest log of my newly created 1.19.2 world and I saw that repurposed structures couldn't load alot of it's tags correctly.
I think it can't load any of it's tags for some strange reason..

Here's my latest log which will tell you everything that's possibly missing;

https://gist.github.com/Coraline774477/fe13c229063dfec8e6ac5bd7cee18bd6

What it'll mostly say is what I've reported to the author of Zombie Friends mod already but take a good look in there cause Repurposed Structures is in there and there's ALOT of missing tags apparently.

**Comment by TelepathicGrunt** [comment]
It's just worldgen tag logspam caused by forge in 1.19.2 and below and affected quite a few mods besides mine. Magically fixed itself in 1.19.3 https://github.com/MinecraftForge/MinecraftForge/issues/8771

The tags exists in my mod and they still function in your world. Just forge somehow causes it to pretend it cannot be parsed when json is parsed the first time around with creating/opening worlds for whatever unknown reason. No other loader has shown this logspam

**Comment by Coraline774477** [comment]
Oh, okay. Was just making sure even tho I don't remember seeing all of the forge logspam in 1.19.2 with Repurposed Structures installed before till recently, unless it's always been doing that after 43.2.0 or even 43.1.0.
At least the logspam issue caused by forge itself has magically fixed itself somehow in 1.19.3.

Speaking of that I'm starting my 1.19.3 worlds today (as of Cora World (1.19.3)) even tho I was waiting for Modern UI to be ported to 1.19.3.
But that'll take quite some time since Mojang literally changed the rendering engine yet again. 
So now mods like Modern UI will have to go through a rewrite yet again which that takes alot of time to do to be able to port over to 1.19.3.

So why I'm starting 1.19.3 now is cause of my war against my own computer as of the RAM department which I'm scanning for any possible malware threats since malware is known to cause potential high RAM usage.
Since I had noticed that while I was playing minecraft that I'm running out of memory which has caused some of my modded worlds already since they had between 60-70 mods.

So I had to either decrease the amount of mods for all of my worlds or get rid of most of the worlds entirely cause of taking out alot of mods that added to the theme of the worlds which I had to get rid of Cora World 4 which its theme was all about Simple Ores and its addon mods but I took the addon mods out for more RAM and decided to get rid of the world cause it turned into what was Cora World (1.19.2) which only had Simple Ores as the main theme which that world no longer exists due to boredom and lost interest in that world as I lost interest in Simple Ores again.

I had to get rid of Cora World T.I.C (Tinkers' Construct 3) 1.18.2 cause of the same reasons as well as boredom of Tinkers cause I was taking too long with each material that I could make in Tinkers Construct.

I had to get rid of my latest world Cora World; Zombie Apocalypse due to the same reason as Cora World 4 and it just became a gun world and lost interest in gun mods again..

So now the new min/max amount of mods I can play with on my ASUS VivoBook 15 now is between 45-55 mods...

Who knew that minecraft is so RAM intensive more than CPU/GPU intensive?....

**Comment by TelepathicGrunt** [comment]
Be sure to use Ferritecore and other performance mods that might help with RAM. https://github.com/TheUsefulLists/UsefulMods/blob/main/Performance/Performance119.md

**Comment by Coraline774477** [comment]
I am using Ferrite Core but apparently it's still not enough cause its random at times that I get the out of memory error after a few hours of game time or would happen after 6-8 hours later.

Bte I've decided to remain in 1.19.2 and going back to Tinkers' Construct 1.18.2 (but starting on teir 2 materials instead of the first teir of materials) cause I'm truly not ready for 1.19.3 yet and the performance plays a role in my decision as well. Btw did ya know that 1.19.4 is in snapshots right now? Apparently I didn't know till recently when Architectury API ported their fabric version to the first snapshot of 1.19.4 yesterday.

Btw I wouldn't mind talkin with you on either dms on discord or if you have a discord server that I can join so that we could talk on there instead of here if you want.

**Comment by TelepathicGrunt** [comment]
My discord channel is the telepathic grunt channel here. The bottom of my mod pages on curseforge and modrinth has the link if you lose it https://discord.gg/K8qRev3yKZ
