### ISSUE TITLE
1.19.2 [Forge] Can't /locate the dungeon structure.

### ISSUE THREAD

**Issue by SmittyTheGod** [TelepathicGrunt/RepurposedStructures#265]
For my modpack I need to config the structes to have quark chests but whenever I try to find the dungeon structures I can't /locate them, also I cant find them in the configuration datapack for this mod. Its like they don't exist
![2023-02-25_17 42 11](https://user-images.githubusercontent.com/101068560/221382895-b563dd73-c795-4c70-9bca-59cc32e42306.png)
![2023-02-25_17 40 24](https://user-images.githubusercontent.com/101068560/221382898-dc23d89e-f749-471a-a8ea-9d38f50b966b.png)

**Comment by TelepathicGrunt** [comment]
Dungeons are not structures. They are features just like vanilla’s dungeons which are not structures. Thus no locate command. The config datapack has them under the worldgen/configured_feature folder where you can edit what chest they spawn with: https://github.com/TelepathicGrunt/RepurposedStructures/releases/tag/4.0.0

This line you would change when you override the files by datapack: https://github.com/TelepathicGrunt/RepurposedStructures/blob/5c8b32f300c216e35d95b4e780742be1cd6fae5a/src/main/resources/data/repurposed_structures/worldgen/configured_feature/dungeons/badlands.json#L18

change it to quark’s blocks. Delete all other files/folders you have not edited and that should work

**Comment by TelepathicGrunt** [comment]
im assuming you got this to work with my suggestion so I'll close this since there isn't actually a bug with /locate
