### ISSUE TITLE
Extremaly lag SERVER TPS=0

### ISSUE THREAD

**Issue by MrJorman** [TelepathicGrunt/RepurposedStructures#266]
https://spark.lucko.me/lGXV91RGTV When I open a wandering trade that trades maps of mushroom villages or other dungeons, my server freezes for 5-10 or even 15 seconds and everything hangs very badly. I even made a spark profiler

**Comment by MrJorman** [comment]
Version: 1.19.2 Fabric

**Comment by TelepathicGrunt** [comment]
This is not a repurposed structures issue. Explorer Maps are just locate commands basically and in order for them to show the closest structure to find, they require to find the structure first. Vanilla has this locating run immediately when the map item is made.

So if a structure is far away or you have enough terrain mods that messed with biome layout and made the structure beyond rare, it’ll take longer for the map to find the structure. Not really anything I can do about it. 

If the maps are taking longer than say 10 seconds to find the structure, you can disable the maps from wandering traders by overriding this file by datapack: 
https://github.com/TelepathicGrunt/RepurposedStructures/blob/1.19.3-Arch/common/src/main/resources/data/repurposed_structures/structure_map_trades/default_maps.json

Or mess with the structure’s spawnrates to make it more common or add more biomes to the structures valid biome tags to give them more valid areas to spawn in.

The gold standard would be this async locator mod but it is forge only. If one ports it to Fabric, this is what I would recommend to fix this vanilla flaw with maps: https://www.curseforge.com/minecraft/mc-mods/async-locator

Even vanilla has this issue with Explorer Maps to Treasure Chest structure: https://bugs.mojang.com/browse/MC-249136

Closing as this is beyond what I can do
