### ISSUE TITLE
Server crash with 34.1.17 forge and Repurposed Structures v2.2.7 (1.16.3 MC)  Download

### ISSUE THREAD

**Issue by Letoric** [TelepathicGrunt/RepurposedStructures#27]
---- Minecraft Crash Report ----
// You're mean.

Time: 10/10/20 2:53 PM
Description: Exception in server tick loop

java.lang.UnsupportedOperationException: null
	at com.google.common.collect.ImmutableMap.putAll(ImmutableMap.java:572) ~[server-1.16.3-20200911.084530-extra.jar:?] {re:mixin}
	at com.telepathicgrunt.repurposedstructures.RepurposedStructures.addDimensionalSpacing(RepurposedStructures.java:159) ~[?:1.16.3-2.2.7] {re:mixin,re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:376) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:305) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:164) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:617) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 11631787016 bytes (11092 MB) / 17179869184 bytes (16384 MB) up to 17179869184 bytes (16384 MB)
	CPUs: 12
	JVM Flags: 27 total; -Xmx16G -Xms16G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Xloggc:gc.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=1M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.17.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.17.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.17.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.17.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.17.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.17
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		NetherPortalFix_1.16.3-7.2.0.jar NetherPortalFix {netherportalfix@7.2.0 DONE}
		aiotbotania-1.16.2-1.3.2.jar AIOT Botania {aiotbotania@1.3.2 DONE}
		forge-1.16.3-geckolib-2.1.2.jar GeckoLib {geckolib@2.1.2 DONE}
		simplemagnets-1.0.8-mc1.16.3.jar Simple Magnets {simplemagnets@1.0.8 DONE}
		mcw-windows-1.0.2-mc1.16.3.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		modnametooltip_1.16.2-1.15.0.jar Mod Name Tooltip {modnametooltip@1.15.0 DONE}
		KleeSlabs_1.16.3-9.2.0.jar KleeSlabs {kleeslabs@9.2.0 DONE}
		rsgauges-1.16.3-1.2.4.jar Gauges and Switches {rsgauges@1.2.4 DONE}
		IronJetpacks-1.16.3-4.1.1.jar Iron Jetpacks {ironjetpacks@4.1.1 DONE}
		CookingForBlockheads_1.16.3-9.2.1.jar Cooking for Blockheads {cookingforblockheads@9.2.1 DONE}
		Controlling-7.0.0.8.jar Controlling {controlling@7.0.0.8 DONE}
		Placebo-1.16.3-4.3.2.jar Placebo {placebo@4.3.2 DONE}
		dankstorage-3.11.jar Dank Storage {dankstorage@3.11 DONE}
		citadel-1.4.0.jar Citadel {citadel@1.4.0 DONE}
		Powah-1.16.3-2.3.0.jar Powah {powah@2.3.0 DONE}
		ftb-gui-library-1603.1.1.19.jar FTB GUI Library {ftbguilibrary@1603.1.1.19 DONE}
		rangedpumps-0.8.2.jar Ranged Pumps {rangedpumps@0.8.2 DONE}
		potionsmaster-0.1.22-1.16.3-34.1.0.jar Potions Master {potionsmaster@0.1.22 DONE}
		jumbofurnace-1.16.3-2.1.0.0.jar Jumbo Furnace {jumbofurnace@1.16.3-2.1.0.0 DONE}
		culinaryconstruct-forge-1.16.3-4.0.0.1.jar Culinary Construct {culinaryconstruct@1.16.3-4.0.0.1 DONE}
		Wither-Skeleton-Tweaks-1.16.3-5.2.1.jar Wither Skeleton Tweaks {wstweaks@5.2.1 DONE}
		Bookshelf-1.16.3-8.4.15.jar Bookshelf {bookshelf@8.4.15 DONE}
		Reliquary-1.16.3-1.3.4.1015.jar Reliquary {xreliquary@1.16.3-1.3.4.1015 DONE}
		randompatches-1.16.2-1.22.1.2.jar RandomPatches {randompatches@1.16.2-1.22.1.2 DONE}
		buildinggadgets-3.7.0.jar Building Gadgets {buildinggadgets@3.7.0 DONE}
		Apotheosis-1.16.3-4.3.1.jar Apotheosis {apotheosis@4.3.1 DONE}
		mcw-doors-1.0.1fix-mc1.16.3-1.16.2.jar Macaw's Doors {mcwdoors@1.0.1 DONE}
		LightingWand-1.16.2-1.7.0.jar Lighting Wand {lightingwand@1.7.0 DONE}
		Morpheus-1.16.3-4.2.59.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.16.3-10.0.11.436.jar Mekanism: Generators {mekanismgenerators@10.0.11 DONE}
		WaterStrainer-1.16.3-10.0.0.jar Water Strainer {waterstrainer@1.16.3-10.0.0 DONE}
		Ma-Essentials-1.16.3-3.4.0.jar Ma Essentials {maessentials@1.16.3-3.4.0 DONE}
		carryon-1.16.3-1.15.0.6.jar Carry On {carryon@1.15.0.6 DONE}
		JustEnoughResources-1.16.3-0.12.0.100.jar Just Enough Resources {jeresources@0.12.0.100 DONE}
		XNetGases-1.16.3-2.0.0.jar XNet Gases {xnetgases@2.0.0 DONE}
		confdespawntimer_1.16.3_1.3.jar Configurable Despawn Timer {confdespawntimer@1.3 DONE}
		ftb-teams-1.0.1.12.jar FTB Teams {ftbteams@1.0.1.12 DONE}
		shetiphiancore-1.16-3.8.2.jar ShetiPhian-Core {shetiphiancore@3.8.2 DONE}
		MysticalAgradditions-1.16.3-4.1.0.jar Mystical Agradditions {mysticalagradditions@4.1.0 DONE}
		absentbydesign-1.16.3-1.1.1.jar Absent By Design Mod {absentbydesign@1.16.3-1.1.1 DONE}
		emojiful-1.16.3-2.1.0.jar Emojiful {emojiful@1.16.3-2.1.0 DONE}
		refinedstorage-1.9.7.jar Refined Storage {refinedstorage@1.9.7 DONE}
		corpse-1.16.3-1.0.6.jar Corpse {corpse@1.16.3-1.0.6 DONE}
		PackMenu-1.16.3-2.3.0.jar Pack Menu {packmenu@2.3.0 DONE}
		alltheores-0.1.10-1.16.3-34.1.0.jar AllTheOres {alltheores@0.1.10 DONE}
		mcw-bridges-1.0.4-mc1.16.3.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		industrial-foregoing-1.16.3-3.1.1-a834e76.jar Industrial Foregoing {industrialforegoing@3.1.1 DONE}
		cleancut-mc1.16-2.2-forge.jar Clean Cut {cleancut@2.2 DONE}
		useful_backpacks-1.16.3-1.11.5.82.jar Useful Backpacks {usefulbackpacks@1.11.5.82 DONE}
		torchmaster-2.3.3-alpha.jar Torchmaster {torchmaster@2.3.3-alpha DONE}
		repurposed_structures-1.16.3-2.2.7.jar Repurposed Structures {repurposed_structures@1.16.3-2.2.7 DONE}
		chonk-1.16.3-0.1.4.jar Chonk {chonk@1.16.3-0.1.4 DONE}
		entangled-1.2.7-mc1.16.3.jar Entangled {entangled@1.2.7 DONE}
		endertanks-1.16-1.9.3.jar EnderTanks {endertanks@1.9.3 DONE}
		crashutilities-3.5.jar Crash Utilities {crashutilities@3.5 DONE}
		Compressium-1.16.3-1.1.33.jar Compressium {compressium@1.1.33 DONE}
		enchantingcmds_1.16.3_1.3.jar Enchanting Commands {enchantingcmds@1.3 DONE}
		BiomesOPlenty-1.16.3-12.0.0.405-universal.jar Biomes O' Plenty {biomesoplenty@1.16.3-12.0.0.405 DONE}
		MekanismAdditions-1.16.3-10.0.11.436.jar Mekanism: Additions {mekanismadditions@10.0.11 DONE}
		valkyrielib-1.16.3-3.0.3.2.jar ValkyrieLib {valkyrielib@1.16.3-3.0.3.2 DONE}
		Lollipop-1.16.3-3.2.0.jar Lollipop {lollipop@3.2.0 DONE}
		ftb-ranks-1.0.0.7.jar FTB Ranks {ftbranks@1.0.0.7 DONE}
		SilentGear-1.16.3-2.3.0+165.jar Silent Gear {silentgear@2.3.0+165 DONE}
		simplylight-1.16.3-1.0.2.jar Simply Light {simplylight@1.16.3-1.0.2 DONE}
		tgcropesmod-1.16.2-1.1.0.jar Ropes Mod {tgcropesmod@1.16.2-1.1.0 DONE}
		atmadditions-1.16.2-1.0.0.jar All The Mods: Additions {atmadditions@1.16.2-1.0.0 DONE}
		SolarFluxReborn-1.16.3-16.1.2.jar Solar Flux Reborn {solarflux@16.1.2 DONE}
		portality-1.16.3-3.1.1.jar Portality {portality@3.1.1 DONE}
		curios-forge-1.16.3-4.0.2.0.jar Curios API {curios@1.16.3-4.0.2.0 DONE}
		Botania-1.16.2-406.jar Botania {botania@1.16.2-406 DONE}
		managear-1.16.3-2.1.2.jar Mana Gear {managear@1.16.1-2.1.2 DONE}
		Patchouli-1.16.2-44.jar Patchouli {patchouli@1.16.2-44 DONE}
		collective-1.16.3-1.51.jar Collective {collective@1.51 DONE}
		camera-1.16.3-1.0.3.jar Camera Mod {camera@1.16.3-1.0.3 DONE}
		tanknull-2.1-1.16.2.jar Tank Null {tanknull@2.1-1.16.2 DONE}
		angelring-1.16.3-1.3.3.jar Angel Ring {angelring@1.3.3 DONE}
		MysticalCustomization-1.16.3-2.1.0.jar Mystical Customization {mysticalcustomization@2.1.0 DONE}
		elevatorid-1.16.3-1.7.6.jar Elevator Mod {elevatorid@1.16.3-1.7.6 DONE}
		ftb-ultimine-1.1.0.10.jar FTB Ultimine {ftbultimine@1.1.0.10 DONE}
		Runelic-1.16.3-5.0.1.jar Runelic {runelic@5.0.1 DONE}
		DarkUtilities-1.16.3-6.0.3.jar Dark Utilities {darkutils@6.0.3 DONE}
		ExtraStorage-1.16.3-1.1.0.jar Extra Storage {extrastorage@1.1.0 DONE}
		worldedit-forge-mc1.16.3-7.2.0-rc-01.jar WorldEdit {worldedit@7.2.0-rc-01+81f978e DONE}
		NaturesAura-30.0.jar Nature's Aura {naturesaura@30.0 DONE}
		MekanismTools-1.16.3-10.0.11.436.jar Mekanism: Tools {mekanismtools@10.0.11 DONE}
		constructionwand-1.16.2-1.5.jar Construction Wand {constructionwand@1.16.2-1.5 DONE}
		mcws-roofs-1.16.3-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
		cc-tweaked-1.16.3-1.93.0.jar CC: Tweaked {computercraft@1.93.0 DONE}
		globalxp-1.16.3-v1.4.14.jar Global XP {globalxp@v1.4.14 DONE}
		cloth-config-forge-4.1.0.jar Cloth Config v4 API {cloth-config@4.0 DONE}
		trashcans-1.0.3-mc1.16.3.jar Trash Cans {trashcans@1.0.3 DONE}
		TrampleStopper-2.2.0+build.1.mcVersion.1.16.3.jar Trample Stopper {tramplestopper@2.2.0+build.1.mcVersion.1.16.3 DONE}
		bwncr-1.16.3-3.8.15.jar Bad Wither No Cookie Reloaded {bwncr@1.16.3-3.8.15 DONE}
		FastLeafDecay-v25.jar FastLeafDecay {fastleafdecay@v25 DONE}
		BetterMineshaftsForge-1.16.2-1.0.jar YUNG's Better Mineshafts {bettermineshafts@1.16.2-1.0 DONE}
		Cyclic-1.16.3-0.8.0.jar Cyclic {cyclic@1.16.3-0.8.0 DONE}
		BetterAdvancements-1.16.3-0.1.0.102.jar Better Advancements {betteradvancements@0.1.0.102 DONE}
		ClientTweaks_1.16.3-5.2.0.jar Client Tweaks {clienttweaks@5.2.0 DONE}
		nomowanderer_MC1.16.3_1.0.jar NoMoWanderer {nomowanderer@1.16.3_1.0 DONE}
		doubledoors_1.16.3_2.1.jar Double Doors {doubledoors@2.1 DONE}
		Cucumber-1.16.3-4.1.2.jar Cucumber Library {cucumber@4.1.2 DONE}
		TrashSlot_1.16.3-12.2.0.jar TrashSlot {trashslot@12.2.0 DONE}
		mining-helmet-1.16.3-1.0.9.jar Mining Helmet {mining_helmet@1.0.9 DONE}
		flatbedrock-1.16.3-1.1.3.jar Flat Bedrock {flatbedrock@1.16.3-1.1.3 DONE}
		woot-1.16.2-1.0.0.0.jar Woot {woot@1.16.2-1.0.0.0 DONE}
		bagofyurting-1.16.3-1.1.0.1.jar Bag of Yurting {bagofyurting@1.1.0.1 DONE}
		item-filters-2.2.2.17.jar Item Filters {itemfilters@2.2.2.17 DONE}
		platforms-1.16-1.7.5--TESTER1.jar Platforms {platforms@1.7.5 DONE}
		jei-1.16.3-7.5.0.43.jar Just Enough Items {jei@7.5.0.43 DONE}
		elementalcraft-1.16.3-2.3.4.jar ElementalCraft {elementalcraft@1.16.3-2.3.4 DONE}
		metalbarrels-3.3a.jar Metal Barrels {metalbarrels@3.3a DONE}
		AttributeFix-1.16.3-8.0.2.jar AttributeFix {attributefix@8.0.2 DONE}
		Mekanism-1.16.3-10.0.11.436.jar Mekanism {mekanism@10.0.11 DONE}
		invtweaks-1.16.2-1.0.0.jar Inventory Tweaks Renewed {invtweaks@1.16.2-1.0.0 DONE}
		Waystones_1.16.3-7.3.0.jar Waystones {waystones@7.3.0 DONE}
		Clumps-6.0.0.11.jar Clumps {clumps@6.0.0.11 DONE}
		shutupexperimentalsettings-1.0.0.jar Shutup Experimental Settings! {shutupexperimentalsettings@1.0.0 DONE}
		light-overlay-5.5.3.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		enviromats-1.16.3-2.0.3.2.jar Environmental Materials {enviromats@1.16.3-2.0.3.2 DONE}
		comforts-forge-1.16.3-4.0.0.1.jar Comforts {comforts@1.16.3-4.0.0.1 DONE}
		appliedenergistics2-8.1.0-alpha.3.jar Applied Energistics 2 {appliedenergistics2@8.1.0-alpha.3 DONE}
		NaturesCompass-1.16.3-1.8.5.jar Nature's Compass {naturescompass@1.16.3-1.8.5 DONE}
		DimStorage-1.16.3-4.2.1.jar DimStorage {dimstorage@4.2.1 DONE}
		BotanyPots-1.16.3-5.0.7.jar BotanyPots {botanypots@5.0.7 DONE}
		engineerstools-1.16.3-1.1.0.jar Engineer's Tools {engineerstools@1.1.0 DONE}
		FarmingForBlockheads_1.16.3-7.2.0.jar Farming for Blockheads {farmingforblockheads@7.2.0 DONE}
		BadMobs-1.16.3-7.0.1.jar BadMobs {badmobs@7.0.1 DONE}
		pneumaticcraft-repressurized-1.16.3-2.4.2-49.jar PneumaticCraft: Repressurized {pneumaticcraft@1.16.3-2.4.2-49 DONE}
		demagnetize-forge-1.16.2-1.2.2.jar Demagnetize {demagnetize@1.16.2-1.2.2 DONE}
		mcjtylib-1.16-5.0.9.jar McJtyLib {mcjtylib@1.16-5.0.9 DONE}
		rftoolsbase-1.16-2.0.5.jar RFToolsBase {rftoolsbase@1.16-2.0.5 DONE}
		xnet-1.16-3.0.7.jar XNet {xnet@1.16-3.0.7 DONE}
		rftoolsstorage-1.16-2.0.5.jar RFToolsStorage {rftoolsstorage@1.16-2.0.5 DONE}
		rftoolscontrol-1.16-4.0.5.jar RFToolsControl {rftoolscontrol@1.16-4.0.5 DONE}
		restrictions-1.16-3.0.3.jar Restrictions {restrictions@1.16-3.0.3 DONE}
		pedestals-0.8a.jar Pedestals {pedestals@0.8a DONE}
		mahoutsukai-1.16.3-v1.24.0.jar Mahou Tsukai {mahoutsukai@1.16.3-v1.24.0 DONE}
		Toast-Control-1.16.3-4.3.0.jar Toast Control {toastcontrol@4.3.0 DONE}
		mininggadgets-1.6.0.jar Mining Gadgets {mininggadgets@1.6.0 DONE}
		Ars Nouveau-1.16.3 0.20.5.jar Ars Nouveau {ars_nouveau@1.0 DONE}
		rftoolspower-1.16-3.0.7.jar RFToolsPower {rftoolspower@1.16-3.0.7 DONE}
		extradisks-1.16.3-1.3.3.jar Extra Disks {extradisks@1.3.3 DONE}
		ftb-chunks-1.1.2.36.jar FTB Chunks {ftbchunks@1.1.2.36 DONE}
		forge-1.16.3-34.1.17-universal.jar Forge {forge@34.1.17 DONE}
		scuba-gear-1.16.3-1.0.1.jar Scuba Gear {scuba_gear@1.0.1 DONE}
		MysticalAgriculture-1.16.3-4.1.0.jar Mystical Agriculture {mysticalagriculture@4.1.0 DONE}
		ironchest-1.16.3-11.2.6.jar Iron Chests {ironchest@1.16.3-11.2.6 DONE}
		CraftingTweaks_1.16.3-12.2.0.jar Crafting Tweaks {craftingtweaks@12.2.0 DONE}
		forge-1.16.3-34.1.17-server.jar Minecraft {minecraft@1.16.3 DONE}
		rftoolsutility-1.16-3.0.10.jar RFToolsUtility {rftoolsutility@1.16-3.0.10 DONE}
		EnchantmentDescriptions-1.16.3-5.0.5.jar EnchantmentDescriptions {enchdesc@5.0.5 DONE}
		theoneprobe-1.16-3.0.4-beta.jar The One Probe {theoneprobe@1.16-3.0.4-beta DONE}
		MouseTweaks-2.13-mc1.16.2.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.16.2-1.14.4.jar Tool Belt {toolbelt@1.14.4 DONE}
		titanium-1.16.3-3.1.0.jar Titanium {titanium@3.1.0 DONE}
		ImmersiveEngineering-1.16.3-4.1.0-124.jar Immersive Engineering {immersiveengineering@1.16.3-4.1.0-124 DONE}
		useful_railroads-1.16.3-1.4.4.31.jar Useful Railroads {usefulrailroads@1.4.4.31 DONE}
		SilentLib-1.16.3-4.8.1+61.jar Silent Lib {silentlib@4.8.1+61 DONE}
		pamhc2crops-1.16.3-1.0.0.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		allthemodium-1.1.11-1.16.3-34.1.0.jar Allthemodium {allthemodium@1.1.11 DONE}
		forbidden_arcanus-1.16.3-1.0.1.jar Forbidden & Arcanus {forbidden_arcanus@1.16.3-1.0.1 DONE}
		rftoolsbuilder-1.16-3.0.7.jar RFToolsBuilder {rftoolsbuilder@1.16-3.0.7 DONE}
		jeiintegration_1.16.3-6.0.0.8.jar JEI Integration {jeiintegration@6.0.0.8 DONE}
		rats-7.0.0-1.16.3.jar Rats {rats@7.0.0 DONE}
		ratlantis-1.0.0-1.16.3.jar Rats: Ratlantis {ratlantis@1.0.0-1.16.3 DONE}
		pamhc2foodcore-1.16.3-1.0.0.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		ftb-backups-2.1.1.6.jar FTB Backups {ftbbackups@2.1.1.6 DONE}
		FastWorkbench-1.16.3-4.4.0.jar FastWorkbench {fastbench@4.4.0 DONE}
		polymorph-forge-1.16.3-0.15.jar Polymorph {polymorph@1.16.3-0.15 DONE}
		StorageDrawers-1.16.2-8.1.0.jar Storage Drawers {storagedrawers@1.16.2-8.1.0 DONE}
		enderchests-1.16-1.7.4--TESTER1.jar EnderChests {enderchests@1.7.4 DONE}
		PickleTweaks-1.16.3-5.1.2.jar Pickle Tweaks {pickletweaks@5.1.2 DONE}
		FastFurnace-1.16.3-4.3.0.jar FastFurnace {fastfurnace@4.3.0 DONE}
		AppleSkin-mc1.16.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		engineersdecor-1.16.3-1.1.3-b1.jar Engineer's Decor {engineersdecor@1.1.3-b1 DONE}
		solcarrot-1.16.3-1.9.8.jar Spice of Life: Carrot Edition {solcarrot@1.16.3-1.9.8 DONE}
		modular-routers-1.16.3-7.1.0-35.jar Modular Routers {modularrouters@1.16.3-7.1.0-35 DONE}
		allthetweaks-1.1.7-1.16.3-34.1.10.jar All The Tweaks {allthetweaks@1.1.7 DONE}
		kubejs-1603.2.8.71.jar KubeJS {kubejs@1603.2.8.71 DONE}
		u_team_core-1.16.3-3.1.9.181.jar U Team Core {uteamcore@3.1.9.181 DONE}
		byg-1.0.7.jar Oh The Biomes You'll Go {byg@1.0.7 DONE}
		Aquaculture-1.16.3-2.1.1.jar Aquaculture 2 {aquaculture@1.16.3-2.1.1 DONE}
		refinedstorageaddons-0.7.2.jar Refined Storage Addons {refinedstorageaddons@0.7.2 DONE}
		CosmeticArmorReworked-1.16.3-v1.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.3-v1 DONE}
		morered-1.16.3-2.0.0.0.jar More Red {morered@2.0.0.0 DONE}
		balancedenchanting-1.0.jar Balanced Enchanting {balancedenchanting@1.0 DONE}
		xptome-1.16.2-v1.1.6.jar XP Tome {xpbook@v1.1.6 DONE}
	Crash Report UUID: 139eccb1-456b-4aa9-919f-ca567cfd4790
	Player Count: 0 / 20; []
	Data Packs: vanilla, mod:netherportalfix (incompatible), mod:aiotbotania (incompatible), mod:geckolib (incompatible), mod:simplemagnets (incompatible), mod:mcwwindows (incompatible), mod:modnametooltip, mod:kleeslabs (incompatible), mod:rsgauges, mod:ironjetpacks, mod:cookingforblockheads (incompatible), mod:controlling (incompatible), mod:placebo (incompatible), mod:dankstorage (incompatible), mod:citadel (incompatible), mod:powah, mod:ftbguilibrary (incompatible), mod:rangedpumps, mod:potionsmaster, mod:jumbofurnace (incompatible), mod:culinaryconstruct (incompatible), mod:wstweaks (incompatible), mod:bookshelf, mod:xreliquary (incompatible), mod:randompatches (incompatible), mod:buildinggadgets, mod:apotheosis (incompatible), mod:mcwdoors, mod:lightingwand, mod:morpheus (incompatible), mod:mekanismgenerators, mod:waterstrainer, mod:maessentials (incompatible), mod:carryon, mod:jeresources, mod:confdespawntimer, mod:ftbteams (incompatible), mod:shetiphiancore, mod:mysticalagradditions (incompatible), mod:absentbydesign (incompatible), mod:emojiful (incompatible), mod:refinedstorage, mod:corpse, mod:packmenu (incompatible), mod:alltheores, mod:mcwbridges (incompatible), mod:industrialforegoing (incompatible), mod:cleancut (incompatible), mod:usefulbackpacks, mod:torchmaster (incompatible), mod:repurposed_structures (incompatible), mod:chonk (incompatible), mod:entangled (incompatible), mod:endertanks, mod:crashutilities (incompatible), mod:compressium (incompatible), mod:enchantingcmds, mod:biomesoplenty (incompatible), mod:mekanismadditions, mod:valkyrielib, mod:lollipop, mod:ftbranks (incompatible), mod:silentgear, mod:simplylight, mod:tgcropesmod (incompatible), mod:atmadditions (incompatible), mod:solarflux, mod:portality (incompatible), mod:curios, mod:botania, mod:managear, mod:patchouli (incompatible), mod:collective, mod:camera, mod:tanknull (incompatible), mod:angelring (incompatible), mod:mysticalcustomization (incompatible), mod:elevatorid (incompatible), mod:ftbultimine (incompatible), mod:runelic, mod:darkutils (incompatible), mod:extrastorage, mod:worldedit (incompatible), mod:naturesaura (incompatible), mod:mekanismtools, mod:constructionwand (incompatible), mod:mcwroofs (incompatible), mod:computercraft, mod:globalxp, mod:cloth-config (incompatible), mod:trashcans (incompatible), mod:tramplestopper (incompatible), mod:bwncr (incompatible), mod:fastleafdecay (incompatible), mod:bettermineshafts (incompatible), mod:cyclic (incompatible), mod:betteradvancements, mod:clienttweaks (incompatible), mod:doubledoors, mod:cucumber, mod:trashslot (incompatible), mod:mining_helmet (incompatible), mod:flatbedrock (incompatible), mod:woot, mod:bagofyurting (incompatible), mod:itemfilters (incompatible), mod:platforms, mod:jei, mod:elementalcraft, mod:metalbarrels (incompatible), mod:attributefix, mod:mekanism, mod:invtweaks (incompatible), mod:waystones (incompatible), mod:clumps (incompatible), mod:shutupexperimentalsettings (incompatible), mod:lightoverlay-forge (incompatible), mod:enviromats (incompatible), mod:comforts (incompatible), mod:appliedenergistics2 (incompatible), mod:naturescompass (incompatible), mod:dimstorage, mod:botanypots, mod:engineerstools, mod:farmingforblockheads (incompatible), mod:badmobs (incompatible), mod:pneumaticcraft, mod:demagnetize (incompatible), mod:mcjtylib, mod:rftoolsbase, mod:xnet, mod:rftoolsstorage, mod:rftoolscontrol, mod:restrictions (incompatible), mod:pedestals (incompatible), mod:mahoutsukai (incompatible), mod:toastcontrol (incompatible), mod:mininggadgets (incompatible), mod:ars_nouveau (incompatible), mod:rftoolspower, mod:extradisks, mod:ftbchunks (incompatible), mod:forge, mod:scuba_gear (incompatible), mod:mysticalagriculture, mod:ironchest (incompatible), mod:craftingtweaks (incompatible), mod:rftoolsutility, mod:enchdesc, mod:theoneprobe, mod:mousetweaks, mod:toolbelt (incompatible), mod:titanium (incompatible), mod:immersiveengineering (incompatible), mod:usefulrailroads, mod:silentlib (incompatible), mod:pamhc2crops (incompatible), mod:allthemodium, mod:forbidden_arcanus (incompatible), mod:rftoolsbuilder, mod:jeiintegration, mod:rats, mod:ratlantis, mod:pamhc2foodcore (incompatible), mod:ftbbackups (incompatible), mod:fastbench (incompatible), mod:polymorph (incompatible), mod:storagedrawers (incompatible), mod:enderchests, mod:pickletweaks, mod:fastfurnace (incompatible), mod:appleskin, mod:engineersdecor, mod:solcarrot (incompatible), mod:modularrouters, mod:allthetweaks, mod:kubejs (incompatible), mod:uteamcore, mod:byg (incompatible), mod:aquaculture (incompatible), mod:refinedstorageaddons, mod:cosmeticarmorreworked (incompatible), mod:morered (incompatible), mod:balancedenchanting (incompatible), mod:xpbook, mod:xnetgases, mod:nomowanderer (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by TelepathicGrunt** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaa

just curious, do you know if any dimension is using a flat chunk generator? Like the land is completely flat?

**Comment by Letoric** [comment]
Yes, it's All the Mods, and their mining dimension is flat

**Comment by TelepathicGrunt** [comment]
that explains it lol. I was cleaning up code and someone said the special map of structure spacing for dimensions is mutable except for flat chunk generators. So I removed some code to simplify thing but forgot that some mods specifically use FlatChunkGenerator which makes the structure spacing map immutable.

this is on me sorry. Give me a few minutes and I'll push a hotfix

**Comment by Letoric** [comment]
No worries, and thanks.

**Comment by TelepathicGrunt** [comment]
This should fix the issue. Give it a shot! 
And thank you for letting me know about the crash asap!

https://www.curseforge.com/minecraft/mc-mods/repurposed-structures/files/3076405

**Comment by Letoric** [comment]
Looks like the world booted ok, and I was able to log in and travel to the
mining dimension without getting a crash. I also ran /locate to check it
since I have a good backup, and that worked ok too.

**Comment by TelepathicGrunt** [comment]
Awesome! I'll close this now and I'll dele the previous broken release to stop anymore crashes with this
