### ISSUE TITLE
Something wrong in main thread? 

### ISSUE THREAD

**Issue by Rad586** [TelepathicGrunt/RepurposedStructures#278]
Mod version: 4.1.15
Game version: 1.18.2 fabric
Link: https://spark.lucko.me/6P125kZreF
Screenshot: https://postimg.cc/gallery/4Y22yZq
Sorry if this is something normal, but it looks so wrong...

**Comment by TelepathicGrunt** [comment]
What specifically looks wrong? The shipwreck structure needs to get the shape of terrain to know if there’s room for it to spawn. The game gets the column of blocks at the spot which means it has to run the density functions that determines the shape of the terrain for that spot

**Comment by Rad586** [comment]
> What specifically looks wrong? The shipwreck structure needs to get the shape of terrain to know if there’s room for it to spawn. The game gets the column of blocks at the spot which means it has to run the density functions that determines the shape of the terrain for that spot

Sry to bother you again, the profiler was run in the overworld, but why the nether shipwreck structure is still using thread?

**Comment by TelepathicGrunt** [comment]
The nether could be loaded by another mod or whatever. If on server, I think servers loads all dimension spawn areas. Or a mod put a nether biome in overworld which triggers the checks for nether structure. Anyway, this isn’t impacting your game and isn’t really any concern. It’s only using 0.15% of the cpu on offthread from what spark is saying so it has having zero impact on the TPS.

**Comment by Rad586** [comment]
> The nether could be loaded by another mod or whatever. If on server, I think servers loads all dimension spawn areas. Or a mod put a nether biome in overworld which triggers the checks for nether structure. Anyway, this isn’t impacting your game and isn’t really any concern. It’s only using 0.15% of the cpu on offthread from what spark is saying so it has having zero impact on the TPS.

Okay, thanks!
