### ISSUE TITLE
Ocean dungeons have weird spawning, sea weed and kelp get stuck in the air, structures sometimes collide with eachother.

### ISSUE THREAD

**Issue by BugmanBugman** [TelepathicGrunt/RepurposedStructures#28]
![2020-10-09_10 50 57](https://user-images.githubusercontent.com/40730042/95664624-42ea5300-0b0f-11eb-85a3-509aff2f9924.png)
![2020-10-09_10 46 46](https://user-images.githubusercontent.com/40730042/95664626-44b41680-0b0f-11eb-8fca-3bca650d0cff.png)
![2020-10-09_10 47 41](https://user-images.githubusercontent.com/40730042/95664627-454cad00-0b0f-11eb-9b17-ed56ac6bd2ab.png)

**Comment by TelepathicGrunt** [comment]
The kelp, I'm not sure I can fix easily. For the chests, I could leave a block below them if a cave is removing the ground below it but that block will still be floating if the cave removed everything else around it lol. Probably no good way to fix this lol. Maybe a pillar of prismarine instead?

**Comment by TelepathicGrunt** [comment]
v2.2.10 should fix this! give it a shot and see if the ocean dungeons looks much better now :)
