### ISSUE TITLE
compatiblility with monobank mod

### ISSUE THREAD

**Issue by jojofenin99** [TelepathicGrunt/RepurposedStructures#280]
I was playing and I went into a village with repurposed structures and monobank installed, and in the village, the bank structure wasn't there so I wanted to know if there could be a datapack made so that the structure could be added to the repurposed villages.

**Comment by TelepathicGrunt** [comment]
I’ll make a note here on this dedicated page to tracking mod to do compat for

https://github.com/TelepathicGrunt/RepurposedStructures/issues/113


Though monobank isn’t very popular so it may not be worth the effort me to do the compat datapack with it. Unless some wants to make the datapack for me following how I do the other compat datapacks. I’ll revisit later if it gets more known
