### ISSUE TITLE
Ice and Fire updated, please update your Ice and Fire addon.

### ISSUE THREAD

**Issue by MagmaSlime123** [TelepathicGrunt/RepurposedStructures#281]

**Comment by TelepathicGrunt** [comment]
I already know. I have a life and doing other things so updating compat datapacks is very low in my priority. I think you’ll be fine waiting till I got free time

**Comment by TelepathicGrunt** [comment]
Actually they updated to 1.18.2 which I dropped support for. I’m only supporting 1.19.2+ at the moment and ice and fire did not update to 1.19.2 yet

**Comment by MagmaSlime123** [comment]
> Actually they updated to 1.18.2 which I dropped support for. I’m only supporting 1.19.2+ at the moment and ice and fire did not update to 1.19.2 yet

Well, 1.18.2 is in Beta for them.
