### ISSUE TITLE
Bug - cannot load tags/ missing references

### ISSUE THREAD

**Issue by Yourname942** [TelepathicGrunt/RepurposedStructures#282]
**Bug Description**
Cannot load tags and missing references

**Steps to Reproduce**
1. Open Curseforge app
2. Create a new profile
3. MC 1.19.2
4. Forge 43.2.11
5. Install JEI
6. Install MVS 3.2
7. launch the game
8. create a new world (creative/hard)
9. enter the world
10. close the game
_observe the errors in the log file_

MC 1.19.2
Forge 43.2.11
MVS 3.2
Repurposed Structures 6.3.24

**Latest log:** https://paste.ee/p/hFYBB

**Comment by TelepathicGrunt** [comment]
@Yourname942 hey, are you reading responses at all? I already mentioned to you here that this is not a bug on my side and rather just logspam by forge https://github.com/TelepathicGrunt/Bumblezone/issues/249

Load up the game and do /locate structure for the tags that the log said didn’t load. And you will find the tags do exist in game and function properly. The logspam is just some weird bug in forge that stopped occurring in 1.19.3+.

RS is using the exact same tags and json files on Fabric and it doesn’t get the logspam there. So there’s nothing wrong with my tag files. It’s just spam that you can ignore in forge as it has no gameplay impact

**Comment by Yourname942** [comment]
I see. Thank you
