### ISSUE TITLE
[1.19.2 forge] Problem with Better Desert Temples Compat Datapack

### ISSUE THREAD

**Issue by PineJamX** [TelepathicGrunt/RepurposedStructures#285]
Mod Loader : forge
Minecraft Version : 1.19.2
Repurposed Structures Version : 6.3.24
YUNG's Better Desert Temples Version : 2.2.2
Datapack Version : 7

Nether Pyramid is generated above Bedrock and looks strange.
The same thing seems to be happening in all worlds.
![2023-06-04_09 09 32](https://github.com/TelepathicGrunt/RepurposedStructures/assets/101681286/aa60b297-73d1-478f-a357-b364fb084a1d)
![2023-06-04_09 25 42](https://github.com/TelepathicGrunt/RepurposedStructures/assets/101681286/c68ed48d-c65d-412f-9120-a8c8af4fa8ac)

PS : The same thing seems to happen in Nether Ancient City without addons.

![2023-06-04_09 57 12](https://github.com/TelepathicGrunt/RepurposedStructures/assets/101681286/3098e96f-e658-4192-a048-a443cea93d7c)

**Comment by TelepathicGrunt** [comment]
I'm guessing you have a lot more mods on than RS and Yung because what you showed does not happen for me and no one else is reporting this issue. Which leads to me believing you have mods on in your pack that is adding terrain projection to the RS nether structures when it should not being doing so. Please share your full modpack for me to download and test with to narrow down who is breaking nether structures.

I even checked my structure JSON files. The nether pyramid and nether ancient city both do not have any projection settings and will spawn at a fixed y value of around 32.

My test here done with: 
- repurposed_structures_forge-6.3.24+1.19.2.jar
- YungsApi-1.19.2-Forge-3.8.9.jar
- YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar
- Repurposed_Structures-Better_Desert_Temples_v7.zip

![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/b87bfe25-36ee-44f1-a5b1-365ca52f65dc)
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/8f4448be-0ac4-4bbe-9505-161c452c1457)

**Comment by PineJamX** [comment]
I tried it in the specified environment and it was generated properly.
It seems that the abnormal generation was due to my environment. sorry.
![2023-06-05_15 12 47](https://github.com/TelepathicGrunt/RepurposedStructures/assets/101681286/c2e993c5-4b6f-4434-920e-dd54530f054b)
![2023-06-05_15 16 06](https://github.com/TelepathicGrunt/RepurposedStructures/assets/101681286/e870c01f-d14f-4e28-b967-336c9399c0f4)

**Comment by TelepathicGrunt** [comment]
If you cannot find the cause, you can share your modpack with me and I'll narrow it down to who is causing this

**Comment by PineJamX** [comment]
It is not a Modpack. I will put a list of mods I have installed.

<details>
<summary>mod list</summary>

- [Savage & Ravage (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/savage-and-ravage)
- [Integrated Dungeons and Structures (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/idas)
- [YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
- [Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
- [Jade Addons (Forge) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade-addons)
- [Cloud Storage (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-cloud-storage)
- [Ender's Delight (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/enders-delight)
- [L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
- [Create Slice & Dice (by possible_triangle)](https://www.curseforge.com/minecraft/mc-mods/slice-and-dice)
- [Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
- [Alex's Delight (by NCP_Bails)](https://www.curseforge.com/minecraft/mc-mods/alexs-delight)
- [Upgraded Netherite (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite)
- [Dynamic View[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/dynamic-view)
- [JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
- [YUNG's Bridges (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-bridges)
- [Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)
- [Nether's Delight (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
- [Additional Placements (by firemerald)](https://www.curseforge.com/minecraft/mc-mods/additional-placements)
- [Rotten Creatures (by fusionstudiomc)](https://www.curseforge.com/minecraft/mc-mods/rotten-creatures)
- [Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
- [Create Enchantment Industry (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
- [Illage and Spillage (by this_is_stupid123)](https://www.curseforge.com/minecraft/mc-mods/illage-and-spillage)
- [Polymorph (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
- [Upgraded Netherite : Items (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite-items)
- [Global Packs (by JTK222)](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack)
- [AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
- [Smooth Boot (Reloaded) (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded)
- [Just Enough Effect Descriptions (JEED) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed)
- [CorgiLib (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/corgilib)
- [Neko's Enchanted Books (by Nekomaster1000)](https://www.curseforge.com/minecraft/mc-mods/nekos-enchanted-books)
- [Ocean's Delight (by scouter567)](https://www.curseforge.com/minecraft/mc-mods/oceans-delight)
- [AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
- [YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
- [Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
- [The Conjurer (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/the-conjurer)
- [YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
- [Create Confectionery (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-confectionery)
- [Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
- [Traveler's Backpack (by Tiviacz1337)](https://www.curseforge.com/minecraft/mc-mods/travelers-backpack)
- [Oh The Biomes You'll Go (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
- [Repurposed Structures (Forge) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures)
- [Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
- [CoFH Core (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/cofh-core)
- [Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
- [Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
- [MmmMmmMmmMmm (Target Dummy) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm)
- [Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
- [GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
- [Max Health Fix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/max-health-fix)
- [Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
- [SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
- [Integrated Stronghold (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/integrated-stronghold)
- [Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
- [Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
- [Apotheosis (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
- [Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
- [Delightful (by brnbrd)](https://www.curseforge.com/minecraft/mc-mods/delightful)
- [FastSuite (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastsuite)
- [Upgraded Core (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-core)
- [Every Compat (Wood Good) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/every-compat)
- [Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
- [Configured (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured)
- [Chef's Delight [Forge] (by redstone3game)](https://www.curseforge.com/minecraft/mc-mods/chefs-delight-forge)
- [FastFurnace (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastfurnace)
- [Simple Magnets (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/simple-magnets)
- [Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
- [YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
- [YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
- [Shutup Experimental Settings! (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/shutup-experimental-settings)
- [Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
- [TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
- [Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
- [Explorer's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/explorers-compass)
- [Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
- [Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
- [JER Integration (by AlasDiablo)](https://www.curseforge.com/minecraft/mc-mods/jer-integration)
- [YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts)
- [Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
- [Create: Crystal Clear (by singularity_cyvack)](https://www.curseforge.com/minecraft/mc-mods/create-crystal-clear)
- [Create Jetpack (by possible_triangle)](https://www.curseforge.com/minecraft/mc-mods/create-jetpack)
- [Create Encased (by iglee42)](https://www.curseforge.com/minecraft/mc-mods/create-encased)
- [Integrated API (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/integrated-api)
- [Create: Edible Belts (by Halogen)](https://www.curseforge.com/minecraft/mc-mods/create-edible-belts)
- [Amplified Nether (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/amplified-nether)
- [Upgraded Netherite : Ultimerite (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite-ultimerite)
- [YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
- [FastWorkbench (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)
- [SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
- [Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
- [Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
- [Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
- [Enchant With Mob (by bagu_chan500)](https://www.curseforge.com/minecraft/mc-mods/enchant-with-mob)
- [Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
- [Ensorcellation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/ensorcellation)
- [Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
- [FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
- [Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
- [Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
- [YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
- [Domestication Innovation (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/domestication-innovation)
- [Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
</details>

**Comment by TelepathicGrunt** [comment]
Putting mods together creates a modpack. Normally mod launcher have a way to export your modpack into a zipped file that can be shared with others (by Dropbox or Google drive with sharing on for the file)

what mod launcher do you use? CurseForge launcher, GDLauncher, Prism? I might be able to help you find the export button. Otherwise, it’ll take me quite a bit to download all the mods myself individually

**Comment by PineJamX** [comment]
This is the modpack file. Launcher is CurseForge
[Create.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/11652801/Create.zip)

(For the current playthrough, Better Desert Temples Compat Datapack in this file has had the Nether portion removed, so please replace it with the original version. Additionally, I have raised the ceiling on the Nether with Amplified Nether.)

**Comment by TelepathicGrunt** [comment]
Found it. it is the Quark compat data Repurposed_Structures_Quark_Compat.zip by badooga. They did state that their alterations to the structures was specifically for amplified nether.
https://modrinth.com/datapack/repurposed-structures-quark+-compat

This includes spawning the nether ancient city at y = 132 so you can edit the datapack to change that to 32. Desired result: https://github.com/TelepathicGrunt/RepurposedStructures/blob/969e43f93595591c78d2db2d2aa465d6bcf8b2ce/src/main/resources/data/repurposed_structures/worldgen/structure/ancient_city_nether.json#L9

The nether pyramid is weird and the start height here is an issue. Start height should be -2
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/67d456b3-5ec1-4242-880f-b1dd8b91ba4f)
https://github.com/TelepathicGrunt/RepurposedStructures/blob/969e43f93595591c78d2db2d2aa465d6bcf8b2ce/src/main/resources/data/repurposed_structures/worldgen/structure/pyramid_nether.json#L11

**Comment by badooga** [comment]
Sorry for the headaches, I included some personal changes in the datapack based on the Amplified Nether and Nullscape mods that I use, which resulted in this issue. I just updated the mod to remove these changes altogether so that there aren't any further compatibility issues:

https://modrinth.com/datapack/repurposed-structures-quark+-compat/version/1.0.1
