### ISSUE TITLE
Repurposed Structures Savage&Ravage compat BUG!!!

### ISSUE THREAD

**Issue by MrJorman** [TelepathicGrunt/RepurposedStructures#287]
I found bug! In structure Pillager Outpost one chest is not marked by Lootr mod storage.

**Comment by TelepathicGrunt** [comment]
Wouldn’t this be more of a bug on lootr’s side? I don’t do anything that can break lootr and lootr is supposed to work with all structures. You’ll have to show them along with a minimum reproduction case and locate command to the offending structure so they can investigate
