### ISSUE TITLE
crash in All The Mods 8

### ISSUE THREAD

**Issue by pibblepower** [TelepathicGrunt/RepurposedStructures#289]
hey, I'm currently playing on a modified ATM 8 modpack, and I'm currently crashing due to a "feature placement" bug, and it seems that this mod (or better ocean monunmets) is responsible. If it means anything, I have all the repurposed structures datapacks. anyway, here's the crash report.
[crash-2023-06-14_00.06.04-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/11750667/crash-2023-06-14_00.06.04-server.txt)

**Comment by TelepathicGrunt** [comment]
This is crashing due to:  ResourceKey[minecraft:worldgen/structure / ctov:small/village_desert]
That is ChoiceTheorem's Overhauled Village mod.

They have a jigsaw block somewhere with a typo of minecraft:smoooth_sandstone_stairs instead of minecraft:smooth_sandstone_stairs

**Comment by TelepathicGrunt** [comment]
@pibblepower Looks like they already fixed that bug but ATM8 hasn't updated the mod or you didn't update ATM8 to latest.
https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/issues/33

If you update the mod, you should be good to go
