### ISSUE TITLE
empty loot tables / loot

### ISSUE THREAD

**Issue by GitJhopa** [TelepathicGrunt/RepurposedStructures#292]
empty shulkers in /locate structure repurposed_structures:outpost_end
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/86250668/5f5c3fa6-74f3-41c1-a160-9ee6959656be)
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/86250668/75ea00eb-c7db-4211-bda4-55cb3177e7e5)
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/86250668/cd788492-7f27-4606-9fee-68f74dfcbf83)
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/86250668/dfa4c9d8-f714-4749-87ef-4f8e34077fd3)

**Comment by GitJhopa** [comment]
Forge 1.19.2

**Comment by TelepathicGrunt** [comment]
v6 of the compat datapack is now uploaded with corrected loot table names in the shulker boxes
