### ISSUE TITLE
No version marked to be compatible with 1.20.1 (Modrinth)

### ISSUE THREAD

**Issue by MbtMarco** [TelepathicGrunt/RepurposedStructures#293]
<img width="1261" alt="Screenshot 2023-07-30 alle 21 56 51" src="https://github.com/TelepathicGrunt/RepurposedStructures/assets/124934175/700e1d82-59c4-43d6-aa58-71a0bc77bcf3">

**Comment by TelepathicGrunt** [comment]
Fixed

**Comment by MbtMarco** [comment]
Ty :)
