### ISSUE TITLE
[Help Wanted] How to properly replace villages?

### ISSUE THREAD

**Issue by Cixon** [TelepathicGrunt/RepurposedStructures#298]
### 1.20.1 - Forge

_FML: 47.1.3_

datapack:
[Structure.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/12479551/Structure.zip)

Village Expected Results:
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/69068153/7deafdfc-b961-4d4b-9ea5-871162bc8f5c)

What occurred:
![Screenshot (63)](https://github.com/TelepathicGrunt/RepurposedStructures/assets/69068153/8530b140-370c-4e79-85fa-d904d49607fc)

**Comment by TelepathicGrunt** [comment]
You’re going to need to set the street template pools entries to rigid. Not terrain matching. Then replace start piece to be like a treehouse or stairs to the height you want. The rigid streets will then stay at that height and spawn houses to side at that height. The treehouses on side of roads will need to have jigsaw block where you want the street to connect to house entrance. 

Treehouse villages are tricky and might interact strangely with terrain. With terrain adaption on, the land around the village will be flat once all streets are rigid

**Comment by TelepathicGrunt** [comment]
closing since this isn't an actual issue with RS. Just helping to give advice. You can ask for more help on my discord server if needed or reply to this issue report while keeping the issue report closed. https://discord.gg/K8qRev3yKZ
