### ISSUE TITLE
An issue for 1.16.3 when used with YUNG's Better Mineshafts involving server crashing/timed out

### ISSUE THREAD

**Issue by DanielPikaman** [TelepathicGrunt/RepurposedStructures#30]
So there was a certain area in the new world on my server that would cause me to time out and essentially crash the server after a few seconds upon being entered.

After some experimenting by removing some mods and recreating the world with the same seed, I figured out that this problem occurred only when YUNG's Better Mineshafts and Repurposed Structures were both installed. Upon further investigation using spectator mode, I saw that underground there was both a YUNG's mineshaft and an ice-themed mineshaft from Repurposed structures. I don't really know any technical stuff, but I'm guessing that both of these different types of modded mineshafts must somehow be interfering with each other and causing the player to time out. An interesting thing to note is that it only seemed to do this on a server for me, and not in singleplayer. When it happens, the server's memory use peaks and stays at a high level, times me out, but never fully crashes and thus doesn't create a crash report or any error messages in the console.

**Comment by TelepathicGrunt** [comment]
While there's no crash report, there should always be a latest.log file made. You can get it from the server's log folder which is next to the mods folder. Put it here and I can check out if there's any clue as to what is going on. 

I'll also test tomorrow myself to see if I can reproduce the issue

**Comment by DanielPikaman** [comment]
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/5406106/latest.log)
So I tried going to that area again without YUNG's Better Mineshafts, but this time it didn't work and I timed out again, so I was wrong about YUNG's Better Mineshafts being the problem, and it might not have anything to do with repurposed structures at all. Maybe you can help me figure this out anyway?

**Comment by DanielPikaman** [comment]
Ok so it still happens without repurposed structures, so this issue is irrelevant. I'll probably keep removing more mods until I figure out which one is causing it.

**Comment by TelepathicGrunt** [comment]
Ouch. Good luck tho! If you find the issue, I would be curious as to what mod was causing the issue

**Comment by DanielPikaman** [comment]
It ended up being Ice and Fire that caused the problem. It seems to be a problem with just that mod, and not an incompatibility with any other mod.

**Comment by DanielPikaman** [comment]
The only other mod I had installed in my latest test was Biomes O' Plenty so that I could use the same world type for the seed.
