### ISSUE TITLE
1.19.2 Fabric missing trace to moonlightlib/moonlight

### ISSUE THREAD

**Issue by LadyValishade** [TelepathicGrunt/RepurposedStructures#302]
>>>Repurposed Strures refuses to launch with moonlight lib which seems the filename is just called moonlight now. 

error code:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install midnightlib, version 0.5.2 or later.
Unmet dependency listing:
	 - Mod 'Repurposed Structures' (repurposed_structures) 6.3.26+1.19.2 requires version 0.5.2 or later of midnightlib, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

>>>i have moonlight lib already installed. but maybe it's a renamed issue. where repurposed stuctures is looking for the mod that is there but it's just a different filename now? im honestly not sure. and was wondering if this is just a me thing

**Comment by TelepathicGrunt** [comment]
> Mod 'Repurposed Structures' (repurposed_structures) 6.3.26+1.19.2 requires version 0.5.2 or later of midnightlib,

The dependency my mod needs is Midnightlib. Not Moonlight lib. I can see how one can be confused but they are two completely different dependencies 

Here's the midnightlib mod page
https://www.curseforge.com/minecraft/mc-mods/midnightlib

**Comment by LadyValishade** [comment]
oh well apparently i can't read. sorry for the trouble lol
