### ISSUE TITLE
create's power supply missing when using RS and yungs better jungle temple

### ISSUE THREAD

**Issue by liangmoe** [TelepathicGrunt/RepurposedStructures#305]
fabric 1.19.2 
create 0.5.1c
![Base Profile Screenshot 2023 10 07 - 11 54 34 08](https://github.com/TelepathicGrunt/RepurposedStructures/assets/135343248/f8dcd067-ade4-43d2-9c2d-f3932167a75b)
![Base Profile Screenshot 2023 10 07 - 11 45 28 06](https://github.com/TelepathicGrunt/RepurposedStructures/assets/135343248/21456fe3-55b6-4b61-bbfc-94c08e691bae)
![Base Profile Screenshot 2023 10 07 - 11 45 46 82](https://github.com/TelepathicGrunt/RepurposedStructures/assets/135343248/37878879-1edc-496d-9060-9776c541ac0b)
![Base Profile Screenshot 2023 10 07 - 11 45 57 52](https://github.com/TelepathicGrunt/RepurposedStructures/assets/135343248/16384282-d5e4-4daf-9150-beee8759c8e3)
![Base Profile Screenshot 2023 10 07 - 11 54 14 66](https://github.com/TelepathicGrunt/RepurposedStructures/assets/135343248/a5f53026-c213-49db-a3f0-82f88b04f104)
![Base Profile Screenshot 2023 10 07 - 11 54 26 16](https://github.com/TelepathicGrunt/RepurposedStructures/assets/135343248/d886a058-f1c2-4381-82b7-20b34b7280ce)

**Comment by TelepathicGrunt** [comment]
fixed

**Comment by liangmoe** [comment]
i still found some missing lava from the warped one, other then that seems fine
![Base Profile Screenshot 2023 10 08 - 00 40 05 32](https://github.com/TelepathicGrunt/RepurposedStructures/assets/135343248/56ccbe42-b2e4-4d5a-91bf-524b43e820bd)
![Base Profile Screenshot 2023 10 08 - 00 40 10 19](https://github.com/TelepathicGrunt/RepurposedStructures/assets/135343248/fd77ac15-c187-4623-b010-4706f542b05f)
![Base Profile Screenshot 2023 10 08 - 00 39 11 81](https://github.com/TelepathicGrunt/RepurposedStructures/assets/135343248/317049cf-c1fc-40b3-af71-357ad05c8d61)
![Base Profile Screenshot 2023 10 08 - 00 39 19 97](https://github.com/TelepathicGrunt/RepurposedStructures/assets/135343248/7f030e74-43c3-493f-9ee3-5e4f1a13d2e9)

**Comment by TelepathicGrunt** [comment]
fixed now. Warped temple was missing a processor entry to turn dead coral to lava
