### ISSUE TITLE
Villagers plus and Repurposed Structures generating warning

### ISSUE THREAD

**Issue by esvarc** [TelepathicGrunt/RepurposedStructures#310]
Minecraft V.120.1
RS repurposed_structures-7.1.7+1.20.1-forge.jar
Forge forge-1.20.1-47.2.0-installer.jar
Villagers+ villagersplus_3.0_(forge)_for_1.20.1.jar

latest.log contains flood of:

```
[co.te.re.RepurposedStructures/]: Repurposed Structures: Non-existent child pool attempted to be spawned: minecraft: which is being called from villagersplus:villages/bamboo/horticulturist. Let Repurposed Structures dev (TelepathicGrunt) know about this log entry.
```

**Comment by esvarc** [comment]
I'm using datapack as well:

repurposed_structures-villagersplus_v2.zip https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-villagerplus-compat-datapack

**Comment by TelepathicGrunt** [comment]
Fixed in v3. horticulturist  villager wasn't spawning was the issue
