### ISSUE TITLE
Crashes every time this chest is opened

### ISSUE THREAD

**Issue by lumagatto** [TelepathicGrunt/RepurposedStructures#311]
When opening any chest with this loot table:
repurposed_structures:chests/dungeons/deep.
Haven't tested with other loot tables from the mod yet.

[crash-2023-11-14_23.16.57-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/13357883/crash-2023-11-14_23.16.57-server.txt)

**Comment by TelepathicGrunt** [comment]
@DDZiroWan Repurposed Structures is not made for 1.20.2. You're trying to run the mod on a minecraft version it was not made for and so, it'll crash when it reaches a 1.20.2 class/method/field that did not exist back in 1.20.1. You will have to wait for me to update the mod

**Comment by lumagatto** [comment]
Thank you for the quick response, could you by chance give an estimate for when you're gonna update?

**Comment by TelepathicGrunt** [comment]
Whenever neoforge merged in their registry refactor and caps refactor. Then I’ll port all my mods to neoforge and fabric 1.20.2 together

**Comment by TelepathicGrunt** [comment]
Repurposed structures is now out for 1.20.2

**Comment by lumagatto** [comment]
Thank you
