### ISSUE TITLE
Server crashed while entering the nether

### ISSUE THREAD

**Issue by KelvinZhang512** [TelepathicGrunt/RepurposedStructures#314]
My server crashed just after I entered the nether and the crash reports and logs are here.
[crash.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/13533621/crash.log)
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/13533622/latest.log)

**Comment by TelepathicGrunt** [comment]
Did you create any config datapack for repurposed Structures? If so, remove it and try again.

**Comment by KelvinZhang512** [comment]
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/48343945/3930f8df-233f-4832-a1b8-13a3244cc624)
These are all the datapacks and the server's fine after removing all of them and the nether dimension, thx for helping out!

**Comment by TelepathicGrunt** [comment]
Hmm… reopening as one of them probably has a structure set that needs to be fixed. Two structures are trying to avoid each other and got locked up

**Comment by TelepathicGrunt** [comment]
Fairly certain the issue is the better jungle temple datapack. Uploading a fixed version now

**Comment by TelepathicGrunt** [comment]
v5 of that datapack should fix the issue.

https://modrinth.com/datapack/repurposed-structures-better-jungle-temples/version/5

https://legacy.curseforge.com/minecraft/texture-packs/repurposed-structures-better-jungle-temples-compat/files/4919783
