### ISSUE TITLE
1.19.2 - Modpack Pregen Crash

### ISSUE THREAD

**Issue by Serimah** [TelepathicGrunt/RepurposedStructures#316]
First and foremost, I hope I did not miss any resolution to this Issue from closed Issues...

While doing Pregen on Overworld in the Modpack "Fear - Nightfall" (using 1.19.2) it will repeatedly crash when trying to generate the same Region over and over.
I have tried fresh Maps, different Seeds... but eventually it will hit a point where it will crash over and over.

I did try talking to the Modpack Developers which then re-routed me to asking here.
Is there anything I can do to remedee this?
[crash-2023-12-29_06.52.01-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/13797375/crash-2023-12-29_06.52.01-server.txt)
[crash-2023-12-29_15.06.51-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/13797376/crash-2023-12-29_15.06.51-server.txt)

**Comment by TelepathicGrunt** [comment]
Can you please give me the seed of the world you're trying to pregen? I'll check if pack had edited the structure avoid tags as if they did, it can cause an infinite loop like this

**Comment by TelepathicGrunt** [comment]
Also, try updating the Repurposed Structures - Better Jungle Temple Compat Datapack in `Fear Nightfall\defaultconfigs\paxi\datapacks` to v1.3 and see if that makes issue go away
https://legacy.curseforge.com/minecraft/texture-packs/repurposed-structures-better-jungle-temples-compat/files/4919775

**Comment by Serimah** [comment]
Hello again and thank you for your Reply!
I updated the Datapack as you suggested, unfortunately it would keep crashing nontheless.

As requested, here is the World Seed.
Seed: 8282346177423030437

I also added the most recent Crashlog, just in case it is needed.
[crash-2023-12-31_01.02.28-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/13800397/crash-2023-12-31_01.02.28-server.txt)

**Comment by TelepathicGrunt** [comment]
When you can, reproduce the issue with this jar file instead. Then give me the latest.log file. Not the crashlog file. Latets.log. This jar will print out the structure sets it is trying to avoid which should help me know exactly which structure sets are looping with each other

(Unzip this file to get the jar file)
[repurposed_structures_forge-6.3.28-test+1.19.2.jar.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/13802068/repurposed_structures_forge-6.3.28-test%2B1.19.2.jar.zip)

**Comment by Serimah** [comment]
Alright, here is the latest.log as requested using the provided Jar.

[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/13802250/latest.log)

**Comment by TelepathicGrunt** [comment]
Are you absolutely positive that you removed Repurposed_Structures-Better_Jungle_Temples_v1_2.zip datapack and put on Repurposed_Structures-Better_Jungle_Temples_v1_3.zip? The log shows the cycle between the Nether Shipwrecks, Nether Temples, and Nether City. This cycle is specifically what I fixed in v1.3 of the datapack.

![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/66a6e34d-3fd2-4532-94e9-cf389a70b2d4)

 I even opened it up and verified that the datapack overrides the Nether Shipwreck Avoids tag so that shipwrecks won't cause the temples to start checking. Thus killing there cycle there. The log still shows the shipwreck -> temple connection which tells me that v1.2 better temples compat data is still running in your game

**Comment by Serimah** [comment]
I am honestly not sure how this came to be, surely this should be correct?
![datapack](https://github.com/TelepathicGrunt/RepurposedStructures/assets/123443596/e6d3de9d-dd18-4386-9211-df4da692e00e)
![mods](https://github.com/TelepathicGrunt/RepurposedStructures/assets/123443596/7d4bb920-3e8b-4520-aa6a-49038420d2ea)

**Comment by TelepathicGrunt** [comment]
Is there any other datapack loading system in the modpack? Like global packs or open loader. And make sure once datapack is on, the server/game is shut down and then started back up for new datapack to apply. 

You can try also the /datapack command in game to see all datapacks active and see if you can find 1.2 and disable that pack in the game. (And then close and restart game to have changes take effect)

**Comment by TelepathicGrunt** [comment]
To be clear, if running a server, the datapack has to be put on server. It won’t do anything clientsided unless playing singleplayer.

**Comment by Serimah** [comment]
Hi there, I won't be home until noon tomorrow (CET)..
I'll make sure to triple-check all Data/retry the Pregen for this Seed from Scratch as soon as I am home. 

Thank you :)

**Comment by Serimah** [comment]
Alright, so I did get one more attempt in.
Made an entirely new Map (same Seed) and teleported myself to the previously affected Area which caused Crashes.
I made sure that all Files provided by you, are in their designated Folders.

[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/13804731/latest.log)

**Comment by TelepathicGrunt** [comment]
I just did a search in the modpack and there's two paxi folders with the broken datapack. Be sure to get the defaultconfigs folder as well alongside the config folder. That might be the issue 
![image](https://github.com/TelepathicGrunt/RepurposedStructures/assets/40846040/87ec764f-6e36-4e08-a07f-dbdf1ffaf461)

**Comment by Serimah** [comment]
That might have actually been it!
I switched out the broken Datapack in both Folders and the Pregen has moved past/finished the previously affected Region.

Thank you so much!

**Comment by Serimah** [comment]
Nevermind.. it crashed again. 
[crash-2024-01-01_10.37.27-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/13805144/crash-2024-01-01_10.37.27-server.txt)
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/13805145/latest.log)

**Comment by TelepathicGrunt** [comment]
Idk what else to tell you. It is still showing the cycle crash that was in v1.2 of the datapack. You can try deleting the better temple compat datapacks from both spots entirely but if it still crashes even without the compat datapacks, then there's some other place in this modpack that has the datapack that i don't know of. There isn't much more I can do here.

I even tried pregenning originally with same seed and couldn't get the issue to happen myself.

**Comment by TelepathicGrunt** [comment]
Wait I checked again, the tag I used was supposed to be replace = true but it is false. Hang on

**Comment by TelepathicGrunt** [comment]
Apologies, try this datapack and hopefully that will be the last we ever see of this issue. The tags are set to have replace be true which should *properly* kill the cycle. Though this does make me wonder how the last report of this issue a while ago was said to be resolved by the player when the tags weren't working properly....
[Repurposed_Structures-Better_Jungle_Temples_v1_4.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/13805198/Repurposed_Structures-Better_Jungle_Temples_v1_4.zip)

**Comment by Serimah** [comment]
It is generating nicely, you love to see it. 
I figure I'll reply one more time in 1-2 hours with a final Status and this entire thing can finally be brought to a close.

Thank you so much for taking the time to figure this out. Not sure why previous Reports declared it as solved... but alas we got there in the end :)

**Comment by Serimah** [comment]
It's now been well over an hour, it's all running smoothly.
Thank you so much!

**Comment by TelepathicGrunt** [comment]
Fixed datapacks are now released
