### ISSUE TITLE
Why are there two datapacks for Repurposed Structures Friends & Foes Compatibility Datapack on Curseforge?

### ISSUE THREAD

**Issue by DarthCaesium** [TelepathicGrunt/RepurposedStructures#319]
Which datapack is the correct one, and why are there two? Genuinely wondering.

**Comment by TelepathicGrunt** [comment]
One is a true datapack. The other is a mod form of the datapack and will load in the mods folder. Use whichever one you want

**Comment by TelepathicGrunt** [comment]
This is the actual datapack and goes into datapack folder or is loaded by another mod:
https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-friends-and-foes-datapack

This one is the mod form and will load from mods folder:
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-friends-and-foes-compat-mod

The mod form is what I am moving to for 1.20.4+ for all my datapacks
