### ISSUE TITLE
Request for Version 1.20.1

### ISSUE THREAD

**Issue by Nate4Fate** [TelepathicGrunt/RepurposedStructures#322]
If possible, a version for 1.20.1 (using a modpack)

**Comment by TelepathicGrunt** [comment]
What do you mean? Repurposed structures is already released for 1.20.1

**Comment by TelepathicGrunt** [comment]
1.20.1: https://www.curseforge.com/minecraft/mc-mods/repurposed-structures/files/4823487

**Comment by Nate4Fate** [comment]
Sorry, I meant for Fabric, that's my bad

**Comment by TelepathicGrunt** [comment]
It’s already on 1.20.1 fabric: https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric/files/4823484

**Comment by Nate4Fate** [comment]
Thank you!
