### ISSUE TITLE
Required pieces failed to generate

### ISSUE THREAD

**Issue by purejosh** [TelepathicGrunt/RepurposedStructures#323]
Triple checked, the end city style structure generated just fine in the overworld, and went as high as y170. Don't see any generation issues with it, but...

```
Repurposed Structures: Failed to create valid structure with all required pieces starting from this pool file: repurposed_structures:cities/overworld/start_pool. Required pieces failed to generate the required amount are: [repurposed_structures:cities/overworld/fat_tower_top=1]
  This can happen if a structure has a required piece but the structure size is set too low.
  However, this is most likely caused by a structure unable to spawn properly due to hitting the world's min y or max y build thresholds or a broken RS datapack.
  Try teleporting to: class_2338{x=439, y=110, z=631} and see if the structure generated fine with the required structure piece or if it is indeed missing it.
  Please report the issue to Repurposed Structures's dev with latest.log file if the structure is not cut off by world min/max y build thresholds.
```

**Comment by TelepathicGrunt** [comment]
The structure tried finding a piece layout that had all the required pieces but failed. So it spawned the last piece layout it made.

I would need seed, coordinates, and modpack to investigate further. If the structure is too high close to world build height, there may not be enough room for all the required pieces to fit

**Comment by TelepathicGrunt** [comment]
Closing as no new info

**Comment by purejosh** [comment]
Sorry, I forgot to reply. It's honestly not an issue to me, and as long as you're not too concerned, I don't see a reason to keep this ticket open.
