### ISSUE TITLE
All (tested) datapacks crash alongside latest Blueprint

### ISSUE THREAD

**Issue by brnbrd** [TelepathicGrunt/RepurposedStructures#324]
I am getting a crash upon world creation with:
- Forge 47.2.20 (1.20.1)
- Repurposed Structures 7.1.11+1.20.1-forge
- Blueprint 7.0.1
- Any pre-made datapack (tested with Immersive Engineering, Farmer's Delight, Friends and Foes, More Villagers, Sawmill)

https://pastebin.com/RTH4VZuU

**Comment by TelepathicGrunt** [comment]
It looks like blueprint is replacing a resource manager. May be better to ask them what they are doing

**Comment by TelepathicGrunt** [comment]
fixed now
