### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by MrHimera** [TelepathicGrunt/RepurposedStructures#326]
Minecraft: 1.20.1
Forge: 47.2.20
Repurposed Structures: v7.1.12

Crash on startup.
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/14467162/latest.log)

**Comment by Krimatoria** [comment]
Yes, me too) Forge: 47.2.6

https://gist.github.com/Krimatoria/7cfaed9f90596bf57ac140b47bc23ec3#file-structure

**Comment by TelepathicGrunt** [comment]
It's fix now. I don't even know why it broke randomly on build but rebuilding after updating some toolchain worked
