### ISSUE TITLE
1.20.1 Forge

### ISSUE THREAD

**Issue by Krimatoria** [TelepathicGrunt/RepurposedStructures#327]
Repurposed_structures-7.1.13+1.20.1-forge.jar

> [02Mar2024 19:28:32.345] [Server thread/ERROR] [com.telepathicgrunt.repurposedstructures.RepurposedStructures/]: (Repurposed Structures POOL MERGER) Failed to parse repurposed_structures:witch_huts/mangrove_start_pool additions file. Error is: Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]; Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]; Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]
> [02Mar2024 19:28:32.401] [Server thread/ERROR] [com.telepathicgrunt.repurposedstructures.RepurposedStructures/]: (Repurposed Structures POOL MERGER) Failed to parse repurposed_structures:witch_huts/giant_tree_taiga_start_pool additions file. Error is: Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]; Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]; Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]
> [02Mar2024 19:28:32.436] [Server thread/ERROR] [com.telepathicgrunt.repurposedstructures.RepurposedStructures/]: (Repurposed Structures POOL MERGER) Failed to parse repurposed_structures:witch_huts/oak_start_pool additions file. Error is: Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]; Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]; Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]
> [02Mar2024 19:28:32.480] [Server thread/ERROR] [com.telepathicgrunt.repurposedstructures.RepurposedStructures/]: (Repurposed Structures POOL MERGER) Failed to parse repurposed_structures:witch_huts/dark_forest_start_pool additions file. Error is: Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]; Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]; Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]
> [02Mar2024 19:28:32.487] [Server thread/ERROR] [com.telepathicgrunt.repurposedstructures.RepurposedStructures/]: (Repurposed Structures POOL MERGER) Failed to parse repurposed_structures:witch_huts/taiga_start_pool additions file. Error is: Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]; Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]; Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]
> [02Mar2024 19:28:32.524] [Server thread/ERROR] [com.telepathicgrunt.repurposedstructures.RepurposedStructures/]: (Repurposed Structures POOL MERGER) Failed to parse repurposed_structures:witch_huts/birch_start_pool additions file. Error is: Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]; Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]; Failed to get element ResourceKey[minecraft:worldgen/processor_list / hexerei:witch_hut/witch_hut_legs]
>

**Comment by TelepathicGrunt** [comment]
Hexerei is not on 1.20.1. Please remove the repurposed structures - hexerei compat datapack

**Comment by Krimatoria** [comment]
> Hexerei нет на 1.20.1. Пожалуйста, удалите перепрофилированные структуры - пакет данных hexerei compat.

And yes, exactly) it's sad that they are not ported((
