### ISSUE TITLE
The compatibility datapacks results in server not starting.

### ISSUE THREAD

**Issue by ghost** [TelepathicGrunt/RepurposedStructures#328]
"Errors in element repurposed_structures:decor/flower_forest_pyramid_structure_flowers:
[12.03 18:18:50] [Server] java.lang.IllegalStateExceptionFailed to parse repurposed_structures:worldgen/configured_feature/decor/flower_forest_pyramid_structure_flowers.json from pack file/Repurposed_Structures-Better_Desert_Temples_v8.zip"

This pops up in the console before getting stuck and not start at all. I am on 1.20.1 Fabric and using BisectHosting. I have installed RS and the Yung's Better Desert Temple along with all other Yung's better structure mods and compatibility datapacks, along with Bountiful and Villager Plus.

![image_2024-03-12_142826625](https://github.com/TelepathicGrunt/RepurposedStructures/assets/147958672/fda3e3fa-541f-4f15-aef7-48642eb101a3)

**Comment by TelepathicGrunt** [comment]
I’m guessing repurposed structures or yung’s better desert temple wasn’t on? Or did you edit the datapack?

**Comment by ghost** [comment]
I checked more thoroughly and turns out it was more than the Repurposed Structure Pyramid compatibility datapack. I will post the full server mod list and the console log.

**Comment by ghost** [comment]
**Mods**
- 2mal3's Recipe
- Additional Structures
- Areas
- Async Locator
- Balm
- Blossom Back
- Blossom Enderchest
- Blossom Homes
- Blossom Lib
- Blossom PvP
- Blossom TPA
- Blossom Warps
- C2ME
- Chunky
- Chunky Border
- Clumps
- Collective
- Cupboard
- CustomPlayerModels
- DarkRewards
- DarkSmithing
- DarkTimer
- Dismount Entity
- Double Doors
- FallingTree
- Ferritecore
- Fish on the line
- Flower Mimics
- Followers Teleport Too
- Forgiving World
- Giant Spawn
- Gotta Go Fast
- Infinite Trading
- Inventory Totem
- Keep Some Inventory
- Krypton
- Limited Chunks
- Lithium
- Log Protection
- Midnight Lib
- More Mobs
- Naturally Charged Creepers
- Noisium
- Random Village Names
- Recipe Cooldown
- Repurposed Structures
- Respawning Shulkers
- Slimyfloor
- Smooth Chunk
- Spawn Animations
- Vanilla Refresh
- Villager Names
- Village Spawn Point
- Weaker Spider Webs
- Yungs API
- Yungs Better Desert Temples
- Yungs Better Dungeons
- Yungs Better End Island
- Yungs Jungle Temples
- Yungs Better Nether Fortresses
- Yungs Better Ocean Monuments
- Yungs Better Strongholds
- Yungs Better Witch Huts
- Yungs Bridges
- Yungs Extras
- Alloy Forgery
- Attribute Fix
- Bendy Lib
- BetterCombat
- Bountiful
- Cardinal Components API
- Cloth Config
- Coro Utility (forgot the name)
- Fabric API
- Fabric Language Kotlin
- Fabric Seasons
- Friends and Foes
- GeckoLib
- Grapple Mod Restitched
- Kambril
- MC Dungeon Armor
- MC Dungeon Artifact
- MC Dungeon Enchanting
- MC Dungeon Weapon
- Moonlight
- Mythic Metals
- owolib
- Player Animation Lib
- Puffish Skills
- Randomium
- Soulslike Weaponry
- Trade Cycling
- Travelers Backpack
- Villagers Plus
- What Are They Up To
- Inventory Sorter
- Project Save the Pets
- Starter Kit

**Datapack**
- Better End City Vanilla
- Blaze and Cave's Advancements
- CraftableLights
- Repurposed Structures Better Desert Temple Compat
- Repurposed Structures Better Dungeon Compat
- Repurposed Structures Better Jungle Temple Compat
- Repurposed Structures Better Monument Compat
- Repurposed Structures Better Nether Fortress Compat
- Repurposed Structures Better Stronghold Compat
- Repurposed Structures Better Witch Hut Compat
- Repurposed Structures Bountiful Compat
- Repurposed Structures Friends and Foes Compat
- Repurposed Structures Villagers Plus Compat

[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/14579274/latest.log)

**Comment by ghost** [comment]
The max RAM on my BisectHosting server is 4 GB if that matters.

**Comment by ghost** [comment]
Turns out I accidentally downloaded the Quilt version of RS instead of Fabric, sorry.
