### ISSUE TITLE
Forge clients without Repurposed Structures cannot connect to Servers with the mod. Vanilla clients can connect just fine.

### ISSUE THREAD

**Issue by Dealman** [TelepathicGrunt/RepurposedStructures#33]
Been working on setting up a relatively simple server for my partner, on 1.16.3 - using the latest Forge as of writing _(34.1.35)_. Seems like the world's generated just fine, but was unable to join the server with this mod present.

Worlds generated fine with no errors, however it was my understanding that this was a server-side mod.

We had some issues trying to connect where we'd get stuck on Encrypting, and the client would eventually freeze - force kill necessary.

Turns out, the client does in fact need the mod to be able to join. Thought I'd post this as a rather minor bug, alternatively need of description polish on the mod page. 😃

**Comment by TelepathicGrunt** [comment]
I had been able to launch a modded server and had a vanilla client work on it and people in comments had talked about translation issues for advancements due to vanilla clients not having the en_us.json file so it should be allowing vanilla clients. But I have strong suspicion of what is going on now and I realllly hope I am wrong.

Can you downgrade to 34.1.25 Forge and downgrade repurposed structures to V.2.2.9? Then see if vanilla clients can connect. Let me know the result as this important to confirm my theory or debunk it

**Comment by Dealman** [comment]
Sorry for the delay, I've now set it up and did some quick testing.

**Server:** MC Forge 34.1.25 + Repurposed Structures V2.2.9, no world generation errors
**Client:** MC Forge 34.1.25 - No Mods

Only things I can spot are some warnings about Repurposed_Structures having incorrect config files, but I'm assuming that's because they hadn't been generated yet.

Upon the client trying to join the server they are met with the following error message;
"`Failed to synchronize registry data from server, closing connection"`

I think I've found what the issue was, though. The client had Forge installed, upon the client uninstalling Forge - they are able to connect. 👍

**Comment by TelepathicGrunt** [comment]
Ok so this appears to be a forge bug. They marked the biome and feature registries as needing to always be synced when in reality, minecraft will sync worldgen registries for us. So right now, have the client either not use forge when connecting or have my mod on when connecting. I'll poke the forge guys about this. Thank you for letting me know!

**Comment by Dealman** [comment]
Ya, we were able to solve it on our end by simply just slapping your mod on the clients. Since we're using MultiMC it was no biggie. Glad I could help, if you need some more help testing this bug later on don't hesitate to poke me a bit. 👊

**Comment by TelepathicGrunt** [comment]
forge merged my PR that fixes this issue so this so no longer be a problem anymore! Closing issue report now
