### ISSUE TITLE
Failed to get mob

### ISSUE THREAD

**Issue by AlexM2202** [TelepathicGrunt/RepurposedStructures#330]
Failed to get mob. Please check that integrated_stronghold:library.json is correct or that no other mod is interfering with how vanilla reads data folders. Let TelepathicGrunt know about this too!

**Comment by TelepathicGrunt** [comment]
This is an issue report for integrated_stronghold mod. They copied some of my logging code but didn’t change the messages. Please report to them and ask them to change their logging too.
