### ISSUE TITLE
Cannot start server with this mod (fabric, 1.20.4, bug)

### ISSUE THREAD

**Issue by vlad0-0** [TelepathicGrunt/RepurposedStructures#331]
I checked for conflicts with other mods, it doesn't seem to be the case. I ran it on a server without other mods (just fabric api and MidnightLib), same error

**Comment by TelepathicGrunt** [comment]
I need the error. Share your latest.log from server after attempting to start it

**Comment by vlad0-0** [comment]
Sorry, it seems to be my mistake that the library was not updated to the latest version. I checked again with the latest version of midnightlib and the server started successfully
