### ISSUE TITLE
[NeoForge 20.6.61-beta] Crash to launcher when clicking "Create New World" in Singleplayer

### ISSUE THREAD

**Issue by PiDay314** [TelepathicGrunt/RepurposedStructures#335]
Hello! Love this mod.  However, it appears to be causing a crash.  Minecraft will load the mod just fine, but when I go into "Singleplayer" and click "Create New World", it crashes back to the launcher with an Illegal State Exception.

I did a quick look through the crash log, and it seems like Repurposed Structures is trying to load values outside of allocated ranges for a lot of its structures... At least, that's what I can tell.  Once I removed this mod, I was able to enter the "Create New World" screen without a crash.

Sorry for the trouble! Didn't see the issue reported yet so I figured I'd jump on it.

NeoForge Version: 20.6.61-beta
Version: repurposed_structures-7.4.0+1.20.6-neoforge

See Gist containing the log below:
https://gist.github.com/PiDay314/a49711ac17ca2f578f144478b8c4c49f

**Comment by TelepathicGrunt** [comment]
stupid fricken mojang codec limit mumble grumbles nkjfdnfknsj

time to fix mixin again

**Comment by TelepathicGrunt** [comment]
Fixed now in 7.4.1

I really shot myself in the foot reporting this mojang bug which mojang solves by capping weight to 150 which then I have to go and undo that change....
https://bugs.mojang.com/browse/MC-203131
