### ISSUE TITLE
[Forge 1.19.2] Exception Ticking World

### ISSUE THREAD

**Issue by Darkfiend009** [TelepathicGrunt/RepurposedStructures#336]
RS Version: 6.3.28+1.19.2
Forge: 43.3.5

Running the modpack Fear Nightfall. When exploring, server ultimately crashes with Exception Ticking World and the debug.log fills with random placement attempts from Repurposed Structures.

debug.log: https://gist.github.com/Darkfiend009/9f2bc1e3322d0812b215ba63c7fddb62

**Comment by TelepathicGrunt** [comment]
Repeat of https://github.com/TelepathicGrunt/RepurposedStructures/issues/333

You need to update the better jungle temple compat datapack

This file you need to replace the modpack's datapack with: https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-better-jungle-temples-compat/files/4999732
