### ISSUE TITLE
Fatal feature placement crash: invalid identifier name "Random spawn bonus"

### ISSUE THREAD

**Issue by Treeways** [TelepathicGrunt/RepurposedStructures#338]
This bug renders my server unplayable unless I quickly teleport myself out of the area.

After strolling through the nether, the pack attempted to place a feature with an invalid identifier name:

`net.minecraft.util.InvalidIdentifierException: Non [a-z0-9/._-] character in path of location: repurposed_structures:Random spawn bonus`

Repurposed Structures v7.5.1 for Fabric 1.21 (loader version 0.15.11)
[Full crash log](https://github.com/user-attachments/files/15856370/rps-crash-log.txt)

**Comment by Treeways** [comment]
This bug was introduced in 1.21. It happens when the game attempts to spawn a bowman wither skeleton, then modify it with a random spawn bonus attribute. However, the provided ID is not syntactically valid. What this is intended to modify is unclear.

I can't find the implementation for whatever this attribute ID is a placeholder for. Either it is unimplemented, or I'm not able to find it at a glance:

https://github.com/TelepathicGrunt/RepurposedStructures/blob/473cc29054a75b39cacabdc5354e96890fe5318a/common/src/main/java/com/telepathicgrunt/repurposedstructures/world/features/WitherSkeletonWithBow.java#L47

Thanks,

**Comment by TelepathicGrunt** [comment]
AttributeModifiers need an ID so the game adds it as a new entry onto the mob. It's not something you register. It's a replacement for the UUID mojang used to have for every time they added an attribute to a mob to distinguish each `new AttributeModifier` added to a mob or if it overrides an existing one of same ID.

**Comment by TelepathicGrunt** [comment]
Fixed now and released

**Comment by Treeways** [comment]
Ah, interesting, that makes more sense. Thanks again!
