### ISSUE TITLE
village_ocean structure is causing game to lag due to some GL ERROR.

### ISSUE THREAD

**Issue by Ynaught** [TelepathicGrunt/RepurposedStructures#341]
On v7.5.3 (1.21 MC Fabric)

The log reads as follows:

> [19:47:47] [Server thread/INFO]: Locating element #minecraft:village (repurposed_structures:village_ocean) took 0 ms
> [19:47:47] [Render thread/ERROR]: ########## GL ERROR ##########
> [19:47:47] [Render thread/ERROR]: @ Pre render
> [19:47:47] [Render thread/ERROR]: 65539: Invalid key -1
> [19:47:47] [Render thread/ERROR]: ########## GL ERROR ##########
> [19:47:47] [Render thread/ERROR]: @ Pre render
> [19:47:47] [Render thread/ERROR]: 65539: Invalid key -1
> [19:47:47] [Render thread/ERROR]: ########## GL ERROR ##########
> [19:47:47] [Render thread/ERROR]: @ Pre render
> [19:47:47] [Render thread/ERROR]: 65539: Invalid key -1
> [19:47:47] [Render thread/ERROR]: ########## GL ERROR ##########
> [19:47:47] [Render thread/ERROR]: @ Pre render
> [19:47:47] [Render thread/ERROR]: 65539: Invalid key -1
> [19:47:47] [Render thread/ERROR]: ########## GL ERROR ##########
> [19:47:47] [Render thread/ERROR]: @ Pre render
> [19:47:47] [Render thread/ERROR]: 65539: Invalid key -1
> [19:47:47] [Render thread/ERROR]: ########## GL ERROR ##########
> [19:47:47] [Render thread/ERROR]: @ Pre render
> [19:47:47] [Render thread/ERROR]: 65539: Invalid key -1
> [19:47:47] [Render thread/ERROR]: ########## GL ERROR ##########
> [19:47:47] [Render thread/ERROR]: @ Pre render
> [19:47:47] [Render thread/ERROR]: 65539: Invalid key -1
> [19:47:47] [Render thread/ERROR]: ########## GL ERROR ##########
> [19:47:47] [Render thread/ERROR]: @ Pre render
> [19:47:47] [Render thread/ERROR]: 65539: Invalid key -1
> [19:47:47] [Render thread/ERROR]: ########## GL ERROR ##########
> [19:47:47] [Render thread/ERROR]: @ Pre render
> [19:47:47] [Render thread/ERROR]: 65539: Invalid key -1
> [19:47:47] [Render thread/ERROR]: ########## GL ERROR ##########
> [19:47:47] [Render thread/ERROR]: @ Pre render
> [19:47:47] [Render thread/ERROR]: 65539: Invalid key -1
> [19:47:47] [Render thread/ERROR]: ########## GL ERROR ##########
> [19:47:47] [Render thread/ERROR]: @ Pre render
> [19:47:47] [Render thread/ERROR]: 65539: Invalid key -1

**Comment by TelepathicGrunt** [comment]
Repurposed structures is a serverside mod. It has no rendering code at all. GL Errors are rendering related iirc so it is some other mod causing issues afaik. You’ll have to narrow down what other mod it is as RS is not involved here. I’m guessing you’re using shaders that have some sort of non-crashing issue?

**Comment by Ynaught** [comment]
Nope, I do not use shaders. Only texture packs.

Could you tell me all the blocks and parts used in an ocean village? Perhaps I can narrow down what block/part that is in conflict with the source that is actually causing the issue atleast. Perhaps there's something in the structure that a separate mod doesn't like.


Alternatively, it could just be that too many villagers/guard villagers spawn in this village. I lag too much before ever seeing it.

**Comment by TelepathicGrunt** [comment]
Repurposed structures only uses vanilla blocks. Mainly vanilla village job sites with normal blocks swapped with other normal blocks to fit biome theme. Ocean village is just a degraded vanilla village on ocean floor made of oak, spruce, jungle wood with some drowned spawning instead of villagers (like the villagers downed). Some dripstone inside the houses to show old age. That’s it. There isn’t anything special about it. Are you sure you haven’t ruled out other mod’s stuff nearby

**Comment by Ynaught** [comment]
Impossible to know, I'm usually underground when it happens/come into proximity with the issue. Thats just the section the log freaks out at for some reason.

**Comment by Ynaught** [comment]
The structure wouldn't happen to use any mob heads by chance, would it? I've had issues with those in the past. It could though just be too many mobs all at once, but the way you described it, I highly doubt on the too many mobs thing.

**Comment by TelepathicGrunt** [comment]
I don’t have mob heads in underwater village. If your issue is reproduceable, you can try making a backup of the world, then start removing mods and resourcepacks till issue stops. Clientside mods are the more likely thing to target

**Comment by Ynaught** [comment]
Unfortunately, I have way too many variables to test for, I'll just leave the issue report as "unresolved/not planned" and leave it at that.

> 65539: Invalid key -1

Still wish I coulda figured out what that was referring to tho.

**Comment by TelepathicGrunt** [comment]
I asked some friends and they pointed out this invalid key error is user input issue. In other words, you have unbounded a keybind that another mod was using. Probably can be fixed if you go into your keybind settings and make sure all keys have a keybind. They said the weird part is how the unbounded key is causing a gl error. Closing as this isn’t related to RS.

**Comment by Ynaught** [comment]
Woah, that IS weird. Thanks for the heads up. o_e
