### ISSUE TITLE
Update yung Compat datapacks to 1.21

### ISSUE THREAD

**Issue by MimzyFang** [TelepathicGrunt/RepurposedStructures#342]
With yung having recently released betas of all his mods for 1.21 to his patreons (the code is on the respective github repos and can be manually compiled) it's probably a good time to look into what needs to be done to update the Compat datapacks 

Also I'm sorry for opening a porting issue I know how annoying they can be please don't feel pressured by this Issue and take the time you need

**Comment by TelepathicGrunt** [comment]
I rather wait till the mods are fully released before porting compat datapacks

**Comment by MimzyFang** [comment]
You've probably seen it already but yung has updated his mods looking forward to when you have time to update the datapacks
