### ISSUE TITLE
when i enter the nether im crashing

### ISSUE THREAD

**Issue by nxiank** [TelepathicGrunt/RepurposedStructures#345]
im playing fantasy mc mod pack and when i enter the nether im getting crash i tried everything help me im gettin crash from  repurposed structures https://mclo.gs/DeHrRtz here is the crash report

**Comment by TelepathicGrunt** [comment]
Update the Repurposed Structures Better Templates Compat Datapack in your modpack

Duplicate of https://github.com/TelepathicGrunt/RepurposedStructures/issues/333

**Comment by TelepathicGrunt** [comment]
The updated datapack can be obtained here https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-better-jungle-temples-compat/files/4999732

**Comment by nxiank** [comment]
should i delete the old one?

**Comment by TelepathicGrunt** [comment]
Yes. Like updating a mod, you delete the old version and put on the new version

**Comment by nxiank** [comment]
> Yes. Like updating a mod, you delete the old version and put on the new version

now i cant play the game
https://prnt.sc/f0CQSfkKrQkg

**Comment by TelepathicGrunt** [comment]
If you’re on 1.18.2, you should grab the 1.18.2 compat datapack. I linked the 1.19.2 one
