### ISSUE TITLE
game crashes on underground bastion if More Mob Variants is installed

### ISSUE THREAD

**Issue by Hugs288** [TelepathicGrunt/RepurposedStructures#347]
[crash-2024-08-27_22.25.08-server.txt](https://github.com/user-attachments/files/16767662/crash-2024-08-27_22.25.08-server.txt)

**Comment by TelepathicGrunt** [comment]
The problematic mod is More Mob Variant’s mixin. Please report to them and link this issue report so they know what to fix

net.minecraft.class_1613.handler$gaj000$moremobvariants$onInitialize(cl

**Comment by Hugs288** [comment]
👍
