### ISSUE TITLE
Domestication Innovation Compatibility 

### ISSUE THREAD

**Issue by Coolchilion** [TelepathicGrunt/RepurposedStructures#348]
https://www.curseforge.com/minecraft/mc-mods/domestication-innovation

Domestic innovation adds a new villager and home called the Animal Tamer Villager

**Comment by TelepathicGrunt** [comment]
Ah this mod. Yeah I already got a compat datapack for it. You can download it from here: https://legacy.curseforge.com/minecraft/texture-packs/repurposed-structures-domestication-innovation
