### ISSUE TITLE
Abandoned Villages Support

### ISSUE THREAD

**Issue by thimblebird** [TelepathicGrunt/RepurposedStructures#349]
as far as i can tell (in game) there's no chance for RS villages to spawn [abandoned](https://minecraft.wiki/w/Village#Abandoned_villages). is there a chance abandoned versions will be added in the future or if already present, is there a way to change the spawn rates of them? 🐢

**Comment by TelepathicGrunt** [comment]
They have a 1/51 chance of a village being abandoned just like vanilla. Controlled by the town center start pool weight values. Overriding these files by datapack (see config datapack example for RS) will let you change the weight values here to make the zombie start piece more likely to be chosen https://github.com/TelepathicGrunt/RepurposedStructures/blob/1.21-Arch/common/src/main/resources/data/repurposed_structures/worldgen/template_pool/villages/birch/town_centers.json

**Comment by TelepathicGrunt** [comment]
lol the wiki says 2% but vanilla is 1/51 chance or  1.96%. Technically incorrect wiki! 
https://github.com/misode/mcmeta/blob/data-json/data/minecraft/worldgen/template_pool/village/plains/town_centers.json

**Comment by thimblebird** [comment]
whoops! cool, thanks for the clarification 🐢
now i know why the "80 % abandoned villages" mod only works with vanilla villages if its spawn chance is set for every structure individually instead of a "global chance" to generate an abandoned village.
