### ISSUE TITLE
[1.21][Fabric] Crashes near structures generated by Repurposed Structures

### ISSUE THREAD

**Issue by willyougooutwithme** [TelepathicGrunt/RepurposedStructures#351]
So basically I was roaming in my world and suddenly I saw a Overworld End City (from Repurposed Structures) and shortly after, my game crashed. So after I removed Repurposed Structures, the structure is visible, but no crash. I reenabled the mod again and located (using the locate command) to find another repurposed structure in an unloaded chunk, found it, teleported to it and it crashed again.

Crash Report - https://mclo.gs/jHp3a1D
Latest.log - https://mclo.gs/PbImesw

**Comment by TelepathicGrunt** [comment]
It’s not repurposed structures. And isn’t the overworld city.

net.minecraft.entity.mob.SkeletonEntity.handler$egb000$moremobvariants$onInitialize(SkeletonEntity.java:556)

an underground Bastion is spawning nearby with Skeletons and More Mob Variants has a broken mixin that is running code that breaks worldgen. You’ll need to report to More Mob Variants
