### ISSUE TITLE
Server crashes after a while exploring new chunks

### ISSUE THREAD

**Issue by AzCreep** [TelepathicGrunt/RepurposedStructures#352]
Server version: 1.21.1
Mod Version 7.5.10
As title says after exploring a x number of new chunks the server fails to load and crashes it can only be fixed by disabling the mod and enter the server without it

[crash-2024-09-28_07.59.16-server.txt](https://github.com/user-attachments/files/17173661/crash-2024-09-28_07.59.16-server.txt)

**Comment by TelepathicGrunt** [comment]
Duplicate of https://github.com/TelepathicGrunt/RepurposedStructures/issues/351 and https://github.com/TelepathicGrunt/RepurposedStructures/issues/347

This is not a Repurposed Structures issue. This is a More Mobs Variant issue. Disabling More Mobs Variant will fix the issue https://github.com/nyuppo/MobVariants/issues/49

**Comment by AzCreep** [comment]
thank you for fast response i will disable it till further fix!
