### ISSUE TITLE
invalid datapack name 1.21.1 neoforge

### ISSUE THREAD

**Issue by VaporeonScripts** [TelepathicGrunt/RepurposedStructures#355]
![image](https://github.com/user-attachments/assets/e9464d3e-151c-4228-b074-be7b384a9fc8)

**Comment by VaporeonScripts** [comment]
u might have forgotten to add it/typo in some part of code

**Comment by TelepathicGrunt** [comment]
technically not invalid and wont prevent datapack from loading

just wrong description in pack.mcmeta

**Comment by TelepathicGrunt** [comment]
fixed

**Comment by VaporeonScripts** [comment]
ty
