### ISSUE TITLE
reason to put datapacks in resource packs?

### ISSUE THREAD

**Issue by VaporeonScripts** [TelepathicGrunt/RepurposedStructures#356]
why do you put those datapacks in resource pack section? shouldnt they be in datapacks section, doing that means any modpack creator will get the license strike due to curseforge being unable to find those in datapack section (this for all the repurposed/yung compatibility datapacks)

**Comment by TelepathicGrunt** [comment]
The project was made back when curseforge did not have datapack section. And they said they would one day migrate all legacy resourcepacks tagged as datapacks to the datapack section. As you can see, curseforge is slacking on this. And I rather not spin up a whole new project myself just to move all my stuff as it is quite a bit of work.

Also I doubt curseforge would strike modpack creators. Especially as shown on the project's sidebar, datapack is an option to select for a resourcepack project so CF knew what they gotten themselves into. If you get struck by CF, lmk and who youa re talking to so I can be blunt to them about their problem they made for themselves.

**Comment by VaporeonScripts** [comment]
Ima show u the message rq

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/a74ad234-f957-4efa-8a15-8aee84e33403)

**Comment by VaporeonScripts** [comment]
while using them from datapack section in modrinth seems to not strike me ( i will check tomorrow morning once i wake up)

**Comment by TelepathicGrunt** [comment]
@VaporeonScripts, you could try both shipping the datapack in the override and have it listed in the manifest. CF launcher will download it into the resourcepacks folder where it will do nothing but still give me download counts. But the datapacks in the override folder will still work. They probably want the downloads to still count probably. 

If they still fight back, link them this github post with my responses here and they should back down.

**Comment by VaporeonScripts** [comment]
Well idk how to link it as it's notifications not support,altough ima wait to see how it goes with modrinth modpacks

**Comment by TelepathicGrunt** [comment]
for CF. you would make a new ticket here explaining the issue and the pack and a CF rep can undo the rejection. Hopefully they can reach out to the CF moderator to tell them to stop rejecting datapacks until CF properly handles them
https://support.curseforge.com/en/support/tickets/new

**Comment by VaporeonScripts** [comment]
Alright

**Comment by JTK222** [comment]
CF does indeed want datapack creators to upload them as resourcepacks.
Someone got to hyped creating the datapack section without considering the consequences and now it's to late to remove it.
Install the datapacks trought the CF Launcher & do not move them.
Configure whichever mod you use to load them, to load them out of the resourcepacks folder.

(Yes, I know this all sounds dumb, CF also knows that it's dumb, and they are working on a solution)

P.s. CF Will transfer all existing datapacks to the datapack project type, once those can be installed at all.

**Comment by VaporeonScripts** [comment]
Yeah they striked the pack again,ima have to issue it

**Comment by TelepathicGrunt** [comment]
Which datapack loading mod do you use? Paxi, Global Packs, OpenLoader, KubeJS?

**Comment by VaporeonScripts** [comment]
Paxi

**Comment by VaporeonScripts** [comment]
ima update all the mods, upload the pack, if i get the strike, im reporting it explaining that curseforge didnt yet move ur datapacks from res packs to datapacks and that i got permission to upload ur datapacks in my modpack by linking this issue?

**Comment by VaporeonScripts** [comment]
issue happened again, im opening the issue

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/242e11fa-e107-43e2-8156-44c56440a92f)
here

**Comment by TelepathicGrunt** [comment]
Hmm checking paxi's configs and I can't seem to find how to make it target the default resourcepacks folder to load datapacks. Let me poke the Paxi dev for advice

**Comment by VaporeonScripts** [comment]
alright,its been 7h and curseforge staff didnt reply yet :smile:

**Comment by VaporeonScripts** [comment]
they still didnt reply :/

**Comment by VaporeonScripts** [comment]
here what they replied to me:
![image](https://github.com/user-attachments/assets/74baeed4-96bc-4dd0-9bb4-8ec7f64f788d)

**Comment by VaporeonScripts** [comment]
> CF does indeed want datapack creators to upload them as resourcepacks. Someone got to hyped creating the datapack section without considering the consequences and now it's to late to remove it. Install the datapacks trought the CF Launcher & do not move them. Configure whichever mod you use to load them, to load them out of the resourcepacks folder.

so i will need to install the datapacks which are in the resource packs section into the paxi datapack folder and then i need to automatically load them? or what

**Comment by TelepathicGrunt** [comment]
You would switch to global packs and it’ll load the datapacks from resourcepacks folder.

Or switch to openloader and set it to read from resourcepacks folder.

Or copy the datapack into the paxi folder and then unzip them so the hash system doesn’t detect them but this could cause cf moderators to strike you for bypassing rules if they are feeling feisty.

or wait for paxi to update to where you can tell it to load from resourcepacks folder

**Comment by VaporeonScripts** [comment]
bruh,ima see

**Comment by VaporeonScripts** [comment]
how do i make global packs load the datapacks from resource pack folder?

**Comment by TelepathicGrunt** [comment]
Global Packs reads from resourcepacks folder by default without any configuring needed

**Comment by VaporeonScripts** [comment]
oh

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/180ff90d-79fe-487c-8070-8d19407240b5)

**Comment by VaporeonScripts** [comment]
(in the meanwhile i redownloaded the datapacks/resourcepacks like 2 times :skull: )

**Comment by TelepathicGrunt** [comment]
You have my permission to redistribute my datapacks outside of manifests

**Comment by VaporeonScripts** [comment]
alright, in the meanwhile global packs didnt even work for resource packs,so i had to use paxi only for resource packs, and global packs for datapacks and datapacks in resource pack folder :skull:
