### ISSUE TITLE
Redirector causes Failed to execute chunk source main thread executor task in overworld

### ISSUE THREAD

**Issue by Ethan-Dankiw** [TelepathicGrunt/RepurposedStructures#358]
### **Details**
Minecraft Version: 1.20.1
Forge Version: 47.3.7

I am using shaders via the Oculus mod v1.7.0.

<details><summary>ModList</summary>
<p>

ae2wtlib-15.2.3-forge.jar
AI-Improvements-1.20-0.5.2.jar
almostunified-forge-1.20.1-0.9.4.jar
amendments-1.20-1.2.12.jar
antiblocksrechiseled-0.4.4.jar
Apotheosis-1.20.1-7.4.3.jar
ApothicAttributes-1.20.1-1.3.7.jar
appleskin-forge-mc1.20.1-2.5.1.jar
appliedenergistics2-forge-15.2.13.jar
Aquaculture-1.20.1-2.5.2.jar
aquaculture_delight_1.0.0_forge_1.20.1.jar
architectury-9.2.14-forge.jar
athena-forge-1.20.1-3.1.2.jar
BadOptimizations-2.1.4-1.20.1.jar
badpackets-forge-0.4.3.jar
balm-forge-1.20.1-7.3.9-all.jar
betterfpsdist-1.20.1-4.4.jar
betterp2p-1.4.1-forge.jar
better_angel_ring-1.20.1-1.0.2.jar
biomemusic-1.20.1-2.5.jar
bocchium-1.20.1-0.0.3.jar
Bountiful-6.0.3+1.20.1-forge.jar
buildinggadgets2-1.0.7.jar
CapeJS-1.0.0-1.20.1-forge.jar
CarbonConfig-1.20-1.2.6.jar
carryon-forge-1.20.1-2.1.2.7.jar
CBMultipart-1.20.1-3.3.0.146-universal.jar
cherishedworlds-forge-6.1.6+1.20.1.jar
Chipped-forge-1.20.1-3.0.6.jar
ChippedExpress-universal.jar
chisels-and-bits-forge-1.4.148.jar
chisel_chipped_integration-v1.1.3-1.20.1.jar
Chunk-Pregenerator-1.20-4.4.4.jar
citresewn-1.20.1-5.jar
clienttweaks-forge-1.20-11.1.0.jar
climbladdersfast-4.0-1.20.1-forge.jar
cloth-config-11.1.118-forge.jar
Clumps-forge-1.20.1-12.0.0.4.jar
CodeChickenLib-1.20.1-4.4.0.516-universal.jar
cofh_core-1.20.1-11.0.2.56.jar
collective-1.20.1-7.84.jar
comforts-forge-6.4.0+1.20.1.jar
configuration-forge-1.20.1-2.2.1.jar
configured-forge-1.20.1-2.2.3.jar
connectedglass-1.1.12-forge-mc1.20.1.jar
connectivity-1.20.1-5.6.jar
constructionwand-1.20.1-2.11.jar
Controlling-forge-1.20.1-12.0.2.jar
corpse-forge-1.20.1-1.0.14.jar
cosmeticarmorreworked-1.20.1-v1a.jar
craftingstation-1.20.1-1.jar
craftingtweaks-forge-1.20.1-18.2.5.jar
CreativeCore_FORGE_v2.11.37_mc1.20.1.jar
cristellib-1.1.5-forge.jar
Cucumber-1.20.1-7.0.11.jar
cupboard-1.20.1-2.7.jar
curios-forge-5.9.1+1.20.1.jar
DarkModeEverywhere-1.20.1-1.2.2.jar
defaultoptions-forge-1.20-18.0.1.jar
DefaultWorldType-1.20.1-4.0.4.jar
difficultylock-1.20.1-4.6.jar
DimStorage-1.20.1-8.0.1.jar
Ding-1.20.1-Forge-1.5.0.jar
drippyloadingscreen_forge_3.0.1_MC_1.20.1.jar
DungeonsArise-1.20.x-2.1.58-release.jar
easy-villagers-forge-1.20.1-1.1.23.jar
EasyMagic-v8.0.1-1.20.1-Forge.jar
ecologics-forge-1.20.1-2.2.0.jar
EdivadLib-1.20.1-2.0.1.jar
effortlessbuilding-1.20.1-3.8.2.jar
elevatorid-1.20.1-lex-1.9.jar
embeddium-0.3.30+mc1.20.1.jar
embeddiumplus-1.20.1-v1.2.13.jar
emi-1.1.13+1.20.1+forge.jar
emi_loot-0.6.6+fix3+1.20.1+forge.jar
enderchests-forge-1.20.1-1.2.jar
EnderIO-1.20.1-6.1.8-beta-all.jar
endertanks-forge-1.20.1-1.3.jar
entityculling-forge-1.7.0-mc1.20.1.jar
Explorify v1.6.2 f10-48.jar
ExtendedAE-1.20-1.1.12-forge.jar
ExtendedCrafting-1.20.1-6.1.5u.jar
ExtremeSoundMuffler-3.48-forge-1.20.1.jar
fancymenu_forge_3.2.3_MC_1.20.1.jar
FarmersDelight-1.20.1-1.2.4.jar
farmersplus-1.0.3.jar
farmersrespite-1.20.1-2.1.2.jar
FarmersStructures-1.0.3-1.20.jar
FastFurnace-1.20.1-8.0.2.jar
FastLeafDecay-32.jar
FastSuite-1.20.1-5.0.1.jar
ferritecore-6.0.1-forge.jar
findme-3.2.1-forge.jar
fixexperiencebug-1.20-46.2.2.jar
FluxNetworks-1.20.1-7.2.1.15.jar
forgivingvoid-forge-1.20-10.0.1.jar
FpsReducer2-forge-1.20-2.5.jar
FramedBlocks-9.3.1.jar
framing_templates-1.0.1a.jar
ftb-chunks-forge-2001.3.1.jar
ftb-essentials-forge-2001.2.2.jar
ftb-library-forge-2001.2.4.jar
ftb-quests-forge-2001.4.8.jar
ftb-ranks-forge-2001.1.3.jar
ftb-teams-forge-2001.3.0.jar
ftb-ultimine-forge-2001.1.5.jar
ftb-xmod-compat-forge-2.1.1.jar
ftbbackups2-forge-1.20-1.0.23.jar
fulleng-forge-1.7.2-1.20.1.jar
functionalstorage-1.20.1-1.2.12.jar
fusion-1.1.1-forge-mc1.20.1.jar
gcyr-1.20.1-0.2.0.jar
geckolib-forge-1.20.1-4.4.9.jar
Glodium-1.20-1.5-forge.jar
gpumemleakfix-1.20.1-1.8.jar
gtceu-1.20.1-1.4.1+patch.2.jar
HammerLib-1.20.1-20.1.32.jar
HangGlider-v8.0.1-1.20.1-Forge.jar
HostileNeuralNetworks-1.20.1-5.3.1.jar
Iceberg-1.20.1-forge-1.1.21.jar
iChunUtil-1.20.1-Forge-1.0.0.jar
ImmediatelyFast-Forge-1.2.21+1.20.4.jar
inventoryessentials-forge-1.20.1-8.2.6.jar
invtweaks-1.20.1-1.1.0.jar
ironfurnaces-1.20.1-4.1.6.jar
IronJetpacks-1.20.1-7.0.6.jar
item-filters-forge-2001.1.0-build.59.jar
Jade-1.20.1-forge-11.11.1.jar
JadeAddons-1.20.1-Forge-5.3.0.jar
JAVD-Forge-5.0.1+mc1.20.1.jar
jecalculation-forge-1.20.1-4.0.4.jar
jei-1.20.1-forge-15.14.0.64.jar
jmi-forge-1.20.1-0.14-48.jar
journeymap-1.20.1-5.10.1-forge.jar
Kambrik-6.1.1+1.20.1-forge.jar
konkrete_forge_1.8.0_MC_1.20-1.20.1.jar
kotlinforforge-4.11.0-all.jar
kubejs-forge-2001.6.5-build.14.jar
kubejs-thermal-2001.1.10-build.2.jar
kubejs_enderio-forge-1.20.1-0.5.1.jar
largemeals-1.20.1-2.0.jar
laserio-1.6.8.jar
ldlib-forge-1.20.1-1.0.28.jar
LegendaryTooltips-1.20.1-forge-1.4.5.jar
lithostitched-forge-1.20.1-1.3.1b.jar
Log-Begone-Forge-1.20.1-1.0.8.jar
lootjs-forge-1.20.1-2.12.0.jar
lootr-forge-1.20-0.7.34.89.jar
lostcities-1.20-7.3.2.jar
mae2-1.4.0.jar
megacells-forge-2.4.4-1.20.1.jar
melody_forge_1.0.3_MC_1.20.1-1.20.4.jar
merequester-forge-1.20.1-1.1.4.jar
modelfix-1.15.jar
modernfix-forge-5.19.3+mc1.20.1.jar
moonlight-1.20-2.13.13-forge.jar
morejs-forge-1.20.1-0.10.0.jar
MouseTweaks-forge-mc1.20.1-2.25.1.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
Neat-1.20-35-FORGE.jar
nerb-1.20.1-0.3-FORGE.jar
no-telemetry-1.8.0.jar
NoChatReports-FORGE-1.20.1-v2.2.2.jar
noisium-forge-2.3.0+mc1.20-1.20.1.jar
nomowanderer-1.20.1_1.6.4.jar
nonetherportal-1.20.1-1.0.jar
notenoughcrashes-4.4.7+1.20.1-forge.jar
NuclearCraft-1.20.1-1.0.0-beta.6.jar
oculus-mc1.20.1-1.7.0.jar
PackagedAuto-1.20.1-3.4.7.25.jar
PackagedExCrafting-1.20.1-3.4.0.12.jar
PackagedExExCrafting-1.20.1-1.0.0.1.jar
Patchouli-1.20.1-84-FORGE.jar
Placebo-1.20.1-8.6.2.jar
polylib-forge-2000.0.3-build.143.jar
polymorph-forge-0.49.5+1.20.1.jar
Prism-1.20.1-forge-1.0.5.jar
ProjectRed-1.20.1-4.19.0-expansion.jar
ProjectRed-1.20.1-4.19.0-exploration.jar
ProjectRed-1.20.1-4.19.0-fabrication.jar
ProjectRed-1.20.1-4.19.0-illumination.jar
ProjectRed-1.20.1-4.19.0-integration.jar
ProjectRed-1.20.1-4.19.0-transmission.jar
ProjectRed-1.20.1-4.20.0-beta+5-core.jar
PuzzlesLib-v8.1.22-1.20.1-Forge.jar
Quark-4.0-460.jar
radium-mc1.20.1-0.12.3+git.50c5c33.jar
redirector-5.0.0.jar
redstone_arsenal-1.20.1-8.0.1.24.jar
redstone_clock-1.1-1.20-1.20.1.jar
resourcefullib-forge-1.20.1-2.1.29.jar
rhino-forge-2001.2.3-build.6.jar
rubberdrawers-1.1.jar
Searchables-forge-1.20.1-1.0.3.jar
shetiphiancore-forge-1.20.1-1.3.jar
Shrink-1.20.1-1.4.5.jar
SimpleDiscordRichPresence-forge-4.0.3-build.40+mc1.20.1.jar
smoothboot(reloaded)-mc1.20.1-0.0.4.jar
smoothchunk-1.20.1-3.6.jar
Snad-1.20.1-Neo(Forge)-2.0.4.jar
SolarFluxReborn-1.20.1-20.1.6.jar
sophisticatedbackpacks-1.20.1-3.20.6.1064.jar
sophisticatedcore-1.20.1-0.6.25.632.jar
sophisticatedstorage-1.20.1-0.10.26.817.jar
spark-1.10.53-forge.jar
steamadditions-1.2.jar
steamdynamo-0.1.2.jar
Structory_1.20.x_v1.3.5.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.17a-forge-mc1.20.1.jar
systeams-1.20.1-1.7.1.jar
TelePastries-1.20.1-0.8.3.jar
temp.md
TerraBlender-forge-1.20.1-3.0.1.7.jar
Terralith_1.20.x_v2.5.4.jar
thermaldrawers-1.0.jar
thermal_expansion-1.20.1-11.0.1.29.jar
thermal_foundation-1.20.1-11.0.6.70.jar
thermal_innovation-1.20.1-11.0.1.23.jar
the_afterdark-1.20.1-forge-1.0.2.jar
TipTheScales-forge-1.20.1-9.0.0.1.jar
titanium-1.20.1-3.8.32.jar
ToastControl-1.20.1-8.0.3.jar
toofast-1.20-0.4.3.5.jar
ToolBelt-1.20.1-1.20.01.jar
torchmaster-20.1.6.jar
Towns-and-Towers-1.12-Fabric+Forge.jar
trashcans-1.0.18b-forge-mc1.20.jar
trenzalore-forge-3.3.10+mc1.20.1-all.jar
trofers-forge-5.0.2.jar
TwerkItMeal-2.3.0.jar
ulvcovm-0.1.2.jar
watercollector-1.20.1-1.1.0.jar
waterframes-FORGE-mc1.20.1-v2.1.3.jar
watermedia-2.0.70.jar
waystones-forge-1.20-14.1.5.jar
wirelesschargers-1.0.9a-forge-mc1.20.jar
WWOO-FABRIC+FORGE+QUILT-2.0.0.jar
xtonesreworked-1.0.3-F_1.20.1-47.2.0.jar
YeetusExperimentus-Forge-2.3.1-build.6+mc1.20.1.jar
YungsApi-1.20-Forge-4.0.6.jar
YungsBetterDesertTemples-1.20-Forge-3.0.3.jar
YungsBetterDungeons-1.20-Forge-4.0.4.jar
YungsBetterEndIsland-1.20-Forge-2.0.6.jar
YungsBetterJungleTemples-1.20-Forge-2.0.5.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
YungsBetterNetherFortresses-1.20-Forge-2.0.6.jar
YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar
YungsBetterStrongholds-1.20-Forge-4.0.3.jar
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar
YungsBridges-1.20-Forge-4.0.3.jar
YungsCaveBiomes-1.20.1-Forge-2.0.1.jar
YungsExtras-1.20-Forge-4.0.3.jar
Zeta-1.0-24.jar
zmedievalmusic-1.20.1-2.1.jar
zume-1.1.2.jar
[Forge]CTOV-3.4.9b.jar

</p>
</details> 

I am playing a slightly modified version of the Monifactory Beta 0.9.2 and when I teleported to a random location my game shows what is in the below screenshot.
![image](https://github.com/user-attachments/assets/ecfd1ac3-c59c-4298-8a8e-0bd407decbbe)

The game itself has not crashed and the process is still running, so was not booted back to the minecraft launcher, however instead it seems to have plummeted in usage.
![image](https://github.com/user-attachments/assets/8f83b395-afb2-4002-8aa4-02e3d74ae21a)

From what I could tell from reading the stack trace myself, the crash first occurred at 21:51:0 right after I did the random teleport with /rtp, and can be found by searching "Error executing task on Chunk source main thread executor for minecraft:overworld"

Had to put part of the stack trace on pastebin due to character limit on GitHub, likewise also hit the max file size limit on pastebin so had to paste in multiple parts, I tried to make the breaks between files as clean as possible (eg, between a script finished loading and then a new script being loaded) they are also in chronological order.

1. https://pastebin.com/gjHatshz
2. https://pastebin.com/PF1rNZAU
3. https://pastebin.com/eEXbb1a6

**Comment by TelepathicGrunt** [comment]
`Caused by: java.lang.IllegalArgumentException: Cannot set property DirectionProperty{name=facing, clazz=class net.minecraft.core.Direction, values=[north, south, west, east]} to up on Block{minecraft:chest}, it is not an allowed value`

As you can see here in my code:
https://github.com/TelepathicGrunt/RepurposedStructures/blob/5877644c41d9ffd5e437ff8278104be250960495/common/src/main/java/com/telepathicgrunt/repurposedstructures/utils/GeneralUtils.java#L91-L112

I get the horizontal property of the current chest. Then I iterate over `Direction.Plane.HORIZONTAL` until I find a direction that works. Then I assign the opposite of the selected face which for horizontal faces, is the opposite horizontal face.

Nowhere in this code is it physical possible for `UP` to ever be selected. Meaning you have a mod that is doing something so unbelievably cursed. Like adding `DOWN` to the `Direction.Plane.HORIZONTAL` enum direction list (if they do that, they should be figuratively stabbed). Or the modder forced the default chest blockstate to have `DOWN` as the direction when querying `HorizontalDirectionalBlock.FACING` off of the blockstate but never actually made chests be truly able to have `UP` so it crashes when I assign the opposite back to the block.

There's nothing I can do because someone is breaking the contract of either the Chest block badly or the enum badly. I do not know which mod so you will have to trial and error removing mods until you find out who and let me know so I can contact them

**Comment by TelepathicGrunt** [comment]
>  redirector-5.0.0.jar

Nope, please remove this mod asap. This is 99% the problem. Redirector is known to remove the clone in `Enum.values()` and makes mods explode with each other when one assumed that list was cloned and modifies it. I strongly recommend not using that mod. There are much better performance mods out there that can improve the game's performance without modifying enums.
