### ISSUE TITLE
error with this datapack on console?

### ISSUE THREAD

**Issue by VaporeonScripts** [TelepathicGrunt/RepurposedStructures#359]
https://mclo.gs/HcUc3pA

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/74c54924-2276-4057-80b6-280b5c1713c2)

**Comment by TelepathicGrunt** [comment]
Well, I would assume that the file already exist error there means you already have the datapack loaded somewhere and are loading it twice

**Comment by VaporeonScripts** [comment]
yeah but i dont have it twice

**Comment by TelepathicGrunt** [comment]
Have you talked with the global packs dev? I don’t see how this would be on my end tbh

**Comment by VaporeonScripts** [comment]
Ima issue it ig

**Comment by TelepathicGrunt** [comment]
Datapack loads with Global Packs for me without issue. Closing as there is nothing I can do as the datapack is setup just fine. If there is an issue, it would be on Global Pack's side or something with your specific modpack
![image](https://github.com/user-attachments/assets/08ad3b3a-98ad-4dbf-8b66-b031de97f334)
