### ISSUE TITLE
Monsters respawning in structures

### ISSUE THREAD

**Issue by Razor235T** [TelepathicGrunt/RepurposedStructures#360]
Minecraft 1.20.1 Forge 47.3.10 Repurposed Structures 7.1.15

With the mod installed only, mobs keep respawning in structures, both vanilla and modded (if with mods installed). Without the mod it does not happen- once you kill the mobs, new don't spawn. For example pillager outpost, you kill 5-6 mobs and that's it. But with the Repurposed Structures mobs keep respawning.

**Comment by TelepathicGrunt** [comment]
Uhh vanilla pillager outposts do respawn pillagers over time. That’s the same behavior I keep in my outpost variants. This is normal behavior

https://minecraft.wiki/w/Pillager_Outpost
![IMG_1187](https://github.com/user-attachments/assets/f7c98b4b-288e-4f8d-af4e-0a3d24de0c03)

In fact, you can check the vanilla json files directly and see that any monster spawn attempt that falls in bounds of the vanilla outpost will replace the monster with pillager and spawns it as pillagers can spawn on world surface.
https://github.com/misode/mcmeta/blob/ad7e7407a120064b152478bdb4570c7c8d9d833a/data/minecraft/worldgen/structure/pillager_outpost.json#L7

Repurposed structures has no effect on this vanilla behavior. You will see this behavior with solely unmodded as well
