### ISSUE TITLE
Update to 1.21.3

### ISSUE THREAD

**Issue by Ketoro** [TelepathicGrunt/RepurposedStructures#362]
obligatory "update to newest version" issue

**Comment by TelepathicGrunt** [comment]
There’s no reason to. Most modpacks and many modders are staying on 1.21.1 until 1.22 releases. It would be a waste of time and effort for me to update to 1.21.3 when it’s too niche to develop on and is going to be replaced by 1.21.4 soon anyway. Mc is updating faster now with many more refactors and changes

**Comment by Ketoro** [comment]
understandable, ill be awaiting 1.22 then.
