### ISSUE TITLE
Exception generating new chunk

### ISSUE THREAD

**Issue by e95h** [TelepathicGrunt/RepurposedStructures#364]
Hi, My game keeps crashing, and the report says it's because of the witch hut structures. I want to know if there's any solution to this. I installed the better with huts data pack too; I'm not sure if maybe that's what is causing the crash

[crash-2024-12-21_12.35.50-server.txt](https://github.com/user-attachments/files/18219911/crash-2024-12-21_12.35.50-server.txt)

**Comment by TelepathicGrunt** [comment]
Are you using the right datapack for your Mc version. For example, 1.20.1 datapack will not for for 1.21

**Comment by TelepathicGrunt** [comment]
No new info for over a week. Closing
