### ISSUE TITLE
[1.16.4] Server freezing due to specific stronghold structure gen?

### ISSUE THREAD

**Issue by Carro1001** [TelepathicGrunt/RepurposedStructures#37]
I was in an iceberg biome when my internal server suddenly froze and I could not do anything, I think this mod was the cause of it, or an incompatibility between this mod and a few others, the server freezes to the point where i cannot even quit it properly(saving, etc), and get softlocked in the saving screen, having to forcefully close the game.

the debug.log was too big to put in hastebin, so i put a snippet off the part that seems to be right before and during the freeze

https://hastebin.com/qiqidodape.yaml

Just tell me if ya need any more info on it

**Comment by TelepathicGrunt** [comment]
I'm not seeing anything in the snippet of logs linked. Can you post the latest.log file onto this post? I can download it and check it out no matter how large it is. 

Is there a specific reason why you suspect it is the stronghold? What are the mods you have on?  (I doo see Ice and Fire which has caused me to freeze many times but maybe they patched the freezing issues since the last time I tested that mod)

**Comment by Carro1001** [comment]
[debug-1.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/5578053/debug-1.log)

it's due to this specific part right before lagging that i suspected it was something related to a stronghold

[21nov2020 04:01:59.413] [Worker-Main17/DEBUG] [mixin/]: Mixing StrongholdGeneratorAccessor from repurposed_structures.mixins.json into net.minecraft.world.gen.feature.structure.StrongholdPieces
[21nov2020 04:01:59.413] [Worker-Main17/DEBUG] [mixin/]: Renaming @Accessor method getPIECE_WEIGHTS()[Lnet/minecraft/world/gen/feature/structure/StrongholdPieces$PieceWeight; to getPIECE_WEIGHTS_$md$07bb6e$0 in repurposed_structures.mixins.json:StrongholdGeneratorAccessor

although i went into the same spot and found no issues right after, so i'm quite confused

**Comment by TelepathicGrunt** [comment]
That line just means my mixins are being applied correctly and all is good there. Though thank you for the log! I’ll check out the log once I get back to my computer. 

It might just be ice and fire having another freezing bug again. I’ll test their latest version too and see if I can get the freeze.

**Comment by Carro1001** [comment]
I've also had this weird freeze before when playing with my friend, so maybe it really might be i/f? If you manage to find out which mod it is, i'll surely contact the dev abt it!

**Comment by TelepathicGrunt** [comment]
What is weird is the log (while spammed to the moon and back), doesn't seem to point to anything specific. I did notice there's optifine on and some parts of the log showed missing jigsaw stuff `Empty or none existent pool: minecraft:none` but not why. 

One last thing we can do. Can you put on this Blame mod, enter the world, and give me the latest.log file? I doubt it will find what's wrong but it's worth a shot
https://www.curseforge.com/minecraft/mc-mods/blame

**Comment by Carro1001** [comment]
[debug.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/5578704/debug.log)
Here it is, didn't manage to replicate the issue, though, even going to the same spot n all

**Comment by TelepathicGrunt** [comment]
Hmm. Lots of people aren't registering their configuredfeatures but that would cause the game to freeze. Only cause biome stuff to soemtimes not spawn other mod's stuff. 

Anyway, I loaded latest Ice and Fire in World Blender so all dragons spawn in its dimension as a quick way to test and not even a minute later, the game froze. rip.

Guess ice and fire still havent fixed their freezing bug
