### ISSUE TITLE
(Suggestion) create new custom style villages to biomes!

### ISSUE THREAD

**Issue by TelepathicGrunt** [TelepathicGrunt/RepurposedStructures#4]
Suggested by JoshD8500 on CurseForge.

Will take a lot of time to build and put together the jigsaw structure for custom villages but it can be done when I get a lot of free time.

Biomes to shoot for:

Badlands.
Giant Tree Taiga.
Oceans (think floating villages)
Dark oak forest, forest, birch forest (all have same style)
extreme hills
jungle
ice spikes (maybe?)
End (maybe. Would have to see what happens to houses that generate off the islands...)

Biomes that cannot work:
Nether (due to the ceiling, villages cannot generate inside the nether's playable area and will always be stuck above the bedrock ceiling)

Any other biomes suggestions?

**Comment by JoshD8500** [comment]
Swamp

**Comment by TelepathicGrunt** [comment]
v1.6.0 is out with badlands village! Though making it was SUPER tedious and time consuming holy moley! I definitely will not be doing that again lol. If I can make a script instead to grab vanilla's village nbt files and do changes that way... hmmm

**Comment by TelepathicGrunt** [comment]
Note to self: Ocean

**Comment by TelepathicGrunt** [comment]
1.7.0 released with 6 new villages! I dont think i can add more and keep them looking good without weeks of work lol

**Comment by JoshD8500** [comment]
Thank you for the hard work and time much appreciated!
