### ISSUE TITLE
Yung's Better Mineshafts support

### ISSUE THREAD

**Issue by SlimF** [TelepathicGrunt/RepurposedStructures#41]
Me again!

This is the same suggestion as the I made in this thread #40 

Basically, let RS create its mineshaft variants, but with [Yung's Better Mineshafts](https://github.com/yungnickyoung/YUNGs-Better-Mineshafts) design

Better Mineshafts CurseForge: https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge

**Comment by TelepathicGrunt** [comment]
RS should already support allowing it's mineshafts spawning alongside yung's. Are you able to find both in a world? 

Basically, I got code to detect if yung's is on and to not remove the vanilla mineshaft if so which allows them to replace it. (I always add my mineshafts no matter what)
https://github.com/TelepathicGrunt/RepurposedStructures/blob/7adf4a1e7505c5875dba1ae5dacbfccd0f5f3d4a/src/main/java/com/telepathicgrunt/repurposedstructures/RSAddFeaturesAndStructures.java#L97-L99

**Comment by SlimF** [comment]
My English isn't the best so apologies if I wasn't clear with what I said.

Both Yung's and RS mineshafts spawn. My suggestion is this, instead of RS creating mineshafts that follow the vanilla mineshaft design, let it use Yung's mineshaft design.

As you can see on the first picture, this is a standard Yung's mineshaft. On the second is a RS jungle mineshaft. My idea suggests for RS to create a mineshaft that uses Yung's design instead of the vanilla one. So all the oak planks, fences etc. in the first picture would be replaces with their jungle counterparts. Hopefully that makes sense. Again, apologies for my English!


![2021-01-01_18 11 28](https://user-images.githubusercontent.com/6482572/103442220-ef465c00-4c5c-11eb-8bcc-b46b2fe9728c.png)
![2021-01-01_18 12 13](https://user-images.githubusercontent.com/6482572/103442225-f5d4d380-4c5c-11eb-9888-7e846d2ae1ae.png)

**Comment by TelepathicGrunt** [comment]
Ah. That would be a better suggestion for Yung's as my mineshafts are suppose to be vanilla based. To do yung style Mineshafts, I would just end up copying his mod entirely which I rather not do (copying mods exactly is very frowned upon in modding). And would break the purpose of my mod. 

However, he can easily add variants on his end though. Try and suggest this to him as he might like the idea! I can go ask him if you want me to.

**Comment by SlimF** [comment]
I would be grateful if you do it as it'll take me half an hour to explain what I mean hahaha

**Comment by TelepathicGrunt** [comment]
Done. I just let him know now!

**Comment by TelepathicGrunt** [comment]
Turns out, the Better Mineshaft dev already has 9 biome variants of his Mineshafts. Try exploring a bit and you might find them! I didn't know he variants already either but that is pretty neat
