### ISSUE TITLE
End structures to add

### ISSUE THREAD

**Issue by TelepathicGrunt** [TelepathicGrunt/RepurposedStructures#43]
All suggestions and planned stuff goes here:
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/5

**Comment by AbsorbingSafe11** [comment]
Would a rare endermite dungeon be possible to add?
(since it is so difficult to find any endermites)

**Comment by TelepathicGrunt** [comment]
@AbsorbingSafe11 End Dungeons already have an 86% chance of having an Endermite spawner. These dungeons can be found rarely along the sides of the islands. However, End Mineshafts always has Endermite spawners and End Dungeons tend to spawn more often in these Mineshafts. Both of these features can be found in End category biomes (not the Ender Dragon island tho). I hope this helps!

https://github.com/TelepathicGrunt/RepurposedStructures/blob/master/src/main/resources/data/repurposed_structures/rs_spawners/dungeon_end.json
https://github.com/TelepathicGrunt/RepurposedStructures/blob/master/src/main/resources/data/repurposed_structures/rs_spawners/mineshaft_end.json

**Comment by AbsorbingSafe11** [comment]
Are the chances of them spawning configurable? (because I have explored much of my End dimension and never found any)
Also, extra sorry for asking for an already added feature twice.

**Comment by TelepathicGrunt** [comment]
@AbsorbingSafe11 nah it's fine lol. And yes, you can change the spawnrates in the configs. endDungeonAttemptsPerChunk is how many positions the game will try to spawn a dungeon at per chunk (by making sure there's enough solid and open space around the spot). endMineshaftSpawnrate changes the mineshaft spawnrate with higher numbers being more common (1000 is maximum spawnrate. default is 40)
