### ISSUE TITLE
Overworld structures to try and add maybe 

### ISSUE THREAD

**Issue by TelepathicGrunt** [TelepathicGrunt/RepurposedStructures#44]
All suggestions and planned stuff goes here:
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/4

**Comment by AbsorbingSafe11** [comment]
Can you please fix woodland mansions to spawn better or more frequently?
 (as in making by them into an improved version or increasing the number of biomes it is able to spawn in)
