### ISSUE TITLE
[Suggestion] Bountiful Integration

### ISSUE THREAD

**Issue by NJL5390** [TelepathicGrunt/RepurposedStructures#48]
Hello there!
I've been using a mod called Bountiful lately, which adds bounty boards to villages which you can take bounties from, like the one in the picture below:
![2021-01-31_21 46 36](https://user-images.githubusercontent.com/64381954/106398976-f1433c80-640d-11eb-8cbb-56fa4a1081a4.png)
Currently, This structure/building only spawns in vanilla villages which can lead to modded villages feeling a bit inconsistent with vanilla ones when Bountiful is installed.

My suggestion is that a version of this structure/building with the bounty board from the mod should be able to spawn in the village variants that are added by your mod (except maybe the nether themed ones, though it's up to you). This would essentially mean that the player would be able to find and take bounties from the bountiful mod no matter which type of village was near them rather than them needing to find a vanilla village to know that bounties are a thing. 

Here's a link to the mod's Curseforge page if you want to have a look at it: https://www.curseforge.com/minecraft/mc-mods/bountiful

(I'm not sure on which mod's end this would be implemented so I've opened an issue on Bountiful's github as well: https://github.com/ejektaflex/Bountiful/issues/113)

**Comment by TelepathicGrunt** [comment]
This would probably most likely have to be implemented on their end. That is assuming every village gets only exactly 1 bounty board. I'll mention it on their github

**Comment by TelepathicGrunt** [comment]
Good news! Bountiful's latest update now adds their boards to Repurposed Structures's villages! I also just PR'ed some code to help them customize what blocks the bounty boards uses per village. I'll close this now as compat is here!

**Comment by NJL5390** [comment]
Fantastic! Thank you! 

You are one of the most helpful mod developers I've ever seen on here! You always seem willing to help others, especially other developers and I greatly appreciate it.

Thanks again and keep up the great work!
