### ISSUE TITLE
Mod compat with end remastered 

### ISSUE THREAD

**Issue by Scapul23** [TelepathicGrunt/RepurposedStructures#49]
Hello, idk if you have or haven't heard of this mod but it's called end remastered. It is a mod that revamps the way of getting to the end, one of which is that you have to get 11 different eyes of ender to go to turn on the portal. 

Some of these eyes are found in specific biomes in structures like temples (ie. the jungle temple and desert temple).  It would be cool if say the rogue eye (jungle temple) could also spawn in the jungle fortress and jungle dungeons and the old eye spawn in desert temples and outposts. The same for the other biomes as well.

Thanks for reading.

**Comment by Scapul23** [comment]
oh yeah and a link the mod. https://www.curseforge.com/minecraft/mc-mods/endremastered

**Comment by TelepathicGrunt** [comment]
You can actually add their items to Repurposed Structures chests easily. Here's a datapack of RS's chest loot. All that is needed is adding their eyes to all the chests you want and it should spawn when you put on the pack. When I get time myself, maybe I'll make a datapack myself to distribute on RS's mod page that best reflects the rarity that end remastered was going for with their eyes. But you dont have to wait for me and can add the eyes yourself

https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/releases/tag/0.0.11

**Comment by Scapul23** [comment]
oh thanks for responding quickly, I'll take a look at the data pack you sent me. Thank you!

**Comment by TelepathicGrunt** [comment]
I left a comment on their github as it seems like they can easily add support for repurposed structure's chests with just a few lines. Keep watch on this report to see when they will support RS out-of-the-box! https://gitlab.com/endrem/end-remastered/-/issues/11

Until then, yeah making a datapack is the best solution

**Comment by Scapul23** [comment]
yay

**Comment by TelepathicGrunt** [comment]
v2.5.0 Repurposed Structures now has code to automatically import any modded item from vanilla structures into my own structures! Closing this now

**Comment by daynightcycle** [comment]
In 1.20.1 a grassy igloo had a "lost eye" in it's loot chest, I'm assuming because it's rolling a mineshaft loot table, as the lost eye is supposedly mineshaft exclusive. I could add grassy igloo to the config's list of structures that won't pull modded loot, but idk how to efficiently check what other RS structures are pulling from mineshaft loot. If a lot of structures are pulling from mineshaft loot it would be nice if I could disable structures from pulling from certain loot tables or mods even.

I'm new to datapacks so I'm hoping there's a reasonable solution I'm not seeing.

**Comment by TelepathicGrunt** [comment]
@daynightcycle look at this class to see what structure loot table on left side is pulling eyes from loot on right side https://github.com/TelepathicGrunt/RepurposedStructures/blob/1.20-Arch/common/src/main/java/com/telepathicgrunt/repurposedstructures/misc/lootmanager/EndRemasteredDedicatedLoot.java

**Comment by daynightcycle** [comment]
Thanks. Really helpful
