### ISSUE TITLE
[1.16.4] Eye Spy Advancement

### ISSUE THREAD

**Issue by optmisticnihilist** [TelepathicGrunt/RepurposedStructures#51]
I'm testing a modpack that has both Mana and Artifice and Repurposed Structures. One task of Mana and Artifice is finding a stronghold which is completed by getting the Eye Spy advancement. Eye Spy The Overworld doesn't trigger getting that advancement. I want to either have Eye Spy The Overworld trigger completing Eye Spy or have Mana and Artifice accept the Eye Spy The Overworld advancement. I think I could do either using KubeJS however I still don't have a clue how to, even after looking at https://mods.latvian.dev/books/kubejs.

https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice

**Comment by TelepathicGrunt** [comment]
You can use a datapack to modify the vanilla advancement to point to RS's stronghold. I didn't do this myself in the mod as it would replace the advancement file which might mess with another mod that tries to do the same. So it's better for users to decide if they want the vanilla advancement to trigger as well besides the RS's one. 

Here's a quick datapack i put together. I believe it should work and make the vanilla eye spy work for both vanilla and RS strongholds. The key is the criteria section makes some conditions such as entering structures. And then the trigger section states that criteria as the trigger. You can mess with that to add other structures as well!
[RS_EYE_SPY_ADVANCEMENT.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/5945218/RS_EYE_SPY_ADVANCEMENT.zip)

**Comment by TelepathicGrunt** [comment]
Actually, lmk if the eye spy does trigger but the task doesnt complete. IF that is the case, then they are testing for the stronghold directly and would need to do dedicated mod compat with my mod.

**Comment by optmisticnihilist** [comment]
It worked with KubeJS and counted as completing the task for Mana and Artifice.  Thank you
