### ISSUE TITLE
[Suggestion] Re-add compatibility with Quark

### ISSUE THREAD

**Issue by GeorgeOrwell1** [TelepathicGrunt/RepurposedStructures#56]
I'm using the latest (repurposed structures-1.16.5-2.4.1) version of repurposed structures, and it seems that the Quark compatibility (i.e Quark chests spawning in your structures) has been removed. I don't know if this is intentional or not, but I really liked that compatibility, and I hope you re-add that feature. Here's an image of an oak post showing it:
![2021-02-20_09 30 16](https://user-images.githubusercontent.com/72312697/108589373-4663d580-735e-11eb-92d0-4668efff27c3.png)

**Comment by TelepathicGrunt** [comment]
I believe the quark compat stuff is handled by their configs. You’ll have to add new structures to their config for their chests to spawn in iirc

**Comment by TelepathicGrunt** [comment]
Yep. You just need to look into their config and add the new structures to this list 	https://github.com/Vazkii/Quark/blob/803cb60e3fdd37c4f006bdfc8d3c4c88cd5c2d71/src/main/java/vazkii/quark/content/building/module/VariantChestsModule.java#L88

**Comment by TelepathicGrunt** [comment]
Latest quark's config should now have the new Repurposed Structures's structures in it now. Update quark and then go into the config for the chest and reset to default. That should update it automatically i think

**Comment by GeorgeOrwell1** [comment]
Thanks! 👍
