### ISSUE TITLE
[Crash 1.16.4] Problems with RS + Swamp Expansion, server crash

### ISSUE THREAD

**Issue by PaffcioStudio** [TelepathicGrunt/RepurposedStructures#57]
Hello, recently after finding some structures from this mod the server crashes. The Swamp Expansion mod is not available for version 1.16.4 and is required by Repurposed Structures. Is there any way to fix this error? I would ask for your help. Greetings.
[crash-2021-02-20_13.31.22-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/6015015/crash-2021-02-20_13.31.22-server.txt)

**Comment by TelepathicGrunt** [comment]
Swamp expansion is not required by repurposed structure. Remove the swamp expansion datapack as like I stated on curseforge, that datapack is only for 1.15.2 with swamp expansion on
