### ISSUE TITLE
Water Structures generating on beaches

### ISSUE THREAD

**Issue by Matthysse** [TelepathicGrunt/RepurposedStructures#6]
Hello!

There is a big problem : the mod generates water structures on the beach with the Terraforged mod. It creates ugly water boxes. I don't have images to show now, maybe later.

**Comment by TelepathicGrunt** [comment]
Is the water boxes the Ocean Dungeons or the Ocean Mineshaft?

**Comment by TelepathicGrunt** [comment]
I just opened up a Terraforged world with Repurposed Structures and explored a giant beach. However, I don't see any boxes of water. Did you change the setting for Terraforged's generation? And if so, what was the setting you were using for Terraforged? If I can figure out how to reproduce this issue, I might be able to fix it.

**Comment by TelepathicGrunt** [comment]
Ah finally found one. Interesting 
![image](https://user-images.githubusercontent.com/40846040/82211057-38b88580-98de-11ea-87f7-59843316557c.png)

**Comment by Matthysse** [comment]
Yes it's pretty rare, I didn't changed any option. Yes like the image shows it does that only with Water Dungeons. I think it comes from the fact that ocean biome starts but with Terraforged, the depht of the water increases very slowly.

**Comment by TelepathicGrunt** [comment]
Ok I threw some sealevel checks into the ocean dungeon and it seems that solved the problem completely! 

v1.4.2 is now on curseforge with the fix.
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures

Thank you for reporting this issue! I'll close the report now. Just open a new report if the issue still persist or you find another problem :)
