### ISSUE TITLE
conflict with InstantLava

### ISSUE THREAD

**Issue by MoonMoonShark** [TelepathicGrunt/RepurposedStructures#62]
**Your Environment**
- InstantLava version: InstantLava_Forge1.16.1-1.2.1.jar
- Repurposed Structures version: repurposed_structures-1.16.5-2.4.4.jar
- Minecraft version: 1.16.5
- Mod loader (Forge or Fabric): Forge
- Mod loader version: forge-36.0.43

**Describe the bug**

conflict with InstantLava. i can run the game with one or the other, but not both together.
https://www.curseforge.com/minecraft/mc-mods/instantlava

**Steps to reproduce:**
1. create new Curseforge profile
2. add both InstantLava and Repurposed Structures mods
3. hit Play

**Does this issue occur when you only use this mod?:**
 No

[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures/files/6080929/latest.log)

[crash-2021-03-03_23.38.12-fml.txt](https://github.com/TelepathicGrunt/RepurposedStructures/files/6080927/crash-2021-03-03_23.38.12-fml.txt)

_Thank you for reporting the bug!_

**Comment by TelepathicGrunt** [comment]
I’m going to sleep right now but I’ll check this out tomorrow. Looks like you reported on their GitHub as well. 

gonna paste their issue report here so I can quickly find it tomorrow lol
https://github.com/mystiacraft/instantlava/issues/5

**Comment by parly** [comment]
This was a bug on the InstantLava side (initialization timing problem) and I fixed just a while ago. So please regard this issue closed.

**Comment by TelepathicGrunt** [comment]
Ah nice. Thank you! I'll close this

**Comment by MoonMoonShark** [comment]
thanks team!
