### ISSUE TITLE
Nether Outposts Spawn griefers and creeper enclosures when savage and ravage datapack is installed

### ISSUE THREAD

**Issue by NJL5390** [TelepathicGrunt/RepurposedStructures#63]
Firstly, I want to thank you for making this datapack! It's great for consistency!

I've noticed that when looking at these new outpost designs in the nether, they will still spawn creeper enclosures and greifers, which doesn't make sense to me since the nether ones are meant to be piglin outposts not illager outposts, but I do like that they are included in the overworld variants!

Would it be possible to make this particular structure and mobs that spawn with it only spawn in the overworld variants of the outpost and not the nether variants? 

Thanks a lot and keep up the great work!
![2021-03-04_22 12 26](https://user-images.githubusercontent.com/64381954/110038992-720c9580-7d38-11eb-89e6-c278335c046e.png)
![2021-03-04_22 07 18](https://user-images.githubusercontent.com/64381954/110038967-691bc400-7d38-11eb-8bda-29b6468f5ed2.png)

**Comment by TelepathicGrunt** [comment]
oops.  Super easy fix tho. Just needed to delete the base plates from the nether outposts folder. Try this. Does this work?
[Repurposed_Structures-Savage_And_Ravage.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/6087038/Repurposed_Structures-Savage_And_Ravage.zip)

**Comment by TelepathicGrunt** [comment]
I can't really replace the pit part with a custom pit as it is a code feature in the Savage & Ravage mod and not a structure nbt piece. But I can exclude it from the nether outposts

**Comment by NJL5390** [comment]
> oops. Super easy fix tho. Just needed to delete the base plates from the nether outposts folder. Try this. Does this work?
> [Repurposed_Structures-Savage_And_Ravage.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/6087038/Repurposed_Structures-Savage_And_Ravage.zip)

Yeah, That appears to have done the trick.



> I can't really replace the pit part with a custom pit as it is a code feature in the Savage & Ravage mod and not a structure nbt piece. But I can exclude it from the nether outposts

That's fine, deleting it from the nether ones is all I really need. Thanks!

**Comment by TelepathicGrunt** [comment]
Nice. closing now. The Datapack in the release section is now updated!
