### ISSUE TITLE
Broken mineshaft configs

### ISSUE THREAD

**Issue by ShootToKillSTK** [TelepathicGrunt/RepurposedStructures#68]
Noticed that nether mineshafts don't generate above lava level at all despite even changing the min and max generation, same as the end mineshafts.  Would be nice to control/improve this as it makes the nether one especially irrelevant bc most or all are under lava pools. Also makes most nether dungeons spawn under lava too.

**Comment by TelepathicGrunt** [comment]
Oh i see the issue in my code. I did a big dumb with all mineshaft's height configs. Will fix in next update

**Comment by TelepathicGrunt** [comment]
Minehsaft configs are now fixed in v2.5.1! It should now be approved on curseforge so try it out. Thank you for reporting this issue!
