### ISSUE TITLE
[Suggestion] Little structures

### ISSUE THREAD

**Issue by Matthysse** [TelepathicGrunt/RepurposedStructures#7]
Hello !
I love the mod, I just wish there was more structures like ruins or things like that. I know there is the Ruins mod for 1.15.2 but I thing they are ugly.
I would like to build them for you ! It thought of a tower ruin in the mountains, a farm ruin in the plains, japanese shrines ruins in the bamboo forest. It would make exploration far more interesting!

**Comment by TelepathicGrunt** [comment]
I am open to the idea of more ruins! Though if new ruins gets added, I would like to them close to the style of Ocean Ruins as the scope of this mod is suppose to be regular vanilla structures with more themes. 

If you know how to make and save small builds into structure .nbt files, you can definitely make the builds and give me the nbt files. I, then, can adjust it some more and make them spawn in this mod as well as adding you as a contributor to the project. :)

**Comment by Matthysse** [comment]
Nice ! But it would be difficult to do a farm ruin in the style of the ocean ruin, I thought of really small walls of cobble to with a broken first floor and a chest with wheat, carrots, for getting food in early-game

**Comment by TelepathicGrunt** [comment]
Moving this over to my list of suggestions instead lol. i'll close this here as I am consolidating the ideas together
