### ISSUE TITLE
[Feature suggestion] Waystones from Waystones mod appear in structures

### ISSUE THREAD

**Issue by AbacusOperator** [TelepathicGrunt/RepurposedStructures#71]
### Idea
If [Waystones](https://www.curseforge.com/minecraft/mc-mods/waystones) mod is installed, with certain probability (33% is good in my opinion as structures are not that common anyway) a waystone appears in the following types of structures:

- Villages
- Fortresses
- Cities
- Monument

It would be good if they are placed in the one or two specifically designated places. For villages this near the bell or market spot, for cities it is at the top of tower, etc.

**Comment by TelepathicGrunt** [comment]
Does waystones add their waystone to any vanilla structures? I can't seem to find a waystone in vanilla structures. Also, Repurposed Structures does not have any monuments yet so if this actually a request to spawn waystones in vanilla structures, you should ask Waystone developers for that instead. Once they have their system for adding waystones to structures, the can easily add it to my mod's structures no problem like how Bountiful does it

**Comment by TelepathicGrunt** [comment]
Hmm. Looks like they were going to add waystones to villages but either couldn't get it working or decided not to implement it https://github.com/blay09/Waystones/blob/bd3bf5c3394e545556614f553fa3b6470daa1f88/src/main/java/net/blay09/mods/waystones/worldgen/ModWorldGen.java#L95-L120

**Comment by AbacusOperator** [comment]
> Does waystones add their waystone to any vanilla structures? I can't seem to find a waystone in vanilla structures.
They seem to place them randomly without tying them to structures, but the reason I suggested this feature is because I already seen two structures mods integrating Waystones:
- [Towers Of The Wild](https://www.curseforge.com/minecraft/mc-mods/towers-of-the-wild)

- [When Dungeons Arise](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)

**Comment by TelepathicGrunt** [comment]
I asked in Waystone discord if the devs needs help with adding their waystones to vanilla villages. Once that's done, they can just check if my mod is on and add their waystone pieces to my village's pools super easily. That way users won't need a datapack for direct compatibility

**Comment by TelepathicGrunt** [comment]
I made a PR to them to help get their waystones to spawn in vanilla villages and my mod's villages. Keep watch on the PR to see when Waystones will get the functionality! https://github.com/blay09/Waystones/pull/354

**Comment by TelepathicGrunt** [comment]
Good news! v7.5.1 of waystones now should be able to add waystones to RS villages and vanilla villages as well!
