### ISSUE TITLE
[Feature suggestion] Hybrid structures

### ISSUE THREAD

**Issue by AbacusOperator** [TelepathicGrunt/RepurposedStructures#72]
### Idea
One way of repurposing structures is to combine them.
For example:
- **Pillaged village**: ruined village that has illagers instead of undead, includes pillager tower and maybe enclosures with captive villagers.
- **Corrupted village**: ruined warped or crimson village in Overworld, populated with wither skeletons and zombified piglins.
- **High temple**: pyramid with temple on top of it.

**Comment by TelepathicGrunt** [comment]
That are great ideas but that's far out of scope of my mod. Repurposed Structures is about making new biome variants of existing vanilla structures. Making hybrid structures is really just a completely new and unique structure which doesn't fit with the goal of the mod. A different mod could take up your ideas however!
