### ISSUE TITLE
[Suggestion][Forge] Put Repurposed Structure Configs in a directory named "repurposedstructures" (will do in 1.17)

### ISSUE THREAD

**Issue by CorgiTaco** [TelepathicGrunt/RepurposedStructures#74]
![image](https://user-images.githubusercontent.com/66983020/113472596-3806e000-9419-11eb-993e-cd9a4f28589d.png)

Ples

**Comment by TelepathicGrunt** [comment]
Pay me $50 and I’ll do it! 

Jk. Though I cannot put it into a new directory now as that would break everyone’s configs and worlds. I’ll make note to do this in 1.17 as a major breaking change

**Comment by TelepathicGrunt** [comment]
changed plans. 1.16.5-3.0.0 repurposed structures now has a dedicated config folder with MORE config files! I know you love them config files! lel
