### ISSUE TITLE
Some structures have incorrect materials

### ISSUE THREAD

**Issue by Brun333rp** [TelepathicGrunt/RepurposedStructures#75]
While i was testing the mod, I noticed that some structures use inconsistent materials, materials that are part of their original counterparts or are not correctly distributed. Here are the ones I found so far:

**Desert Mansions:**

Desert Mansions have Dark Oak related blocks
![2021-04-02_22 30 25](https://user-images.githubusercontent.com/77504298/113493923-3ccfa080-94ba-11eb-8bad-e7759ab29bf9.png)

![2021-04-02_22 31 06](https://user-images.githubusercontent.com/77504298/113493937-5bce3280-94ba-11eb-93aa-e650329d1738.png)

![2021-04-02_22 31 32](https://user-images.githubusercontent.com/77504298/113493948-730d2000-94ba-11eb-9205-241687acb600.png)

![2021-04-02_22 32 32](https://user-images.githubusercontent.com/77504298/113493962-8b7d3a80-94ba-11eb-9d09-845553185929.png)

![2021-04-02_22 32 43](https://user-images.githubusercontent.com/77504298/113493966-933cdf00-94ba-11eb-8896-45c41b6a87f2.png)

![2021-04-02_22 32 54](https://user-images.githubusercontent.com/77504298/113493970-98019300-94ba-11eb-90fa-0344621497f6.png)

![2021-04-02_22 35 06](https://user-images.githubusercontent.com/77504298/113493975-9cc64700-94ba-11eb-989c-443f239f9c55.png)

Solution: Replace them with Jungle or Birch blocks
_________________________________________________________________________________________________________________________________________
**Birch Mansion**

Birch Mansions have Oak related blocks

![2021-04-02_22 38 04](https://user-images.githubusercontent.com/77504298/113494022-06465580-94bb-11eb-865d-8a2ffaaab445.png)

![2021-04-02_22 38 19](https://user-images.githubusercontent.com/77504298/113494026-0d6d6380-94bb-11eb-8aaf-953362fa9337.png)

![2021-04-02_22 38 47](https://user-images.githubusercontent.com/77504298/113494028-15c59e80-94bb-11eb-9f47-cfd68373dacd.png)

![2021-04-02_22 39 01](https://user-images.githubusercontent.com/77504298/113494033-21b16080-94bb-11eb-80a1-751346479a88.png)

Solution: Replace them with Birch blocks. Oak blocks next to Bookshelves should be kept though.

Also, I found this illager statue that was incomplete. Idk if this is something related with the mansion itself or caused by terrain generation. Note that part of the floor next to it was incomplete as well
![2021-04-02_22 41 16](https://user-images.githubusercontent.com/77504298/113494061-56bdb300-94bb-11eb-9c9a-895a5632f341.png)
_________________________________________________________________________________________________________________________________________

**Oak Mansion**

1. Entrance and staircase to the second floor use Red Carpets.

![2021-04-02_22 55 43](https://user-images.githubusercontent.com/77504298/113494174-4823cb80-94bc-11eb-81b6-4a0017061fa4.png)

![2021-04-02_22 56 01](https://user-images.githubusercontent.com/77504298/113494141-f7ac6e00-94bb-11eb-9e1c-c93c7e475443.png)

Solution: Replace them with Brown Carpets

2. Bookshelves have Spruce blocks next to them, wich looks weird.

![2021-04-02_22 56 27](https://user-images.githubusercontent.com/77504298/113494212-ac468f80-94bc-11eb-9c65-4a8435d06178.png)

![2021-04-02_22 57 41](https://user-images.githubusercontent.com/77504298/113494216-b4063400-94bc-11eb-9669-657586504b32.png)

Solution: replace them with Oak blocks. But only those that are connected to the bookshelves.
_________________________________________________________________________________________________________________________________________

**Savanna Mansion**

1. Some rooms use a Dark Oak floor.

![2021-04-02_23 05 22](https://user-images.githubusercontent.com/77504298/113494311-853c8d80-94bd-11eb-8615-8b12c7628e4f.png)

Solution: Replace the floor with Oak blocks

2. Cobblestone Stairs and Slabs are replaced with Dark Oak ones.

![2021-04-02_23 05 12](https://user-images.githubusercontent.com/77504298/113494331-b74def80-94bd-11eb-9a76-5a23a62e5c88.png)

![2021-04-02_23 08 13](https://user-images.githubusercontent.com/77504298/113494333-bd43d080-94bd-11eb-8db1-9996e5f07496.png)

![2021-04-02_23 08 03](https://user-images.githubusercontent.com/77504298/113494341-c339b180-94bd-11eb-9b84-0fa4ecfbc195.png)

![2021-04-02_23 06 47](https://user-images.githubusercontent.com/77504298/113494348-c9c82900-94bd-11eb-8f24-d394896e82c2.png)

Solution: Replace them back to Cobblestone
_________________________________________________________________________________________________________________________________________

**Snowy Mansion**

1. Some parts of the mansion use Ice blocks alongside Diorite Stairs and Slabs, wich looks weird.

![2021-04-02_23 14 41](https://user-images.githubusercontent.com/77504298/113494430-7b675a00-94be-11eb-9fb3-04bf3f6b6692.png)

![2021-04-02_23 16 36](https://user-images.githubusercontent.com/77504298/113494437-84f0c200-94be-11eb-96d7-548191950627.png)

![2021-04-02_23 17 52](https://user-images.githubusercontent.com/77504298/113494442-8c17d000-94be-11eb-98dd-564fcfe44eab.png)

![2021-04-02_23 21 37](https://user-images.githubusercontent.com/77504298/113494448-94700b00-94be-11eb-90e2-67f6eae8b64a.png)

![2021-04-02_23 32 33](https://user-images.githubusercontent.com/77504298/113494459-c41f1300-94be-11eb-8747-c11a3c5c671c.png)

![2021-04-02_23 33 08](https://user-images.githubusercontent.com/77504298/113494487-03e5fa80-94bf-11eb-8e17-48645bdd5f48.png)

Solution: Replace these specific parts with Diorite and Polished Diorite. But only those that are next to stairs, slabs and bookshelves.

2. Some rooms use Dark Oak on them.

![2021-04-02_23 11 47](https://user-images.githubusercontent.com/77504298/113494521-5aebcf80-94bf-11eb-8729-ee06c38f976e.png)

![2021-04-02_23 24 18](https://user-images.githubusercontent.com/77504298/113494670-dbf79680-94c0-11eb-9aad-c5ee52a46322.png)

Solution: Replace the floor with Packed ice, just like the rest of the mansion. The fences should either be replaced with Spruce ones, or have a different design, like this:
![2021-04-02_23 27 40](https://user-images.githubusercontent.com/77504298/113494688-06495400-94c1-11eb-9925-d91b3db7f67d.png)

3. Cobblestone is still present in some rooms, wich can also be seen previously.

![2021-04-03_15 21 33](https://user-images.githubusercontent.com/77504298/113494543-9a1a2080-94bf-11eb-8a65-be6dc96ad4b2.png)

Solution: replace the Cobblestone with Diorite and Polished Diorite. And considering the first item, you should also replace most of the ice on this room as well.

OBS: This room also uses a Dark Oak floor.

![2021-04-03_15 24 40](https://user-images.githubusercontent.com/77504298/113494590-ff6e1180-94bf-11eb-980c-1f87f108699f.png)
_________________________________________________________________________________________________________________________________________

**Taiga Mansion**

Birch stairs, slabs and fences are present in some rooms.

![2021-04-03_16 09 10](https://user-images.githubusercontent.com/77504298/113494651-9f2b9f80-94c0-11eb-8fbb-ded82ecbd454.png)

![2021-04-03_16 30 24](https://user-images.githubusercontent.com/77504298/113494652-a5218080-94c0-11eb-8458-58fba3d1c0a1.png)

Solution: Replace them with Cobblestone, though these that are part of chairs and tables should be replaced with Andesite.

Also, not exactly a bug, but I bet this statue is supposed to be a fox. But it looks more like a cat than a fox.

![2021-04-02_23 41 11](https://user-images.githubusercontent.com/77504298/113494728-8a9bd700-94c1-11eb-9233-843f4f82bab5.png)
_________________________________________________________________________________________________________________________________________

Well, these are the ones I discovered so far. If I forgot something, I'm sorry.

**Comment by TelepathicGrunt** [comment]
Fun fact, vanilla mansions actually uses multiple wood types. They use dark oak, oak, birch wood. Many of the mansion pieces you shown here was my direct 1-to-1 replacements working as intended. Although some can be made better to fit their theme which means they will become no longer similar to vanilla mansion's placements.

Gonna try and go through everything you listed:

Desert Mansions dark oak should be sandstone wall except for the cage. Sandstone walls looks terrible as you cannot see inside the cage so I'll only be replacing the dark oak fences that hold up torches and stuff. Cages and that fence room will remain dark oak fences. The dark oak door will remain dark oak unless jungle/acacia door looks better. I'll have to place it down in person to see. 

Birch Mansion's oak blocks will remain as oak blocks. When converting the vanilla mansion to birch mansion, I turned their Birch wood to Oak wood and then turned their Dark Oak wood to Birch wood. So the birch mansion is actually correct and has the multiple wood type in the right places to match vanilla mansions. The incomplete floor/wall thing you found is a bug with how mansions generates in general. In fact, take a closer look at vanilla mansions. Sometimes you may find holes between the second and third floor that leads outside the mansion. It's wacky lol.

Oak Mansion's entrance carpet... oops. yeah I gotta fix that. The bookshelf part is a good catch and I'll make those be oak wood since the 1-to-1 replacement for that wood didn't work out nicely in the end for the bookshelves.

Savanna Mansion's dark oak wood was intended to replace cobblestone stairs and stuff to try and fit better. But I guess it didn't work out so I'll bite the bullet and revert those back to cobblestone.

Snowy Mansion's diorite with ice, I thought it looked good but guess now. I'll mess with that and see if full diorite looks better. The Dark Oak wood will remain as they are necessary for gates and cage fences. 

Taiga Mansion's birch wood will remain to match vanilla mansion's multiple wood usage. And about the fox, oof. I tried my best but I cannot make a better statue. That was the best I can do so it has to stay as is for now unless someone sends me an nbt file of a better tiny fox statue. 

Thank you for your report! I'll be going though the nbt pieces to work on some of these stuff

**Comment by TelepathicGrunt** [comment]
Oh actually about that pillager face wall, that looks to be intended. Dig inside for the actual room. one of the wall is that face and it can show bare like so. Vanilla piece picture:
![image](https://user-images.githubusercontent.com/40846040/113518458-79e87100-9554-11eb-8fba-7e6c5fb02343.png)

**Comment by Brun333rp** [comment]
>  Cages and that fence room will remain dark oak fences.

Well, you know that there are other fitting materials for this, right? These should be either Jungle to fit with desert villages (since they use Jungle wood in certaing parts) or Birch to fit with sandstone (similar with how you did with desert outposts).

> Taiga Mansion's birch wood will remain to match vanilla mansion's multiple wood usage.

But as you can see, in some parts there's a mix of Cobblestone and Birch, wich looks weird. As it seems, Cobblestone was meant to replace Birch Planks, since the floor uses Cobblestone. So I assumed that you forgot to replace Birch Slabs, Stairs and Walls with Cobblestone ones.

> The Dark Oak wood will remain as they are necessary for gates and cage fences.

Spruce wood is a alternative. Dark Oak would not look bad, but Spruce makes more sense with the icy theme of the building.

**Comment by TelepathicGrunt** [comment]
2) The stairway is perfectly fine and isnt suppose to be cobblestone at the top. hence the birch stairs. The arch thing was changed to be fully birch. I did change that arch in several of the other mansions to be one type of block as it seemed the script replacement didnt work so well for that particular piece.

1 and 3) I actually like the darkness of the dark oak wood against the light ice and sandstone. Testing with other wood types feels too light and loses that slight illager feel. I'm not entirely sold on making them not dark oak. Especially as mojang seems to be ok with outposts using dark oak in any biome it is in so illagers have access to dark oak everywhere. In fact, I probably should be using more more dark oak as that's a signature wood type for illagers. hmm

**Comment by TelepathicGrunt** [comment]
Ah i see what you mean about the stairs. That piece I was suppose to do by hand since the floor was made to be cobblestone but shouldnt be cobblestone on the stair part. I'll change that to either oak, spruce, or dark oak wood to look better depending on which fits best

**Comment by TelepathicGrunt** [comment]
Big update to repurposed structures is now released! I squeezed in a bunch of suggestions form here into it
