### ISSUE TITLE
readable indentation in lootTables 

### ISSUE THREAD

**Issue by Torben8** [TelepathicGrunt/RepurposedStructures#78]
Just a small request for a readable indentation in the lootTables of the mod.
Otherwise it is really hard for modpack creators to know the content.
Not a must have, but wuld be really handy.

**Comment by TelepathicGrunt** [comment]
The indentation I went with comes from the vanilla loot tables themselves. I do not know what a better format would be or how to mass format all my loot tables at once. There is 103 loot table files so if someone can PR in the change or show me how to automatic formatting them all, I'll do it but it is too much work for me to do by hand.

**Comment by TelepathicGrunt** [comment]
Oh if you are talking about the indentation when viewing in github, that's actually kinda github's fault and you can change how wide it makes the tabs. 

Go to the loot table and click the edit button on the right
![image](https://user-images.githubusercontent.com/40846040/113789483-2e2cf780-970d-11eb-893b-6864f79c9f29.png)


Change indent size to 2
![image](https://user-images.githubusercontent.com/40846040/113789500-37b65f80-970d-11eb-8891-83d821e8e113.png)

And now loot tables should look the same as if you open them in notepad.
![image](https://user-images.githubusercontent.com/40846040/113789525-46047b80-970d-11eb-91bc-06dda1632c5d.png)


I though you meant like a completely different format until I re-read what you said. I can find-replace tabs with spaces tho to tell off GitHub's dumb tab spacing viewing lol

**Comment by TelepathicGrunt** [comment]
Ok using the find/replace comment to swap tabs for 2 spaces, the files should look more readable in github. I still blame github's default for showing tabs as 8 spaces. It's so ridiculous lol

But yeah, it should be good now! (though reformatting the loot tables themselves into a different format isnt a bad idea but not sure what good format is)

**Comment by Torben8** [comment]
Oh i did not mean the lootTables from github, I have never looked at them, probably should have...
But somehow the lootTables in the mods .jar-file are kind of messed up and the whole lootTable is on one line, that was what I meant.
But the files on github are fine for me, will use those in the future, thanks!

**Comment by TelepathicGrunt** [comment]
Ah that. I minify my json which one-lines everything in order to reduce the file size of my jar. The minifying saves me half a megabyte last I checked. But yeah, the tables are viewable on github like so and also, I got a datapack here of the formatted jsons too that you can downlaod and check out. https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/releases/tag/0.0.11

Lots of options and have fun! :)
