### ISSUE TITLE
[Forge] Failed to get mob

### ISSUE THREAD

**Issue by oguh43** [TelepathicGrunt/RepurposedStructures#79]
[22:28:03] [Worker-Main-91/INFO] [STDOUT/]: [knightminer.simplytea.worldgen.TeaTreeFeature:generate:22]: BlockPos{x=360, y=128, z=661}
[22:28:04] [Worker-Main-82/ERROR] [co.te.re.RepurposedStructures/]:
***************************************
Failed to get mob. Please check that repurposed_structures:dungeon_nether.json is correct or that no other mod is interfering with how vanilla reads data folders. Let TelepathicGrunt know about this too!
***************************************
[22:28:04] [Worker-Main-85/ERROR] [co.te.re.RepurposedStructures/]:
***************************************
Failed to get mob. Please check that repurposed_structures:dungeon_nether.json is correct or that no other mod is interfering with how vanilla reads data folders. Let TelepathicGrunt know about this too!
***************************************
[22:28:19] [Worker-Main-85/ERROR] [co.te.re.RepurposedStructures/]:
***************************************
Failed to get mob. Please check that repurposed_structures:dungeon_nether.json is correct or that no other mod is interfering with how vanilla reads data folders. Let TelepathicGrunt know about this too!

**Comment by TelepathicGrunt** [comment]
Thank you for the report! This was fixed in v2.6.3 repurposed structures a few days ago so try updating to that and see if the issue goes away. If not, let me know and I'll re-open this report and ask for more information

**Comment by oguh43** [comment]
Thanks for the quick reply, and sorry for the scuffed formatting, I was in a rush :)
