### ISSUE TITLE
Repurposed Structure's Dungeons generate weirdly when The Outer End is installed (As of 2.6.0)

### ISSUE THREAD

**Issue by NJL5390** [TelepathicGrunt/RepurposedStructures#80]
Repurposed Structures Version: 2.6.3
The Outer End version: 0.2.8
Abnormals core version: 3.1.1
Forge Version: 36.1.4
Minecraft Version: 1.16.5
Latest Log: https://pastebin.com/SCu2b3BN

Hi,
I've noticed that when looking at your beautiful structures on my test worlds that the dungeons spawned really weirdly, in that they would always spawn as a cube, usually without chests and caves would be unable to cut through them. After some narrowing down of my mod list, I discovered that this only occurred when a mod called The Outer End was installed. This issue was not happening before your latest content update (2.6.0), but I'm still not entirely sure whose mod is responsible for this.

Some Screenshots to show what I mean:
![2021-04-08_21 50 05](https://user-images.githubusercontent.com/64381954/114096050-1e044c00-98b6-11eb-88b4-79d390b400ea.png)
![2021-04-08_21 50 40](https://user-images.githubusercontent.com/64381954/114096085-2ceafe80-98b6-11eb-8c19-eb57a8033a40.png)
![2021-04-08_21 50 46](https://user-images.githubusercontent.com/64381954/114096096-31171c00-98b6-11eb-8b15-fc05ea671be0.png)
![2021-04-08_00 16 56](https://user-images.githubusercontent.com/64381954/114096311-763b4e00-98b6-11eb-8954-6246e41d7143.png)
![2021-04-06_11 18 41](https://user-images.githubusercontent.com/64381954/114096354-83f0d380-98b6-11eb-88d3-29d9e9aa62fe.png)
![2021-04-05_22 11 23](https://user-images.githubusercontent.com/64381954/114096436-9e2ab180-98b6-11eb-8aba-3cf7bfbce35d.png)

I'll be reporting this on their github as well soon. (Update: Here it is: https://github.com/BlueDuckYT/The-Outer-End/issues/26)

**Comment by TelepathicGrunt** [comment]
Most likely has to do with this issue which I already helped fixed for them in a PR. They just need to merge it in and release an update
https://github.com/BlueDuckYT/The-Outer-End/pull/21

The issue is they have a processor that is broken and it is wrecking all other processors as a result. My dungeons and many other structures uses processors for specific behaviors such as not placing blocks in cave space, randomizing blocks, etc. 

Hopefully they will merge it in

**Comment by TelepathicGrunt** [comment]
Also, update repurposed structures to 2.6.3 too as I did some important bugfixes as well. Won't solve this specific issue but still good to update to latest always

**Comment by NJL5390** [comment]
> Most likely has to do with this issue which I already helped fixed for them in a PR. They just need to merge it in and release an update
> [BlueDuckYT/The-Outer-End#21](https://github.com/BlueDuckYT/The-Outer-End/pull/21)
Ok, I'll mention it on my issue post.
> Also, update repurposed structures to 2.6.3 too as I did some important bugfixes as well. Won't solve this specific issue but still good to update to latest always
I already did, I just put 2.6.0 in the post and title because that was the major content update you did recently.

**Comment by TelepathicGrunt** [comment]
v0.2.9 Outer end now resolves the issue! I was able to test this so you can close the report for them as well. :)

**Comment by NJL5390** [comment]
Thanks a lot! You saved me some time, I appreciate it! Especially with how busy I've been lately.
