### ISSUE TITLE
Advancements not showing correctly (FORGE)

### ISSUE THREAD

**Issue by leyxcx** [TelepathicGrunt/RepurposedStructures#82]
This might be a lang json problem, but a lot of the advancements don't show up correctly
![2021-04-15_19 58 07](https://user-images.githubusercontent.com/67163463/114834969-34198b80-9e25-11eb-80ad-062b77a5c4a9.png)
![2021-04-15_19 58 03](https://user-images.githubusercontent.com/67163463/114834975-367be580-9e25-11eb-9a3d-f45f69620860.png)

version: 2.6.3

**Comment by TelepathicGrunt** [comment]
remove the old advancement datapack you have on. The newer repurposed structures changed the key used for advancements so the language files was updated. By using the old advancement datapacks, it breaks a s aresult. 

Let me know if that was indeed the issue

**Comment by leyxcx** [comment]
Ah yeah that's the issue. Didn't realise I'd copied them over with the other files.
