### ISSUE TITLE
Crash during chunk loading

### ISSUE THREAD

**Issue by MrVauxs** [TelepathicGrunt/RepurposedStructures#84]
Hello, our dedicated server crashes whenever a player loads into a newly explored chunk. From the error logs best we could figure out is repurposed structures mod having a play in it.

The error logs can be found here https://pastebin.com/jvTeVcFB

**Comment by TelepathicGrunt** [comment]
Yeah this was fixed in v2.6.5. Try updating RS to that newest version and then let me know if the issue still presists
