### ISSUE TITLE
New chunks hang in nether with pyromancer mod

### ISSUE THREAD

**Issue by cncz42** [TelepathicGrunt/RepurposedStructures#85]
Kind of an obscure [mod](https://www.curseforge.com/minecraft/mc-mods/pyromancer) but this datapack seems to cause a freeze in the nether with this mod, a temporary fix seems to be just removing the nether variants from the datapack

**Comment by TelepathicGrunt** [comment]
I got the world deadlock issue to happen and I did a thread dump to see what line of code the world is stuck on. It seems NetherPyrowoodRootsStructure is not worldgen safe and will deadlock the server. I'll try contacting them s they can fix their feature
https://paste.ee/p/MS4Cy

**Comment by TelepathicGrunt** [comment]
wait a second, this is an mcreator mod. Welp, that explains why it is broken lol. I'll still contact them but this report will be closed as with mcreator mods, mod compat is super sketchy and they generally have a ton of bugs
