### ISSUE TITLE
Global dimension blacklist for structures doesn't work for dungeons and wells

### ISSUE THREAD

**Issue by NJL5390** [TelepathicGrunt/RepurposedStructures#86]
Repurposed Structures Version: 2.6.5
Forge Version: 36.1.13
Twilight Forest Version: 4.0.435

Hi,
I noticed when flying around the twilight forest recently in a test world that some of your structures still seem to be spawning in that dimension, despite that dimension being blacklisted in the config files from being able to spawn your structures. 

More specifically it appears to be the dungeons and well variants that are added by your mod which can't be located via the /locate command. These can rarely spawn in places that interfere with the Twilight Forest's Structures.

![2021-04-28_22 41 44](https://user-images.githubusercontent.com/64381954/116478417-f0d40980-a875-11eb-8c9c-4e19613e015d.png)
![2021-04-28_22 53 28](https://user-images.githubusercontent.com/64381954/116478433-f893ae00-a875-11eb-9b69-d98b8e39753e.png)
![2021-04-28_22 40 21](https://user-images.githubusercontent.com/64381954/116478459-01847f80-a876-11eb-823f-6cb50d5bc6b1.png)
![2021-04-05_22 11 23](https://user-images.githubusercontent.com/64381954/116478605-385a9580-a876-11eb-8b1a-09f61f58c946.png)
![2021-04-06_15 53 59](https://user-images.githubusercontent.com/64381954/116478618-3db7e000-a876-11eb-856b-dde488a0a13d.png)

**Comment by TelepathicGrunt** [comment]
Ah yes, the way the dimension blacklist works only works for structures. Not features. I’ll have the shove them check directly into the features themselves unlike structures

**Comment by TelepathicGrunt** [comment]
can you test this jar to see if it resolves the issue? It should work. If so, i'll release the update soon
[repurposed_structures-1.16.5-2.6.6b-forge.zip](https://github.com/TelepathicGrunt/RepurposedStructures/files/6399277/repurposed_structures-1.16.5-2.6.6b-forge.zip)

**Comment by NJL5390** [comment]
As far as I can tell, it seems to be fixed.

**Comment by TelepathicGrunt** [comment]
update is now out with the fix. Thank you!
