### ISSUE TITLE
[1.16.5] Game crashed with mod "water physics overhaul" in nether

### ISSUE THREAD

**Issue by CHanzyLazer** [TelepathicGrunt/RepurposedStructures#97]
I have tested that when with mod "water physics overhaul" ([curse forge](https://www.curseforge.com/minecraft/mc-mods/water-physics-overhaul)), it can successfully started but it  crashed when I go into the nether.

crash report(just water physics overhaul and repurposed structures):
[minecraft-exported-logs-2021-05-21T00-14-42.log](https://github.com/Sasai-Kudasai-BM/Water-Physics-Overhaul/files/6517370/minecraft-exported-logs-2021-05-21T00-14-42.log)

also reported on water physics overhaul issues page

**Comment by TelepathicGrunt** [comment]
Yeah they mixin to add new waterlogging properties to blocks. However, this is highly unsafe and it will blow up all worldgen json files that uses the blocks that they modified. Including vanilla worldgen datapacks. I'll let them know to switch to how Statement adds waterlogging as that mod added the properties in a safe way that doesn't break vanilla datapacks
