### ISSUE TITLE
[Bug] Weird Snowy Pyramid generation

### ISSUE THREAD

**Issue by CREEATION** [TelepathicGrunt/RepurposedStructures#98]
![2021-05-21_18 04 09](https://user-images.githubusercontent.com/3277769/119166768-4e1b3f00-ba5f-11eb-9d4b-83e8ae30c955.png)

i guess the screenshot speaks for itself. also, not sure if the red sandstone is intentional. that's all 🐢

**Comment by TelepathicGrunt** [comment]
![image](https://user-images.githubusercontent.com/40846040/119167090-6b371a00-ba2d-11eb-82ed-efe9099848a1.png)
shoot. WIll fix. my bad

**Comment by CREEATION** [comment]
all good, awesome work 🐢 is the general location of the pyramid also considered a bug? meaning, "floating" in the air like in the screenshot.

**Comment by TelepathicGrunt** [comment]
no the bug is the red sandstone foundation. Vanilla Pyramids creates Sandstone all the way down under it until it hits the first solid block like this 
![image](https://user-images.githubusercontent.com/40846040/119168447-e947f080-ba2e-11eb-9854-879860aef16f.png)


I reproduce the same behavior for some of my Pyramids. In this case, I copied my Badlands Pyramid but forgot to change the Red Sandstone to Snow Block

**Comment by CREEATION** [comment]
i see 👀 caught another one by accident:

![2021-05-21_18 25 19](https://user-images.githubusercontent.com/3277769/119169185-01853300-ba62-11eb-94e3-5dcdfc2c0db8.png)

the taiga witch hut partially generated into the pyramid here. probably a separate issue, though.

**Comment by TelepathicGrunt** [comment]
That's normal. Structures can fuse together if they spawn too close. Even vanilla structures will do this too. 
![image](https://user-images.githubusercontent.com/40846040/119169448-0630f380-ba30-11eb-8c30-7d364416071d.png)


I decided not to put a separation for all of my structures as it would make structures a bit too rare to find, have some performance overhead, and makes cool combos not possible anymore

**Comment by CREEATION** [comment]
makes sense! thanks for the quick responses. 🐢

**Comment by TelepathicGrunt** [comment]
fixed in v2.7.0 which is now released!
